### PR TITLE
Fixed wrong definition of enum operator that lead to misinterpreting the result and mistaken edge update

### LINKED ISSUE #1405: [BUG] The `checkEdge` function doesn't regard edge-only event `SRT_EPOLL_UPDATE`
**Describe the bug**
The `SRT_EPOLL_UPDATE` bit remains set after returning from epoll waiting functions.

**To Reproduce**
Use Backup groups with builtin use of `swait` See the logs:

```
11:37:43.506660/SRT:RcvQ:w1 D:SRT.d: epoll/update: @124181649 +[U]: EID 1 TRACKING: @124181646:[R][E] @124181648:[R][E] @124181649:[R][U] 
11:37:43.506694/SRT:RcvQ:w1 D:SRT.c: processConnectRequest: @124181649 connected, setting epoll to connect:
11:37:43.506721/SRT:RcvQ:w1 D:SRT.d: epoll/update: @124181649 +[W]: EID 1TRACKING: @124181646:[R][E] @124181648:[R][E] @124181649:[R][U]  NOT updated: no changes
11:37:43.507063/srt-test-live D:SRT.d: EID 1 rdy=1: @124181649:[U]  TRACKED: @124181646:[R][E] @124181648:[R][E] @124181649:[R][U] 
11:37:43.507152/srt-test-live D:SRT.d: group/recv: RDY: @124181649:[U] 
11:37:43.507317/srt-test-live D:SRT.d: epoll/update: @124181648 +[W]: EID 1TRACKING: @124181646:[R][E] @124181648:[R][E] @124181649:[R][U]  NOT updated: no changes
11:37:43.507429/srt-test-live D:SRT.d: epoll/update: @124181646 +[W]: EID 1TRACKING: @124181646:[R][E] @124181648:[R][E] @124181649:[R][U]  NOT updated: no changes
11:37:43.507506/srt-test-live D:SRT.d: EID 1 rdy=1: @124181649:[U]  TRACKED: @124181646:[R][E] @124181648:[R][E] @124181649:[R][U] 
11:37:43.507559/srt-test-live D:SRT.d: group/recv: RDY: @124181649:[U] 
11:37:43.507713/srt-test-live D:SRT.d: epoll/update: @124181648 +[W]: EID 1TRACKING: @124181646:[R][E] @124181648:[R][E] @124181649:[R][U]  NOT updated: no changes
11:37:43.507838/srt-test-live D:SRT.d: epoll/update: @124181646 +[W]: EID 1TRACKING: @124181646:[R][E] @124181648:[R][E] @124181649:[R][U]  NOT updated: no changes
11:37:43.507914/srt-test-live D:SRT.d: EID 1 rdy=1: @124181649:[U]  TRACKED: @124181646:[R][E] @124181648:[R][E] @124181649:[R][U] 
11:37:43.507945/srt-test-live D:SRT.d: group/recv: RDY: @124181649:[U] 
11:37:43.508119/srt-test-live D:SRT.d: epoll/update: @124181648 +[W]: EID 1TRACKING: @124181646:[R][E] @124181648:[R][E] @124181649:[R][U]  NOT updated: no changes
11:37:43.508211/srt-test-live D:SRT.d: epoll/update: @124181646 +[W]: EID 1TRACKING: @124181646:[R][E] @124181648:[R][E] @124181649:[R][U]  NOT updated: no changes
11:37:43.508275/srt-test-live D:SRT.d: EID 1 rdy=1: @124181649:[U]  TRACKED: @124181646:[R][E] @124181648:[R][E] @124181649:[R][U] 
```

As you can see here, the `+[U]` - that confirms that the UPDATE state has been set on the socket - happens exclusively once in the beginning, and then several waiting calls, as reported by `EID 1 rdy=1: @124181649:[U]` are made.

**Expected behavior**
After the call to a waiting function the `[U]` readiness shall be cleared and not reported in further wait calls, until the `+[U]` state update is made again.

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #1405

Two bugfixes:

1. Subscription wasn't taking into account that some flags passed together with the others are always edge-triggered, while edge-triggered version for those that support both wasn't requested. This made an unwanted situation when an always-edge-triggered event was subscribed in level-trigger mode.

2. The operator & was defined incorrectly and actually it didn't do the job it was intended to do, instead caused a bug that resolved the flag & operation into a boolean, then interpreted as 1.

### CODE REVIEW

File: srtcore/epoll.cpp [hunk 1]
```diff
@@ -772,11 +778,16 @@ int CEPoll::swait(CEPollDesc& d, map<SRTSOCKET, int>& st, int64_t msTimeOut, boo
                 {
                     ++total;
                     st[i->fd] = i->events;
-                    d.checkEdge(i++); // NOTE: potentially deletes `i`
+                    IF_HEAVY_LOGGING(singles << "@" << i->fd << ":");
+                    IF_HEAVY_LOGGING(PrintEpollEvent(singles, i->events, i->parent->edgeOnly()));
+                    bool edged ATR_UNUSED = d.checkEdge(i++); // NOTE: potentially deletes `i`
```
Comment (maxsharabayko) [inline srtcore/epoll.cpp:783]:
```suggestion
                    const bool edged ATR_UNUSED = d.checkEdge(i++); // NOTE: potentially deletes `i`
```

File: srtcore/epoll.cpp [hunk 2]
```diff
@@ -328,8 +334,7 @@ int CEPoll::update_usock(const int eid, const SRTSOCKET& u, const int* events)
 
             // Update the watch configuration, including edge
             wait.watch = evts;
-            if (edgeTriggered)
-                wait.edge = evts;
```
Comment (maxsharabayko) [inline srtcore/epoll.cpp:332]: Is this change intended? No need to check for `edgeTriggered`?

Comment (ethouris) [reply srtcore/epoll.cpp:332]: This is another bugfix. This version was mistakenly set either all to edge-triggered or all to level-triggered depending on found `SRT_EPOLL_ET` flag, which didn't work correctly for flags that were always edge-triggered. The `et_evts` as set earlier was set correctly: to represent either ALL events (if `SRT_EPOLL_ET`) was found, or to represent only the "always-edge" events (that is, `SRT_EPOLL_UPDATE`).
