### PR TITLE
Runtime link stability timeout for main/backup

### LINKED ISSUE #1768: [BUG] Main/backup: The activation period ends earlier than expected
## Describe the bug

During testing the RTT estimate convergence for Connection Bonding (main/backup algorithm), I've noticed that the activation period on the main link ends earlier than expected. It happens at the beginning of a transmission, the activation period ends almost right after 1 RTT is passed since the start of a transmission. As a result, the value of link stability timeout changes to dynamic that depends on the incorrect RTT estimate (actually the initial value of 100 ms). At this time, we haven't yet received the first ACK with the first RTT estimate.

Screenshot 2021-01-28 at 18 36 36

Here the first ACK comes
Screenshot 2021-01-28 at 16 53 25

There is also one problem with RTTVar estimate on the sender side, see ticket (TODO: insert the link).

## To Reproduce

See issue #1755 for the reproduction steps.

**Failed test case:**

Test Case 3. Main link shutdown for 40 seconds (higher than `SRTO_PEERIDLETIMEOUT` = 5 s)

Scenario | Main Link (enp7s0)                              | Backup Link (enp8s0)                       | Bitrate, Mbps  | SRT Options    | 
| --------| ------------------------------------ | ----------------------------------- | -------------- | ---------------| 
| -            | RTT1 = 1000 ms (1 s)                          | RTT2 = 1000 ms (1 s)                        | 1                       | latency=4000  |    

**Statistics and screenshots:**
[dlst_scen4_rtt1s_test3 #1768.zip](https://github.com/Haivision/srt/files/5889057/dlst_scen4_rtt1s_test3.1768.zip)

### PR DESCRIPTION
**Pull request by maxsharabayko**
The existing option `SRTO_GROUPSTABTIMEO` sets a timeout for the last response time of a group member link.
The same value is used for all member links.

An optimal timeout value depends on the network conditions (RTT, loss rate), and can be calculated at runtime.

This PR replaces the usage of  `SRTO_GROUPSTABTIMEO`  with a dynamic link stability timeout calculated at runtime.

When an idle or newly connected link is activated, it first transits to an "activation phase" and stays there for `SRTO_PEERLATENCY + 50ms` with the minimum allowed value of 60 ms, and the maximum allowed value of `SRTO_PEERIDLETIMEO`.
It is expected that at the start of sending RTT, RTTVar and link stability are not yet known. Therefore a link needs to stay active for this period to judge if it is stable or not.

After the activation phase ends, the link stability timeout is determined as `2 × RTT+ 4 × RTTVar` with the minimum allowed value of 60 ms, and the maximum allowed value of `SRTO_LATENCY`.

Fixes #1768 

### TODO

- [x] Repurpose `SRTO_GROUPSTABTIMEO` to set the minimum timeout value -> moved to #1792.
- [x] PR #1774 extracts some minor renaming. Update this PR once that one is merged.
- [x] Replace 50ms in activation period with `5 * COMM_SYN_INTERVAL_US`
- [x] The `weight` parameter of `sendBackup_CheckRunningLinkStable` is only needed for tracing. To remove?
  **Decision**: leaving for now. Will be useful for further testing.
- [x] Remove PEERIDLETIMEO from initial stability timeout.
`Initial Link Stability Timeout = max(Minimum Link Stability Timeout, SRT Latency)`, where Minimum Link Stability Timeout = 60 ms
`Activation Period = Initial Link Stability Timeout + 5 * SYN, where SYN=10`
`Dynamic Link Stability Timeout = min(max(Minimum Link Stability Timeout, 2RTT + 4RTTVar), SRT Latency)`

### CODE REVIEW

File: srtcore/group.cpp [hunk 1]
```diff
@@ -2993,6 +2993,118 @@ void CUDTGroup::sendBackup_CheckIdleTime(gli_t w_d)
...
+{
+    // There was already a response from peer while we are here.
+    // m_tsUnstableSince = 0;
+    // Do we need to keep the activation phase?
+    if (currtime <= u.LastRspTime()) {
+#if SRT_DEBUG_BONDING_STATES
+        s_stab_trace.trace(u, currtime, -1, "STABLE");
+#endif
+        return 1;
+    }
```
Comment (maxsharabayko) [inline srtcore/group.cpp:3072]: TODO: remove this condition.
Issue #1768

**Comment by ethouris** [comment]
I think you are forgetting something here. If you need to have some "initial measurement period" to decide the parameter that should remain valid for a long time of functioning of a given link, then this should be the parameter valid in any kind of conditions, no matter what characteristics particular links have.

If you limit RTT measurements only to active links, then it is likely the following situation: you have 3 equivalent links, one with lower RTT connected and active and 2 backup links currently idle. The RTT on the backup links is currently unknown because they aren't active. When the main link goes down, which is early seen by the exceeded stability timeout, it activates the backup link. However RTT on that link proves to be quite large and the ACK intervals get stretched way beyond the current stability timeout, which triggers activation of the second backup link. That one might also have a higher RTT, in result of which this will also activate the 1st - best - link as the stability timeout couldn't yet converge towards worse conditions of the 2 other backup links (while activation of the 1st link wasn't expected because links are equivalent).

I think the only solution would be to forcefully activate always a link that was first connected, and keep it alive during the initial measurement period. SRT (since always) has a cache mechanism that remembers last characteristics of a link, so this forced activation wouldn't have to be done every time the link is reconnected, only when it is connected the very first time. This will be however necessary to have at least a rough measurement of the RTT for that link, especially if this should make the results worse than current links. The RTT measured in that link should comprise the minimum conditions on the whole group for STO, that is, even if this link isn't active and its RTT isn't being measured. Caching the RTT value should ensure that the forced activation of the link will happen only the very first time in a lifetime when the application uses this link.

If this is implemented, and it is ensured that every idle link always has its last remembered RTT recorded, and the highest RTT from all links is always dictating the minimum value for STO (stating it's still below the maximum required by latency), then getting switched to that link shall never consider activation of another link when a higher-RTT link takes over and it starts exceeding STO in the beginning. Also, the STO should be immediately modified upon reconnection of a link that would not take over the activation (that is, it would be idle in the beginning) so that the group is ready to make this link take over when the currently active link goes down, even if this means giving it more stability tolerance than it is required by the value of its RTT.

File: srtcore/core.h [hunk 2]
```diff
@@ -385,7 +388,8 @@ class CUDT
     int64_t maxBandwidth() const { return m_llMaxBW; }
     int MSS() const { return m_iMSS; }
 
-    uint32_t latency_us() const {return m_iTsbPdDelay_ms*1000; }
+    uint32_t peer_latency_us() const {return m_iPeerTsbPdDelay_ms * 1000; }
```
Comment (ethouris) [inline srtcore/core.h:391]: Why is `latency_us()` removed?

File: srtcore/core.h [hunk 3]
```diff
@@ -385,7 +388,8 @@ class CUDT
...
+    int peer_idle_tout_ms() const { return m_iOPT_PeerIdleTimeout; }
```
Comment (ethouris) [inline srtcore/core.h:392]: This, and `peer_latency_us`: naming convention dictates using `peerLatency_us` and `peerIdleTout_ms` (i'd also rather use `peerIdleTmout_ms`).

File: srtcore/group.cpp [hunk 4]
```diff
@@ -2969,6 +2969,112 @@ void CUDTGroup::sendBackup_CheckIdleTime(gli_t w_d)
...
+    const bool is_activation_phase = !is_zero(u.FreshActivationStart())
+        && (count_microseconds(currtime - u.FreshActivationStart()) <= activation_period_us);
+
+    const int peer_idle_tout_us = u.peer_idle_tout_ms() * 1000;
+
+    const int64_t stability_tout_us = is_activation_phase
+        ? initial_stabtout_us // activation phase
+        : min<int64_t>(max<int64_t>(min_stability_us, 2 * u.RTT() + 4 * u.RTTVar()), latency_us);
+    
+    const steady_clock::duration td_response = currtime - u.LastRspTime();
```
Comment (ethouris) [inline srtcore/group.cpp:3061]: What if `u.lastRspTime() == 0` ?

File: srtcore/core.h [hunk 5]
```diff
@@ -374,9 +374,12 @@ class CUDT
 
     bool isOPT_TsbPd() const { return m_bOPT_TsbPd; }
     int RTT() const { return m_iRTT; }
+    int RTTVar() const { return m_iRTTVar; }
     int32_t sndSeqNo() const { return m_iSndCurrSeqNo; }
     int32_t schedSeqNo() const { return m_iSndNextSeqNo; }
     bool overrideSndSeqNo(int32_t seq);
+    srt::sync::steady_clock::time_point LastRspTime() const { return m_tsLastRspTime; }
+    srt::sync::steady_clock::time_point FreshActivationStart() const { return m_tsFreshActivation; }
```
Comment (ethouris) [inline srtcore/core.h:382]: Naming convention mandates that these names start from a lowercase letter.

File: srtcore/group.cpp (hunk 4 above)
Comment (ethouris) [reply srtcore/group.cpp:3061]: Also, what if `u.LastRspTime() < u.FreshActivationStart()` ?

Comment (maxsharabayko) [reply srtcore/group.cpp:3061]: > What if `u.lastRspTime() == 0`?

It can't be zero. It is initialized with the current time when a socket is created or initially configured.

> what if `u.LastRspTime() < u.FreshActivationStart()`?

That's a good observation! Something like this should be done here then:

```c++
const steady_clock::time_point last_rsp = max(u.freshActivationStart(), u.lastRspTime());
const steady_clock::duration td_response = currtime - last_rsp;
```

File: srtcore/group.cpp [hunk 6]
```diff
@@ -2996,89 +3100,33 @@ bool CUDTGroup::sendBackup_CheckRunningStability(const gli_t d, const time_point
...
-                // The link seems to have missed two ACKs already.
-                // Qualify this link as unstable
-                // Notify that it has been seen so since now
-                u.m_tsUnstableSince = currtime;
-            }
-
-            is_stable = false;
-        }
-    }
+    const int is_stable = sendBackup_CheckRunningLinkStable(u, currtime, d->weight);
```
Comment (ethouris) [inline srtcore/group.cpp:3103]: How do you protect yourself against rapid changes in this value in case when, for example, RTT starts to increase dramatically?

File: srtcore/core.h (hunk 2 above)
Comment (maxsharabayko) [reply srtcore/core.h:391]: It is not used, and I am concerned about the naming. Likely it should be `tsbPdDelay_ms()`.

**Comment by maxsharabayko** [comment]
> If you limit RTT measurements only to active links, then it is likely the following situation: you have 3 equivalent links, one with lower RTT connected and active and 2 backup links currently idle. The RTT on the backup links is currently unknown because they aren't active. When the main link goes down, which is early seen by the exceeded stability timeout, it activates the backup link. However RTT on that link proves to be quite large and the ACK intervals get stretched way beyond the current stability timeout, which triggers activation of the second backup link. That one might also have a higher RTT, in result of which this will also activate the 1st - best - link as the stability timeout couldn't yet converge towards worse conditions of the 2 other backup links (while activation of the 1st link wasn't expected because links are equivalent).

The purpose of the activation phase that lasts for minimum 60 ms (see below), when we don't yet use the dynamic stability timout. It was observed that during this period RTT estimate more or less converges to a real value.
And here is where we have several improvements planned:
- improve RTT convergence;
- do not silence parallel links if the higher weight link is still in the "activation phase".

Both are subject to separate PRs to minimize the number of changes by each small step.

```
Initial Link Stability Timeout = max(Minimum Link Stability Timeout, SRT Latency),
where Minimum Link Stability Timeout = 60 ms
Activation Period = Initial Link Stability Timeout + 5 * SYN, where SYN=10
```

File: srtcore/group.cpp (hunk 6 above)
Comment (maxsharabayko) [reply srtcore/group.cpp:3102]: RTT changes are smoothed by the IIR filter (first on the receiver side, then again on the sender side). So there won't be that high fluctuation. And if some fluctuations fall outside the stability threshold, that is an indicator that something unstable is happening on the link.
