### PR TITLE
[FIX] Calculate correctly max payload size per UDP packet

### LINKED ISSUE #2663: [BUG] Payload size rules are tied to IPv4 only
The internal rules to calculate the maximum payload size for the SRT packet are largely based on the size of 28, which is 8 bytes for UDP header and 20 bytes for the IPv4 header (as mentioned in #2662). This calculation doesn't apply to IPv6, however.

Affected are:
* The `SRT_LIVE_MAX_PLSIZE` constant in `srt.h` header
* The `CUDT::m_iMaxSRTPayloadSize` field, which is used also to calculate the allocation size for the packet's payload

Potential problem: Sending a file over IPv6, which is the case when the maximum SRT payload size is used, may set an oversize to an MTU because it is assumed that the maximum UDP payload is 1492, while for IPv6 it's 1460 for the standard 1500 MTU. The live mode is unaffected only because it has the 1316 payload size, which fits in both IPv4 and IPv6 frames.

Potential solution: The `CUDT::open()` function is called everywhere in conditions where the expected (although not always already allocated) socket family is already known. This family identifier must be passed to it, and then down to `CUDT::clearData` so that the correct maximum payload size depending on the IP version is defined.

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #2663 

This fixes the problem of specifying the maximum payload size per packet. Some of the internal functions have also slightly changed their meaning and logics.

The problem: the system header (IP and UDP part) has a total length dependent on the IP version, and so it affects the remaining space in the 1500 MTU. For IPv4 it splits to 20[IPv4] + 8[UDP] + 16[SRT] + 1456. For IPv6, 32[IPv6] + 8[UDP] + 16[SRT] + 1444. Therefore the constants that were introduced for the maximum payload size have been deprecated and new ones were set up.

The real problem is actually that it depends on the effective IP version that is known only after the connection has been established - even if you declare the address in `srt_bind` or `srt_connect` to be IPv6, if the peer is IPv4, the in-transmission packet layout is like for IPv4. The actual rules of which layout to use are:

* For IPv4 socket, use always IPv4 layout
* For IPv6 socket, depending on the peer's address:
   * if the peer address is IPv6-mapped-IPv4 address, use the layout for IPv4
   * otherwise use the layout for IPv6

In other words, it's not enough to state that the current socket is IPv6, but you need to wait for a connection because if the connection is made to an IPv4 address, the transmission will use IPv4, and the IPv6 socket is just the matter of the agent's system API (it uses dual-stack sockets in reality). As confirmed in experiments, there isn't any limitation in the API how big packet you may send (except that for 65535 bytes) - if it exceeds the payload size for the UDP with particular IP version, worst case the packet will be fragmented and reassembled on the peer side transparently. The problem is then only in the following range:

* In live mode, if we send a packet, we should consider having sent exactly one packet, without initial fragmentation

* In file mode, if we split a bigger buffer into smaller units that will be sent in single UDP packets, it would be counter-productive if a packet happens to have 1456 payload added with 40 bytes header and get effectively split into one unit of 40+16+1444 bytes and one of 40+16+12 bytes.

Fixes embrace also all internal calculations:

1. The `SRTO_PAYLOADSIZE` option: this is used only in live mode and defines the maximum size of a buffer specified for sending in one `srt_send` call, as well as defines the maximum size used for data in the buffers, and calculations of data stats. This option has also changed meaning on reading: for a connected socket it has a fixed value and returns the current maximum payload per packet in all modes. In file mode, where this option defaults to 0, after connecting (when this option can't be any longer altered) it returns the value of the maximum payload size per packet that will be used - that is, in live mode it will return the earlier set value (as long as it was accepted), while in file mode it will return 1456 or 1444 (with no AEAD, no FEC and default value of MSS), depending on which IP protocol is in use. This value is also additionally controlled with regard to this, however it can't really control this option when the underlying protocol is unknown, so setting a too big value for this option with regard to IPv6 may result in error only during the call to `srt_bind` or `srt_connect`.
2. Allocation in the receiver queue and both buffers: The sender buffer is created only at the connection time, so it is known only then what maximum payload size should be used and what the header size is (required for rate estimator). However the receiver queue (unit queue) that is used by the receiver buffer must allocate the maximum payload size because the actual interchange IP protocol isn't known at the moment if creation. Therefore the receiver buffer's unit queue is allocated with every unit having the payload size equal to 1456.

### CODE REVIEW

File: srtcore/api.cpp [hunk 1]
```diff
@@ -3157,7 +3157,14 @@ void srt::CUDTUnited::updateMux(CUDTSocket* s, const sockaddr_any& reqaddr, cons
         m.m_pSndQueue = new CSndQueue;
         m.m_pSndQueue->init(m.m_pChannel, m.m_pTimer);
         m.m_pRcvQueue = new CRcvQueue;
-        m.m_pRcvQueue->init(128, s->core().maxPayloadSize(), m.m_iIPversion, 1024, m.m_pChannel, m.m_pTimer);
+
+        // We can't use maxPayloadSize() because this value isn't valid until the connection is established.
+        // We need to "think big", that is, allocate a size that would fit both IPv4 and IPv6.
+        size_t payload_size = s->core().m_config.iMSS - CPacket::HDR_SIZE - CPacket::udpHeaderSize(AF_INET);
```
Comment (ethouris) [inline srtcore/api.cpp:3163]: There's a controversy whether this size should be used, or rather the payload size set by an option, if it's less, to allocate less memory. I think this shouldn't be done because if you happen to receive an SRT packet that would be oversized in these conditions, it will end up in a call that results in getting MSG_TRUNC flag due to too small buffer for the packet, which may lead to hard to detect errors.

File: srtcore/core.cpp [hunk 2]
```diff
@@ -5572,8 +5596,30 @@ bool srt::CUDT::prepareConnectionObjects(const CHandShake &hs, HandshakeSide hsd
...
+
         const int authtag = m_config.iCryptoMode == CSrtConfig::CIPHER_MODE_AES_GCM ? HAICRYPT_AUTHTAG_MAX : 0;
-        m_pSndBuffer = new CSndBuffer(32, m_iMaxSRTPayloadSize, authtag);
+
+        SRT_ASSERT(m_iMaxSRTPayloadSize != 0);
+        SRT_ASSERT(m_TransferIPVersion != AF_UNSPEC);
+        // IMPORTANT:
+        // The m_iMaxSRTPayloadSize is the size of the payload in the "SRT packet" that can be sent
+        // over the current connection - which means that if any party is IPv6, then the maximum size
+        // is the one for IPv6 (1444). Only if both parties are IPv4, this maximum size is 1456.
```
Comment (ethouris) [inline srtcore/core.cpp:5610]: This comment is likely wrong. 1444 is only when both parties are confirmed as IPv6.

**Comment by ethouris** [comment]
WARNING: Bugs found after update, wait for the fix.

**Comment by ethouris** [comment]
Ok, the problem has been fixed. Again, in short, what this fix is really for:

1. File transmission mode in IPv6. By using the payload size as per IPv4 in IPv6 transmission, it was effectively 1512 bytes of MSS, which still was taken care of by the device by doing packet fragmentation, which resulted in using more link capacity without advantage.
2. When you use live mode and set a bigger size for `SRTO_PAYLOADSIZE` than possible due to limitations imposed by extra settings (FEC or AEAD) and with IPv6, but fitting to IPv4, it might also result in using bigger unit than set for MSS, and also lead to system-wide packet fragmentation.

**Review by maxsharabayko — COMMENTED** [review]
### Reviewing Notes

#### API Changes

New items added:
- `SRT_MAX_PLSIZE_AF_INET`
- `SRT_MAX_PLSIZE_AF_INET6`
- `SRT_MAX_PLDSIZE`

File: srtcore/common.h [hunk 3]
```diff
@@ -1422,6 +1422,15 @@ inline std::string SrtVersionString(int version)
...
 
+bool checkMappedIPv4(const uint16_t* sa);
+
+inline bool checkMappedIPv4(const sockaddr_in6& sa)
+{
+    const uint16_t* addr = reinterpret_cast<const uint16_t*>(&sa.sin6_addr.s6_addr);
+    return checkMappedIPv4(addr);
+}
+
+
```
Comment (maxsharabayko) [inline srtcore/common.h:1433]: Move to a "refactoring" PR N1.

File: srtcore/common.cpp [hunk 4]
```diff
@@ -205,7 +205,7 @@ void srt::CIPAddress::pton(sockaddr_any& w_addr, const uint32_t ip[4], const soc
     {
         // Check if the peer address is a model of IPv4-mapped-on-IPv6.
         // If so, it means that the `ip` array should be interpreted as IPv4.
-        const bool is_mapped_ipv4 = checkMappedIPv4((uint16_t*)peer.sin6.sin6_addr.s6_addr);
+        const bool is_mapped_ipv4 = checkMappedIPv4(peer.sin6);
```
Comment (maxsharabayko) [inline srtcore/common.cpp:208]: Move to a "refactoring" PR N1.

File: srtcore/channel.cpp [hunk 5]
```diff
@@ -1016,6 +1016,15 @@ srt::EReadStatus srt::CChannel::recvfrom(sockaddr_any& w_addr, CPacket& w_packet
...
 
+        if (msg_flags & MSG_TRUNC)
+        {
+            // Additionally show buffer information in this case
+            flg << " buffers: ";
+            for (size_t i = 0; i < CPacket::PV_SIZE; ++i)
+            {
+                flg << "[" << w_packet.m_PacketVector[i].iov_len << "] ";
+            }
+        }
```
Comment (maxsharabayko) [inline srtcore/channel.cpp:1027]: Move to a "refactoring" PR N1.

File: srtcore/buffer_tools.h [hunk 6]
```diff
@@ -94,7 +94,7 @@ class CRateEstimator
     typedef sync::steady_clock::time_point time_point;
     typedef sync::steady_clock::duration   duration;
 public:
-    CRateEstimator();
+    CRateEstimator(int family);
```
Comment (maxsharabayko) [inline srtcore/buffer_tools.h:97]: Move to a "refactoring" PR N1.
Default to AF_INET to not touch the calls.

File: srtcore/buffer_tools.cpp [hunk 7]
```diff
@@ -102,11 +102,12 @@ void AvgBufSize::update(const steady_clock::time_point& now, int pkts, int bytes
     m_dTimespanMAvg   = avg_iir_w<1000, double>(m_dTimespanMAvg, timespan_ms, elapsed_ms);
 }
 
-CRateEstimator::CRateEstimator()
+CRateEstimator::CRateEstimator(int family)
     : m_iInRatePktsCount(0)
     , m_iInRateBytesCount(0)
     , m_InRatePeriod(INPUTRATE_FAST_START_US) // 0.5 sec (fast start)
     , m_iInRateBps(INPUTRATE_INITIAL_BYTESPS)
+    , m_iFullHeaderSize(CPacket::udpHeaderSize(family) + CPacket::HDR_SIZE)
```
Comment (maxsharabayko) [inline srtcore/buffer_tools.cpp:110]: Move to a "refactoring" PR N1.

File: srtcore/buffer_snd.h [hunk 8]
```diff
@@ -87,7 +87,7 @@ class CSndBuffer
     /// @param size initial number of blocks (each block to store one packet payload).
     /// @param maxpld maximum packet payload (including auth tag).
     /// @param authtag auth tag length in bytes (16 for GCM, 0 otherwise).
-    CSndBuffer(int size = 32, int maxpld = 1500, int authtag = 0);
+    CSndBuffer(int ip_family, int size, int maxpld, int authtag);
```
Comment (maxsharabayko) [inline srtcore/buffer_snd.h:90]: Move to a "refactoring" PR N1.

File: srtcore/buffer_snd.cpp [hunk 9]
```diff
@@ -77,6 +77,7 @@ CSndBuffer::CSndBuffer(int size, int maxpld, int authtag)
     , m_iAuthTagSize(authtag)
     , m_iCount(0)
     , m_iBytesCount(0)
+    , m_rateEstimator(ip_family)
```
Comment (maxsharabayko) [inline srtcore/buffer_snd.cpp:80]: Move to a "refactoring" PR N1.

File: docs/API/API-socket-options.md [hunk 10]
```diff
@@ -922,20 +922,88 @@ The default value is 0x010000 (SRT v1.0.0).
...
+what the payload size limit until the connection is established. Parts of the
+SRT facilities that must allocate any resources according to this value prior
+to connecting are using the layout as per IPv4 because this way they allocate
+more space than needed in the worst case.
+
+This value can be set on both connection parties independently, but after
+connection this option gets an effectively negotiated value, which is the less
+one from both parties. If this effective value is too small on any of the
+connection peers, the connection is rejected (or late-rejected on the caller
+side).
```
Comment (stevomatthews) [inline docs/API/API-socket-options.md:961]:
```suggestion
This value can be set on both connection parties independently, but after
connection `SRTO_MSS` gets a negotiated value, which is the lesser
of the two. If this effective value is too small for either of the
connection peers, the connection is rejected (or late-rejected on the caller
side).
```

File: docs/API/API-socket-options.md [hunk 11]
```diff
@@ -922,20 +922,88 @@ The default value is 0x010000 (SRT v1.0.0).
...
+
+* The size of the memory space allocated for a single packet in the sender
+and receiver buffers. This value is equal to "SRT header" + "remaining space"
+in the IPv4 layout case (1472 bytes per packet for MSS=1500). The reason for it
+is that some buffer resources are allocated prior to the connection, so this
+value must fit both IPv4 and IPv6 for buffer memory allocation.
+
+The default value 1500 matches the standard MTU size for network devices. It
+is recommended that this value be set at maximum to the value of MTU size of
+the network device that you will use for connection.
```
Comment (stevomatthews) [inline docs/API/API-socket-options.md:975]:
```suggestion
The default value of 1500 corresponds to the standard MTU size for network devices. It
is recommended that this value be set to the maximum MTU size of
the network device that you will use for the connection.
```

File: docs/API/API-socket-options.md [hunk 12]
```diff
@@ -922,20 +922,88 @@ The default value is 0x010000 (SRT v1.0.0).
...
+
+Detailed recommendations for this value differ in the file and live mode.
```
Comment (stevomatthews) [inline docs/API/API-socket-options.md:977]:
```suggestion
The recommendations for the value of `SRTO_MSS` differ between file and live modes.
```

File: docs/API/API-socket-options.md [hunk 13]
```diff
@@ -922,20 +922,88 @@ The default value is 0x010000 (SRT v1.0.0).
...
+packet. To save memory space, you may want then to set MSS in live mode to
+a value for which the "remaining space" matches `SRTO_PAYLOADSIZE` value (for
+default 1316 it will be 1360 for IPv4 and 1372 for IPv6). This is not done by
+default for security reasons: this may potentially lead to inability to read an
+incoming UDP packet if its size is by some reason bigger than the negotiated MSS.
+This may lead to misleading situations and hard to detect errors. You should
+set such a value only if the peer is trusted (that is, you can be certain that
+it will never come to a situation of having received an oversized UDP packet
+over the link used for the connection). See also limitations for
+`SRTO_PAYLOADSIZE`.
```
Comment (stevomatthews) [inline docs/API/API-socket-options.md:991]:
```suggestion
In live mode a single call to the `srt_send*` function may only send data
that fits in one packet. This size is defined by the `SRTO_PAYLOADSIZE`
option (defult: 1316), and it is also the size of the data in a single UDP
packet. To save memory space, you may want then to set `SRTO_MSS` in live mode to
a value for which the "remaining space" matches the `SRTO_PAYLOADSIZE` value (for
the default value of 1316 this will be 1360 for IPv4 and 1372 for IPv6). For security reasons, 
this is not done by default: it may potentially lead to the inability to read an incoming UDP 
packet if its size is for some reason bigger than the negotiated MSS, which may in turn lead 
to unpredictable behaviour and hard-to-detect errors. You should set such a value only if 
the peer is trusted (that is, you can be certain that you will never receive an oversized UDP 
packet over the link used for the connection). You should also consider the limitations of
`SRTO_PAYLOADSIZE`.
```

File: docs/API/API-socket-options.md [hunk 14]
```diff
@@ -922,20 +922,88 @@ The default value is 0x010000 (SRT v1.0.0).
...
+
+In the file mode `SRTO_PAYLOADSIZE` has a special value 0 that means no limit
+for one single packet sending, and therefore bigger portions of data are
+internally split into smaller portions, each one using the maximum available
+"remaining space". The best value of `SRTO_MSS` for this case is then equal to
+the current network device's MTU size. Setting a greater value is possible
+(maximum for the system API is 65535), but it may lead to packet fragmentation
+on the system level. This is highly unwanted in SRT because:
```
Comment (stevomatthews) [inline docs/API/API-socket-options.md:999]:
```suggestion
In file mode `SRTO_PAYLOADSIZE` has a special value 0 that means there is no limit
for sending a single packet, and therefore bigger portions of data are
internally split into smaller portions, each one using the maximum available
"remaining space". The best value of `SRTO_MSS` for this case is then equal to
the current network device's MTU size. Setting a greater value is possible
(maximum for the system API is 65535), but it may lead to packet fragmentation
on the system level. This is highly unwanted in SRT because:
```

File: docs/API/API-socket-options.md [hunk 15]
```diff
@@ -922,20 +922,88 @@ The default value is 0x010000 (SRT v1.0.0).
...
+
+* Here SRT does also its own fragmentation, so it would be counter-productive
+* It would use more system resources with no advantage
+* SRT is unaware of it, so the statistics will be slightly falsified
```
Comment (stevomatthews) [inline docs/API/API-socket-options.md:1003]:
```suggestion
* SRT also performs its own fragmentation, so it would be counter-productive
* It would use more system resources to no advantage
* SRT is unaware of it, so the resulting statistics would be slightly misleading
```

File: docs/API/API-socket-options.md [hunk 16]
```diff
@@ -922,20 +922,88 @@ The default value is 0x010000 (SRT v1.0.0).
...
+
+The system-level packet fragmentation cannot be however reliably turned off;
+the best approach is then to avoid it by using appropriate parameters.
```
Comment (stevomatthews) [inline docs/API/API-socket-options.md:1006]:
```suggestion
System-level packet fragmentation cannot be reliably turned off,
so safest approach is to avoid it by using appropriate parameters.
```

File: docs/API/API-socket-options.md [hunk 17]
```diff
@@ -1089,12 +1157,51 @@ encrypted connection, they have to simply set the same passphrase.
...
+
+* 4 bytes reserved for FEC, if you use the builtin FEC packet filter (see `SRTO_PACKETFILTER`)
+* 16 bytes reserved for the authentication tag, if you use AES GCM (see `SRTO_CRYPTOMODE`)
+
+**WARNING**: The option setter will reject the setting if this value is too
+great, but note that not every limitation can be checked prior to connection.
+This includes:
+
+* MSS defined by the peer, which may override MSS set in the agent
+* The in-transmission IP version - see `SRTO_MSS` for details
```
Comment (stevomatthews) [inline docs/API/API-socket-options.md:1198]:
```suggestion
Sets the mode that determines the limitations on how data is sent, including the maximum 
size of payload data sent within a single UDP packet.

The default values are 0 (corresponding to file mode) and 1316 (in live mode, which is one 
of the options modified together with `SRTO_TRANSTYPE`).

In file mode (`SRTO_PAYLOAD` = 0) the call to `srt_send*`
is not limited to the size of a single packet. If necessary, the supplied
data will be split into multiple pieces, each fitting into a single UDP packet. Every data payload  
(except the last one in the stream or in the message) will use the maximum space available in 
a UDP packet, as determined by `SRTO_MSS` and other settings that may influence this size 
(such as [`SRTO_PACKETFILTER`](#SRTO_PACKETFILTER) and 
[`SRTO_CRYPTOMODE`](#SRTO_CRYPTOMODE)`SRTO_CRYPTOMODE`).

In live mode  (`SRTO_PAYLOAD` > 0) the value defines the maximum size of:

* a single call to a sending function (`srt_send*`)
* the payload supplied in each data packet

This value can be set to a greater value than the default 1316, but the maximum
possible value is limited by the following factors:

* 1500 bytes is the default MSS (see  [SRTO_MSS](#SRTO_MSS)), including headers, which occupy:
   * 20 bytes for IPv4, or 32 bytes for IPv6
   * 8 bytes for UDP
   * 16 bytes for SRT

This alone gives a limit of 1456 for IPv4 and 1444 for IPv6. This limit may
be further decreased in the following cases:

* 4 bytes reserved for FEC, if you use the built in FEC packet filter (see [`SRTO_PACKETFILTER`](#SRTO_PACKETFILTER))
* 16 bytes reserved for the authentication tag, if you use AES GCM (see [`SRTO_CRYPTOMODE`](#SRTO_CRYPTOMODE))

**WARNING**: The party setting the options will reject a value that is too
large, but note that not every limitation can be checked prior to connection.
This includes:

* the MSS value defined by a peer, which may override the MSS set by an agent
* the in-transmission IP version (see [SRTO_MSS](#SRTO_MSS) for details)
```

File: docs/API/API-socket-options.md (hunk 14 above)
Comment (ethouris) [reply docs/API/API-socket-options.md:999]:
```suggestion
In the file mode `SRTO_PAYLOADSIZE` has a special value 0 that means there is
no size limit for a single `srt_send*` call, and bigger portions of data are
internally split into smaller portions, each one using the maximum available
"remaining space" of a packet. The best value of `SRTO_MSS` for this case is then equal to
the current network device's MTU size. Setting a greater value is possible
(maximum for the system API is 65535), but it may lead to packet fragmentation
on the system level. This is highly unwanted in SRT because:
```

File: docs/API/API-socket-options.md (hunk 17 above)
Comment (ethouris) [reply docs/API/API-socket-options.md:1196]:
```suggestion
Sets the mode that determines the limitations on how data is sent, including the maximum 
size of payload data sent within a single UDP packet.

The default value is 1316 in live mode (which is default) and 0 in file mode (when file
mode is set through the `SRTO_TRANSTYPE` option).

In file mode (`SRTO_PAYLOADSIZE` = 0) the call to `srt_send*` is not limited to the size
of a single packet. If necessary, the supplied data will be split into multiple pieces,
each fitting into a single UDP packet. Every data payload (except the last one in the
stream or in the message) will use the maximum space available in a UDP packet,
as determined by `SRTO_MSS` and other settings that may influence this size 
(such as [`SRTO_PACKETFILTER`](#SRTO_PACKETFILTER) and 
[`SRTO_CRYPTOMODE`](#SRTO_CRYPTOMODE)).

In live mode (`SRTO_PAYLOADSIZE` > 0) the value defines the maximum size of:

* a single call to a sending function (`srt_send*`)
* the payload supplied in each data packet

as well as the minimum size of the buffer used for the `srt_recv*` call.

This value can be set to a greater value than the default 1316, but the maximum
possible value is limited by the following factors:

* 1500 bytes is the default MSS (see [`SRTO_MSS`](#SRTO_MSS)), including headers, which occupy:
   * 20 bytes for IPv4, or 32 bytes for IPv6
   * 8 bytes for UDP
   * 16 bytes for SRT

This alone gives a limit of 1456 for IPv4 and 1444 for IPv6. This limit may
be further decreased in the following cases:

* 4 bytes reserved for FEC, if you use the built in FEC packet filter (see [`SRTO_PACKETFILTER`](#SRTO_PACKETFILTER))
* 16 bytes reserved for the authentication tag, if you use AES GCM (see [`SRTO_CRYPTOMODE`](#SRTO_CRYPTOMODE))

**WARNING**: The party setting the options will reject a value that is too
large, but note that not every limitation can be checked prior to connection.
This includes:

* the MSS value defined by a peer, which may override the MSS set by an agent
* the in-transmission IP version (see [SRTO_MSS](#SRTO_MSS) for details)
```

File: docs/API/API-socket-options.md (hunk 14 above)
Comment (stevomatthews) [reply docs/API/API-socket-options.md:997]: ^^ all good.

File: docs/API/API-socket-options.md (hunk 17 above)
Comment (stevomatthews) [reply docs/API/API-socket-options.md:1196]: ^^ all good.

File: docs/API/API-socket-options.md [hunk 18]
```diff
@@ -922,20 +922,86 @@ The default value is 0x010000 (SRT v1.0.0).
...
-payload or SRT payload - this size is the size of the IP packet, including the
-UDP and SRT headers*
-
-THe value of `SRTO_MSS` must not exceed `SRTO_UDP_SNDBUF` or `SRTO_UDP_RCVBUF`.
+| `SRTO_MSS`           |       | pre-bind | `int32_t`  | bytes   | 1500     | 116..  | RW  | GSD    |
+
+Maximum Segment Size. This value represents the maximum size of a UDP packet
+sent by the system. Therefore the value of `SRTO_MSS` must not exceed the
+values of `SRTO_UDP_SNDBUF` or `SRTO_UDP_RCVBUF`. It is used for buffer
+allocation and rate calculation using packet counter assuming fully filled
```
Comment (stevomatthews) [inline docs/API/API-socket-options.md:930]:
```suggestion
allocation and rate calculation using a packet counter that assumes fully filled
```

File: docs/API/API-socket-options.md [hunk 19]
```diff
@@ -922,20 +922,86 @@ The default value is 0x010000 (SRT v1.0.0).
...
+packets. 
+
+This value is a sum of:
+
+* IP header (20 bytes for IPv4 or 32 bytes for IPv6)
+* UDP header (8 bytes)
+* SRT header (16 bytes)
+* remaining space (as the maximum payload size available for a packet)
+
+For the default 1500 the "remaining space" part is effectively 1456 for IPv4
```
Comment (stevomatthews) [inline docs/API/API-socket-options.md:940]:
```suggestion
For the default 1500 the "remaining space" is effectively 1456 for IPv4
```

File: docs/API/API-socket-options.md [hunk 20]
```diff
@@ -922,20 +922,86 @@ The default value is 0x010000 (SRT v1.0.0).
...
+following cases:
+
+* when the current socket's binding address is of IPv4 domain
+* when the peer's address is an IPv6-mapped-IPv4 address
+
+The IPv6 transmission case is assumed only if the peer's address is a true IPv6 address 
+(not IPv4 mapped). It is then not possible to determine the payload size limit 
+until the connection is established. SRT operations that must allocate any 
+resources according to this value prior to connecting will assume IPv4 transmission 
+because this way, in the worst case, they allocate more space than needed .
```
Comment (stevomatthews) [inline docs/API/API-socket-options.md:954]:
```suggestion
because this way, in the worst case, they allocate more space than needed.
```

File: docs/API/API-socket-options.md [hunk 21]
```diff
@@ -922,20 +922,86 @@ The default value is 0x010000 (SRT v1.0.0).
...
+the default value of 1316 this will be 1360 for IPv4 and 1372 for IPv6). For security reasons, 
+this is not done by default: it may potentially lead to the inability to read an incoming UDP 
+packet if its size is for some reason bigger than the negotiated MSS, which may in turn lead 
+to unpredictable behaviour and hard-to-detect errors. You should set such a value only if 
+the peer is trusted (that is, you can be certain that you will never receive an oversized UDP 
+packet over the link used for the connection). You should also consider the limitations of
+`SRTO_PAYLOADSIZE`.
+
+In the file mode `SRTO_PAYLOADSIZE` has a special value 0 that means no limit
+for one single packet sending, and therefore bigger portions of data are
```
Comment (stevomatthews) [inline docs/API/API-socket-options.md:992]:
```suggestion
In file mode `SRTO_PAYLOADSIZE` has a special value 0 that means no limit
for sending a single packet, and therefore bigger portions of data are
```

File: docs/API/API-socket-options.md [hunk 22]
```diff
@@ -922,20 +922,86 @@ The default value is 0x010000 (SRT v1.0.0).
...
+the current network device's MTU size. Setting a greater value is possible
+(maximum for the system API is 65535), but it may lead to packet fragmentation
+on the system level. This is highly unwanted in SRT because:
+
+* SRT also performs its own fragmentation, so it would be counter-productive
+* It would use more system resources to no advantage
+* SRT is unaware of it, so the resulting statistics would be slightly misleading
+
+System-level packet fragmentation cannot be reliably turned off,
+so safest approach is to avoid it by using appropriate parameters.
```
Comment (stevomatthews) [inline docs/API/API-socket-options.md:1004]:
```suggestion
so the safest approach is to avoid it by using appropriate parameters.
```

**Review by stevomatthews — COMMENTED** [review]
Very minor edits.

File: srtcore/core.h [hunk 23]
```diff
@@ -1204,6 +1204,7 @@ class CUDT
     sockaddr_any m_PeerAddr;   // peer address
     sockaddr_any m_SourceAddr; // override UDP source address with this one when sending
     uint32_t m_piSelfIP[4];    // local UDP IP address
+    int m_TransferIPVersion;   // AF_INET/6 that should be used to determine common payload size
```
Comment (maxsharabayko) [inline srtcore/core.h:1207]:
```suggestion
    int m_iTransferIPVersion;   // AF_INET/6 that should be used to determine the common payload size
```

File: srtcore/srt.h [hunk 24]
```diff
@@ -300,9 +300,20 @@ typedef enum SRT_TRANSTYPE
...
+// in a single UDP packet, depending on the IP version, and
+// with the default socket options, that is:
+// * default 1500 bytes of MTU (see SRTO_MSS)
+// * without FEC packet filter (see SRTO_PACKETFILTER)
+// * without AEAD through AES-GCM (see SRTO_CRYPTOMODE)
+static const int SRT_MAX_PLSIZE_AF_INET = 1456; // MTU(1500) - IPv4.hdr(20) - UDP.hdr(8) - SRT.hdr(16)
+static const int SRT_MAX_PLSIZE_AF_INET6 = 1444; // MTU(1500) - IPv6.hdr(32) - UDP.hdr(8) - SRT.hdr(16)
+
+// A macro for these above in case when the IP family is passed as a runtime value.
+#define SRT_MAX_PLSIZE(famspec) ((famspec) == AF_INET ? SRT_MAX_PLSIZE_AF_INET : SRT_MAX_PLSIZE_AF_INET6)
```
Comment (maxsharabayko) [inline srtcore/srt.h:316]: I am hesitant in having these in the API, because the maximum payload size also depends on the MTU size.

File: srtcore/srt.h [hunk 25]
```diff
@@ -562,6 +573,7 @@ enum SRT_REJECT_REASON
 #ifdef ENABLE_AEAD_API_PREVIEW
     SRT_REJ_CRYPTO,      // conflicting cryptographic configurations
 #endif
+    SRT_REJ_SETTINGS,    // socket settings on both sides collide and can't be negotiated
```
Comment (maxsharabayko) [inline srtcore/srt.h:576]: We already use the "config" naming throughout the project, e.g. socket config. Another naming is "options", e.g. socket option. I suggest using one of those to avoid introducing yet another term.

File: srtcore/core.h (hunk 23 above)
Comment (ethouris) [reply srtcore/core.h:1207]: Actually not. The `i` marker defines an integer - counting - variable, while here it is used as a value that should be assigned to AF_INET or AF_INET6 symbol. If this was a decent C++ API, it would be an enum.

File: srtcore/srt.h (hunk 24 above)
Comment (ethouris) [reply srtcore/srt.h:316]: I was simply trying to do some replacement for the existing the "MAX PLSIZE" constant. Not sure if anyone is using it or whether it is anyhow useful. Note that the live payload size (1316) is still lower than these two, also including FEC and AEAD. So the only use case for these constants is for a case when you have a live stream, but you want to have a bigger payload than 1316. It is also clearly written here, under which circumstances these values hold.

We can remove this, but note that the true maximum payload size can only be determined after connection. As an alternative, we can have some tools to determine the payload size with foreseen IP version, AEAD and FEC.

File: srtcore/srt.h (hunk 25 above)
Comment (ethouris) [reply srtcore/srt.h:576]: Ok, I think you're right. And I've seen one more trick - the numbers should be explicitly assigned, if there is a conditional in the API, in order to avoid ABI compat tricks.
