### PR TITLE
Fixes for CUDTException class. Derived from exception, moved out of the API.

### LINKED ISSUE #861: The `CUDTException` class should derive from `std::exception`
As this is a class predicted for exceptions, it would be more standard friendly if it derives from `std::exception` or its most appropriate specialized derivative (possibly `std::runtime_error`). Also its `what()` method should refer to something that can represent an error message (possibly redirect to `getErrorMessage()`.

### PR DESCRIPTION
**Pull request by ethouris**
Unfortunately `CUDTException` class is very hard to tear off the current code, so the following was done:

1. The CUDTException class was moved to `common.h`, which means that it is internal now.
2. The `UDT::getlasterror()` legacy API function is actually useless. It still returns the same reference to CUDTException, but this time you need additionally `common.h` to be included in order to access the returned object. Note that UDT legacy API is currently treated as deprecated - instead of this function you should use `srt_getlasterror()` and `srt_getlasterror_msg()`.
3. The `m_strMsg` field is turned `mutable` as it functions only as a cache for message string. Note that the major/minor fields are not intended to be altered during this object's runtime.

Fixes #861

### CODE REVIEW

File: testing/testmedia.cpp [hunk 1]
```diff
@@ -673,31 +673,31 @@ void SrtCommon::ConnectClient(string host, int port)
...
-void SrtCommon::Error(UDT::ERRORINFO& udtError, string src, SRT_REJECT_REASON reason)
+void SrtCommon::Error(string src, SRT_REJECT_REASON reason)
 {
-    int udtResult = udtError.getErrorCode();
-    string message = udtError.getErrorMessage();
-    if (udtResult == SRT_ECONNREJ)
+    int errnov = 0;
+    int result = srt_getlasterror(&errnov);
+    string message = srt_getlasterror_str();
+    if (result == SRT_ECONNREJ)
```
Comment (maxsharabayko) [inline testing/testmedia.cpp]: const int result

File: srtcore/common.h [hunk 2]
```diff
@@ -75,6 +75,98 @@ modified by
...
+
+   int getErrorCode() const;
+
+      /// Get the system network errno for the exception.
+      /// @return errno.
+
+   int getErrno() const;
+      /// Clear the error code.
+
+   void clear();
```
Comment (maxsharabayko) [inline srtcore/common.h]: Please format comments placement. It should be right above the function declaration.

File: srtcore/common.h [hunk 3]
```diff
@@ -75,6 +75,98 @@ modified by
...
+
+private:
+   CodeMajor m_iMajor;        // major exception categories
+   CodeMinor m_iMinor;		// for specific error reasons
+   int m_iErrno;		// errno returned by the system if there is any
+   mutable std::string m_strMsg; // text error message (cache)
```
Comment (maxsharabayko) [inline srtcore/common.h]: `m_iError` can be const.

Comment (ethouris) [reply srtcore/common.h]: Unfortunately, not. See `CUDTException::clear()` in `common.cpp`.

File: testing/testmedia.cpp [hunk 4]
```diff
@@ -673,31 +673,31 @@ void SrtCommon::ConnectClient(string host, int port)
...
     }
     if ( Verbose::on )
-        Verb() << "FAILURE\n" << src << ": [" << udtResult << "] " << message;
+        Verb() << "FAILURE\n" << src << ": [" << result << "." << errnov << "] " << message;
     else
-        cerr << "\nERROR #" << udtResult << ": " << message << endl;
+        cerr << "\nERROR #" << result << "." << errnov << ": " << message << endl;
 
-    udtError.clear();
     throw TransmissionError("error: " + src + ": " + message);
```
Comment (maxsharabayko) [inline testing/testmedia.cpp]: `CUDTException.clear();` deleted. OK

File: apps/transmitmedia.cpp [hunk 5]
```diff
@@ -582,36 +582,36 @@ void SrtCommon::ConnectClient(string host, int port)
...
-    int udtResult = udtError.getErrorCode();
-    string message = udtError.getErrorMessage();
-    Verb() << "\nERROR #" << udtResult << ": " << message;
+    int errnov = 0;
+    int result = srt_getlasterror(&errnov);
+    string message = srt_getlasterror_str();
+    Verb() << "\nERROR #" << result << "." << errnov << ": " << message;
 
-    udtError.clear();
     throw TransmissionError("error: " + src + ": " + message);
```
Comment (maxsharabayko) [inline apps/transmitmedia.cpp]: `clear()` usage deleted - OK

File: srtcore/common.h (hunk 3 above)
Comment (maxsharabayko) [reply srtcore/common.h]: Look like clear() is only used in apps. And you are deleting that usage by this PR. See the following comments.

File: apps/transmitmedia.cpp (hunk 5 above)
Comment (ethouris) [reply apps/transmitmedia.cpp]: Not completely. See `srt_clearlasterror()`. Not sure if this is something extremely required, but changes in the API require deprecation period.

Comment (maxsharabayko) [reply apps/transmitmedia.cpp]: Might be more correct to delete m_TLSError, instead of reseting it via `CUDTUnited::getError().clear()` in `srt_clearlasterror()`.
But better to resolve this separately.

```
CUDTException* CUDTUnited::getError()
{
    if(!pthread_getspecific(m_TLSError))
        pthread_setspecific(m_TLSError, new CUDTException);
    return (CUDTException*)pthread_getspecific(m_TLSError);
}
```

File: srtcore/common.h (hunk 3 above)
Comment (maxsharabayko) [reply srtcore/common.h]: Created #1032
