### PR TITLE
[core] Fix : Sequence number in the ACK packet isn’t correct (#2873)

### LINKED ISSUE #2873: [BUG] Sequence number in the ACK packet isn’t correct
**Describe the bug**
I’m currently using SRT 1.5.2 to distribute MPEG TS streams. Recently, I stumbled upon a rare issue where the sequence number (SN) in the ACK packet isn’t correct. This messes up retransmissions and causes data packets to get dropped.

Here’s a snapshot from tcpdump to illustrate:
tcpdump
`
[Black] NAK packet of lost SN:1102276611
`
`
[Yellow] ACK packet of larger SN:1102276613
`

Ideally, **the ACK packet should have an SN of 1102276611** . This causes retransmissions from the sender to be canceled, resulting in a drop.
Turns out, in such cases, the first SN stored in `srt::CUDT::m_pRcvLossList` is used for the ACK packet, according to srtcore/core.cpp:
```
int srt::CUDT::sendCtrlAck(CPacket& ctrlpkt, int size)
{

     ...omitted...

     {
         // If there is no loss, the ACK is the current largest sequence number plus 1;
         // Otherwise it is the smallest sequence number in the receiver loss list.
         ScopedLock lock(m_RcvLossLock);
         // TODO: Consider the Fresh Loss list as well!!!
        ack = m_pRcvLossList->getFirstLostSeq();
     }

    // We don't need to check the length prematurely,
    // if length is 0, this will return SRT_SEQNO_NONE.
    // If so happened, simply use the latest received pkt + 1.
    if (ack == SRT_SEQNO_NONE)
    {
        ack = CSeqNo::incseq(m_iRcvCurrSeqNo);
        IF_HEAVY_LOGGING(reason = "expected next");
    }
```
As a result of investigation, I realized that `m_pRcvLossList` was not updated and the list remained empty because the following condition of `CSeqNo::seqcmp(seqno1, m_iLargestSeq) <= 0` was met, as mentioned in srtcore/list.cpp:
```
void srt::CRcvLossList::insert(int32_t seqno1, int32_t seqno2)
{
     // Data to be inserted must be larger than all those in the list
     if (m_iLargestSeq != SRT_SEQNO_NONE && CSeqNo::seqcmp(seqno1, m_iLargestSeq) <= 0)
     {
         if (CSeqNo::seqcmp(seqno2, m_iLargestSeq) > 0)
         {
             LOGC(qrlog.Warn,
                  log << "RCV-LOSS/insert: seqno1=" << seqno1 << " too small, adjust to "
                      << CSeqNo::incseq(m_iLargestSeq));
             seqno1 = CSeqNo::incseq(m_iLargestSeq);
         }
         else
         {
             LOGC(qrlog.Warn,
                  log << "RCV-LOSS/insert: (" << seqno1 << "," << seqno2
                      << ") to be inserted is too small: m_iLargestSeq=" << m_iLargestSeq << ", m_iLength=" << m_iLength
                      << ", m_iHead=" << m_iHead << ", m_iTail=" << m_iTail << " -- REJECTING");
             return;
         }
     }
     m_iLargestSeq = seqno2;
```
As a result, `m_pRcvLossList->getFirstLostSeq()` returns SRT_SEQNO_NONE, so the current larger `m_iRcvCurrSeqNo` **1102276613** is used.

**To Reproduce**
Further investigation revealed the conditions under which this issue arises. The **SN1** from a previous packet loss event is stored in `m_iLargestSeq`. A next generated packet loss **SN2** will occur under the following conditions.
`
m_iSeqNoTH < The distance from S1 to S2  <= m_iMaxSeqNo
`
In other words, the distance from S1 to S2 is the second half of the SN cycle.

This occurs under the following circumstances. This is super rare and unlikely to happen in a normal environment.

- The data packet transfer rate is very high, and SN cycle over a several days.
- It is a very stable network with no packet loss occurring for few days.

**Possible Solution**
To fix this, I suggest adding two lines of code to initialize `m_iLargestSeq` when the list is empty, in two places before the return statement of the `CRcvLossList::remove()` function.

```
bool srt::CRcvLossList::remove(int32_t seqno)
{

     ...omitted...

         m_iLength--;
>        if (m_iLength == 0)
>          m_iLargestSeq = SRT_SEQNO_NONE;
         return true;
     }

     ...omitted...

     m_iLength--;
>    if (m_iLength == 0)
>      m_iLargestSeq = SRT_SEQNO_NONE;
     return true;
}
```

### PR DESCRIPTION
**Pull request by kura979**
Reset the `m_iLargestSeq` back to `SRT_SEQNO_NONE` once the loss list is empty. This way if the next packet loss seqno has a distance more than `m_iSeqNoTH` from the `m_iLargestSeq`, it is not ignored and added to the loss list.

Fixes #2873.

### CODE REVIEW

File: srtcore/list.cpp [hunk 1]
```diff
@@ -653,6 +653,8 @@ bool srt::CRcvLossList::remove(int32_t seqno)
         }
 
         m_iLength--;
+        if (0 == m_iLength)
```
Comment (maxsharabayko) [inline srtcore/list.cpp:656]:
```suggestion
        if (m_iLength == 0)
```

File: srtcore/list.cpp [hunk 2]
```diff
@@ -708,6 +710,8 @@ bool srt::CRcvLossList::remove(int32_t seqno)
     }
 
     m_iLength--;
+    if (0 == m_iLength)
```
Comment (maxsharabayko) [inline srtcore/list.cpp:713]:
```suggestion
    if (m_iLength == 0)
```

**Review by maxsharabayko — CHANGES_REQUESTED** [review]
The Yoda notation is not used in the project. To be consistent, the typical order should be  used.

**Review by maxsharabayko — APPROVED** [review]

**Comment by gou4shi1** [comment]
I think this PR will re-introduce this bug: fix https://github.com/Haivision/srt/issues/2192#issuecomment-983376741

**Comment by ethouris** [comment]
In #2527 I have provided various improvements for the receiver buffer. In this solution there's also changed the way of taking the sequence number for ACK, which is no longer taken from the loss list, and it's taken exclusively from the receiver buffer (the ACK actually acknowledges the initial contiguous region in the receiver buffer, which is defined directly in this version). Would you be able to take a look at that?

**Comment by maxsharabayko** [comment]
> `m_iLargestSeq` should record history seq, and should not be reset after empty, to fix concurrent issues.
> 
> We should find another way to fix your issue "the next packet loss seqno has a distance more than m_iSeqNoTH"

Just thinking out loud, what if the `m_iLargestSeq` would be ignored upon inserting to the RCV loss list if the loss list is empty?
As a workaround to resolve both issues until #2527 is merged.

**Comment by ethouris** [comment]
Yes, #2527 doesn't fix the loss list, it simply takes out one of its roles in deciding about ACK. Loss list in here is exclusively used for recording the loss for the need of NAKREPORT and in case of the file CC, also checking the loss level for speed control.

**Comment by maxsharabayko** [comment]
@gou4shi1 The bug was that a data packet 899264404 with a gap is inserted into the receiver buffer (899264403 is missing). But before the loss is recorded in the RCV loss list, the TSBPD thread drops the missing packet seqno 899264403.
I am afraid I forgot how does the m_iLargestSeq` fixes the concurrency issue.

The original issue description (https://github.com/Haivision/srt/issues/2192#issuecomment-983376741):
> When processData() received 899264404, it was added into the recv buffer, after recvbuf_acklock was unlocked, the tsbpd thread played 899264404 and dropped 899264403, then processData() immediately insert 899264403 back into loss list, after this, getFirstLostSeq() keep return 899264403

**Comment by maxsharabayko** [comment]
Please continue the discussion in #2881.
