### PR TITLE
Fixed some warning

### LINKED ISSUE #2370: fix "1<<" warn
srt\srtcore\utilities.h(304): warning C4245: 'initializing': conversion from 'int' to 'const uint32_t', signed/unsigned mismatch

https://github.com/Haivision/srt/blob/8d1643e111acba47c09415d18fbf85b107584f68/srtcore/utilities.h#L304

fix "1u <<" instead  "1<<"

### LINKED ISSUE #2371: warn, var i already used
core.cpp(10227): warning C4456: declaration of 'i' hides previous local declaration
core.cpp(10064): note: see declaration of 'i'

https://github.com/Haivision/srt/blob/8d1643e111acba47c09415d18fbf85b107584f68/srtcore/core.cpp#L10227

fix by rename of var i to another name

### LINKED ISSUE #2372: The 'false' value is implicitly cast to the integer type.
https://github.com/Haivision/srt/blob/8d1643e111acba47c09415d18fbf85b107584f68/srtcore/core.cpp#L1370

should return 0; instead return false;

### LINKED ISSUE #2374: The variable 'xxxx' is of enum type. It is odd that it is used as a variable of a Boolean-type.
https://github.com/Haivision/srt/blob/8d1643e111acba47c09415d18fbf85b107584f68/srtcore/core.cpp#L7558
https://github.com/Haivision/srt/blob/8d1643e111acba47c09415d18fbf85b107584f68/srtcore/core.cpp#L9702
https://github.com/Haivision/srt/blob/8d1643e111acba47c09415d18fbf85b107584f68/srtcore/core.cpp#L10162
https://github.com/Haivision/srt/blob/8d1643e111acba47c09415d18fbf85b107584f68/srtcore/fec.cpp#L1476

should use comparison with enum explicite value instead implicite bool

### PR DESCRIPTION
**Pull request by maxsharabayko**
- Explicitly compare with enum type. Fixes #2374.
- Fixed local variable 'i' hiding previous local declaration. Fixes #2371.
- Fixed 'false' value implicitly casting to an integer. Also some other minor warnings. Fixes #2372. Fixes #2370.

Partially addresses #1646.

### CODE REVIEW

File: srtcore/core.cpp [hunk 1]
```diff
@@ -1367,7 +1367,7 @@ size_t srt::CUDT::fillHsExtKMRSP(uint32_t* pcmdspec, const uint32_t* kmdata, siz
         {
             m_RejectReason = SRT_REJ_IPE;
             LOGC(cnlog.Fatal, log << "createSrtHandshake: IPE: srtkm_cmd=SRT_CMD_KMRSP and no kmdata!");
-            return false;
+            return 0;
```
Comment (ethouris) [inline srtcore/core.cpp:1370]: In line about 1760 there's a call of this and the value 0 better be handled. It's an easy way out, just return false there.

File: srtcore/stats.h [hunk 2]
```diff
@@ -56,7 +56,7 @@ class BytesPackets
 
     BytesPackets(uint64_t bytes, size_t n = 1)
```
Comment (gou4shi1) [inline srtcore/stats.h:57]: Why not just change the type of `n` to `uint32_t` here?

File: srtcore/stats.h [hunk 3]
```diff
@@ -56,7 +56,7 @@ class BytesPackets
...
         : m_bytes(bytes)
-        , m_packets(n)
+        , m_packets((uint32_t) n)
```
Comment (ethouris) [inline srtcore/stats.h:59]: I think a better idea would be to use `uint32_t` type for the constructor argument, but dunno how it will influence the application place.

Comment (ethouris) [reply srtcore/stats.h:59]: Ok, I made a short research of the call and it looks like almost everywhere the argument is explicitly cast to `size_t`, and where it isn't, the source type isn't `size_t` either (and it's usually a 32-bit type, `int32_t` or `int`). I think this can be safely changed to `uint32_t` and possibly explicitly cast in some places.
