### PR TITLE
Don't use CTimer in CUDTUnited's constructor.

### LINKED ISSUE #507: Under iOS/tvOS globals are initialized in a different order causing a crash
common.cpp:getTime() for iOS/tvOS does a "return x / s_ullCPUFrequency". s_ullCPUFrequency is a global uint64_t CTimer::s_ullCPUFrequency = CTimer::readCPUFrequency();

There is another global in core.cpp "CUDTUnited CUDT::s_UDTUnited” who’s constructor calls getTime().
CUDTUnited is called before s_ullCPUFrequency global is initialized and so s_ullCPUFrequency is zero and we get a divide by zero when getTime is called by CUDTUnited constructor.

### PR DESCRIPTION
**Pull request by maxlovic**
`s_UDTUnited` is a static instance of `CUDTUnited` with dynamic initialization (calling this constructor), while `CTimer` has a static member `s_ullCPUFrequency` with dynamic initialization. The order of initialization is not guaranteed.
`gettimeofday` is now used to initialize the pseudo-random number generator.

Fixes #507 in common.cpp. Some minor code cleanup in other files, with respect to the discussion in PR #510.
Closes #515.

### CODE REVIEW

File: srtcore/channel.cpp [hunk 1]
```diff
@@ -162,7 +162,7 @@ void CChannel::open(const sockaddr* addr)
       if (0 != ::getaddrinfo(NULL, "0", &hints, &res))
          throw CUDTException(MJ_SETUP, MN_NORES, NET_ERROR);
 
-      if (0 != ::bind(m_iSocket, res->ai_addr, (int) res->ai_addrlen))
+      if (0 != ::bind(m_iSocket, res->ai_addr, (socklen_t) res->ai_addrlen))
```
Comment (ethouris) [inline srtcore/channel.cpp]: This cast is useless - `ai_addrlen` field **is** of type `socklen_t`.

Comment (ethouris) [reply srtcore/channel.cpp]: Ok, then looxlike this cast is then the only warning-proof solution. Add at least some short comment that explains this cast.

**Comment by ethouris** [comment]
For me it's ok to go.

File: srtcore/common.cpp [hunk 2]
```diff
@@ -250,10 +248,16 @@ uint64_t CTimer::getTime()
...
-    rdtsc(x);
-    return x / s_ullCPUFrequency;
-    //Specific fix may be necessary if rdtsc is not available either.
+    // Otherwise we will have an infinite recursive functions calls
+    if (m_bUseMicroSecond == false)
+    {
+        uint64_t x;
+        rdtsc(x);
+        return x / s_ullCPUFrequency;
+    }
```
Comment (rndi) [inline srtcore/common.cpp]: Was the intent here to fall back to gettimeofday()? I think you may have meant to remove pre-processor conditionals.

Comment (maxlovic) [reply srtcore/common.cpp]: Thanks for noticing! Fixed.
