### PR TITLE
Fixed crash in craftKmResponse due to CryptoControl being NULL

### LINKED ISSUE #2231: [BUG] Crash in srt::CUDT::craftKmResponse from a null pointer in m_pCryptoControl
**Describe the bug**
Crash in `srt::CUDT::craftKmResponse` from a null pointer in `m_pCryptoControl` when under some atypical situations

**To Reproduce**
Very rare crash case, can't be sure how exactly it happened. However the machine where this can be gdb debugged from full core file can remain running for a week to do more debugging in, if needed.

**Expected behavior**
No crashes

**Desktop (please provide the following information):**
 - OS: Fedora 35
 - SRT Version / commit ID: 1.4.4 from Fedora package

**Additional context**

Backtrace:

```
#0  CCryptoControl::getKmMsg_size(unsigned long) const (ki=0, this=0x0) at /usr/src/debug/srt-1.4.4-1.fc35.aarch64/srtcore/crypto.h:137
        msgsize = <optimized out>
        hs_flags = 7
#1  srt::CUDT::craftKmResponse(unsigned int*, unsigned long&) (this=0xffff9ba03420, aw_kmdata=0xffffa6fddea0, w_kmdatasize=@0xffffa6fdde40: 26) at /usr/src/debug/srt-1.4.4-1.fc35.aarch64/srtcore/core.cpp:3915
        msgsize = <optimized out>
        hs_flags = 7
#2  0x0000ffffaee30d04 in srt::CUDT::processConnectRequest(sockaddr_any const&, srt::CPacket&) (this=0x1e76280, addr=..., packet=...) at /usr/src/debug/srt-1.4.4-1.fc35.aarch64/srtcore/core.cpp:10638
        kmdata = 
          {4, 0, 927805440, 4129124264, 2801655504, 65535, 45082, 0, 4987808, 0, 927805440, 4129124264, 2801655520, 65535, 2932267136, 65535, 2801655712, 65535, 2932270692, 65535, 2550136864, 65535, 2801661360, 65535, 24, 0}
        kmdatasize = 26
        conn = CONN_ACCEPT
        error = 6
        acpu = 0xffff9ba03420
        result = 0
        exp_len = 48
        hs = 
          {static m_iContentSize = 48, static HS_EXT_HSREQ = 1, static HS_EXT_KMREQ = 2, static HS_EXT_CONFIG = 4, m_iVersion = 5, m_iType = 7, m_iISN = 157897213, m_iMSS = 1500, m_iFlightFlagSize = 8192, m_iReqType = URQ_CONCLUSION, m_iID = 377572497, m_iCookie = 1999797760, m_piPeerIP = {1646402732, 0, 0, 0}, m_extension = true}
        cookie_val = <optimized out>
        id = 182198432
        accepted_hs = <optimized out>
#3  0x0000ffffaee4c520 in srt::CRcvQueue::worker_ProcessConnectionRequest(srt::CUnit*, sockaddr_any const&) (this=this@entry=0x1e4b800, unit=0x1e7ccf8, addr=...)
    at /usr/src/debug/srt-1.4.4-1.fc35.aarch64/srtcore/queue.cpp:1421
        cg = {m_mutex = @0x1e4b868}
        listener_ret = 0
        have_listener = false
#4  0x0000ffffaee4cb30 in srt::CRcvQueue::worker(void*) (param=0x1e4b800) at /usr/src/debug/srt-1.4.4-1.fc35.aarch64/srtcore/queue.cpp:1255
        have_received = false
        rst = RST_OK
        curtime_minus_syn = {m_timestamp = <optimized out>}
        ul = <optimized out>
        self = 0x1e4b800
        sa = 
          {{sin = {sin_family = 2, sin_port = 62858, sin_addr = {s_addr = 1646402732}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 2, sin6_port = 62858, sin6_flowinfo = 1646402732, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}, sa = {sa_family = 2, sa_data = "\212\365\254\034\"b\000\000\000\000\000\000\000"}}, len = 16}
        id = 0
        unit = 0x1e7ccf8
        cst = CONN_CONTINUE
#5  0x0000ffffaec5dfb4 in start_thread (arg=<optimized out>) at pthread_create.c:435
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {281473483402784, 281474078689184, 281474078689182, 8447632, 281474078689183, 0, 281473474953216, 281473621367728, 281473474953216, 8447632, 281473483400560, 16132077304594628293, 0, 16132077304464066169, 0, 0, 0, 0, 0, 0, 0, 0}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x0000ffffaecc8f5c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:79
```

Initial extra gdb debugging:

```
(gdb) frame 1
#1  srt::CUDT::craftKmResponse (this=0xffff9ba03420, aw_kmdata=0xffffa6fddea0, w_kmdatasize=@0xffffa6fdde40: 26) at /usr/src/debug/srt-1.4.4-1.fc35.aarch64/srtcore/core.cpp:3915
3915	        size_t msgsize = m_pCryptoControl->getKmMsg_size(0);
(gdb) print m_pCryptoControl
$1 = std::unique_ptr<CCryptoControl> = {get() = 0x0}
```

### PR DESCRIPTION
**Pull request by maxsharabayko**
1. Check if `CryptoControl` exists in `craftKmResponse(..)`. Fixes #2231.
2. Cleaned up the `CUDT::processConnectRequest(..)` function.
   - ⚠️  Update listener write-ready only after the new connection. Was changed in #1650, but must not be done at all #1831.

### CODE REVIEW

File: srtcore/core.cpp [hunk 1]
```diff
@@ -10748,8 +10756,8 @@ int srt::CUDT::processConnectRequest(const sockaddr_any& addr, CPacket& packet)
         HLOGC(cnlog.Debug, log << "processConnectRequest: ... NOT. Rejecting because broken.");
         return m_RejectReason;
     }
-    size_t exp_len =
-        CHandShake::m_iContentSize; // When CHandShake::m_iContentSize is used in log, the file fails to link!
+    // When CHandShake::m_iContentSize is used in log, the file fails to link!
+    size_t exp_len = CHandShake::m_iContentSize;
```
Comment (ethouris) [inline srtcore/core.cpp:10760]: This can be fixed easier - in 10772 use `+CHandShake::m_iContentSize` instead of `exp_len`.

File: srtcore/core.cpp [hunk 2]
```diff
@@ -3908,6 +3908,14 @@ EConnectStatus srt::CUDT::craftKmResponse(uint32_t* aw_kmdata, size_t& w_kmdatas
     int hs_flags = SrtHSRequest::SRT_HSTYPE_HSFLAGS::unwrap(m_ConnRes.m_iType);
     if (IsSet(hs_flags, CHandShake::HS_EXT_KMREQ))
     {
+        if (!m_pCryptoControl)
```
Comment (ethouris) [inline srtcore/core.cpp:3911]: This lacks an explanation as to why this fixes the problem. This function should at best have:

* The declarations of all mutexes that are locked before calling this function and made sure that the list is stable against all places from which this function is called
* In all places that can modify `m_pCryptoControl` make sure that locking on that place can exclude the possibility of modifying this field anywhere up to the end of this function (mention these places here)

File: srtcore/core.cpp [hunk 3]
```diff
@@ -3908,6 +3908,14 @@ EConnectStatus srt::CUDT::craftKmResponse(uint32_t* aw_kmdata, size_t& w_kmdatas
...
+        {
+            m_RejectReason = SRT_REJ_IPE;
+            LOGC(cnlog.Error, log << "IPE: craftKmResponse needs to send KM, but CryptoControl does not exist."
+                << " Socket state: connected=" << boolalpha << m_bConnected << ", connecting=" << m_bConnecting
+                << ", broken=" << m_bBroken << ", opened " << m_bOpened << ", closing=" << m_bClosing << ".");
+            return CONN_REJECT;
+        }
         // This is a periodic handshake update, so you need to extract the KM data from the
```
Comment (ethouris) [inline srtcore/core.cpp:3919]: I can see that everything below this line is of completely different purpose and it serves as a kind of refactoring. No functionality has been changed there. If so, this should be split into a different PR.

File: srtcore/core.cpp [hunk 4]
```diff
@@ -11029,16 +11012,31 @@ int srt::CUDT::processConnectRequest(const sockaddr_any& addr, CPacket& packet)
             }
         }
 
-        // send back a response if connection failed or connection already existed
-        // (or the above procedure failed)
-        if (result == -1)
+        if (result == 1)
```
Comment (ethouris) [inline srtcore/core.cpp:11015]: What's exactly the purpose of inverting the order of underlying statements beside confusing the reviewer? If the purpose was to add an extra condition to `else`, this could be done without this reordering, too.

File: srtcore/core.cpp [hunk 5]
```diff
@@ -11029,16 +11012,31 @@ int srt::CUDT::processConnectRequest(const sockaddr_any& addr, CPacket& packet)
...
+            // or the connection already existed, but manually sending the HS response above has failed.
+            // HSv4: Send the SHUTDOWN message to the peer (see PR #2010) in order to disallow then to connect.
+            //       The HSv4 clients do not interpret the error handshake response correctly.
+            // HSv5: Send a handshake with an error code (hs.m_iReqType set earlier) to the peer.
             if (hs.m_iVersion < HS_VERSION_SRT1)
             {
                 HLOGC(cnlog.Debug, log << CONID() << "processConnectRequest: HSv4 caller, sending SHUTDOWN after rejection with "
                         << RequestTypeStr(hs.m_iReqType));
-                // The HSv4 clients do not interpret the error handshake response correctly.
-                // In order to really disallow them to connect there's needed the shutdown response.
```
Comment (ethouris) [inline srtcore/core.cpp:11041]: Not sure why this comment is removed. This is an important information as to why such an unusual thing as sending shutdown has been placed here.

Comment (maxsharabayko) [reply srtcore/core.cpp:11041]: It has been moved above. 👆

File: srtcore/core.cpp (hunk 3 above)
Comment (maxsharabayko) [reply srtcore/core.cpp:3919]: THat's why these changes are in a separate commit.

File: srtcore/core.cpp (hunk 1 above)
Comment (maxsharabayko) [reply srtcore/core.cpp:10760]: As I can see, you wrote that exactly this (using the `CHandShake::m_iContentSize` in log) fails to link.

File: srtcore/core.cpp (hunk 5 above)
Comment (ethouris) [reply srtcore/core.cpp:11041]: Ah, ok, missed that.

File: srtcore/core.cpp (hunk 1 above)
Comment (ethouris) [reply srtcore/core.cpp:10760]: You missed the `+` before the name. This is exactly what fixes the problem.

File: srtcore/core.cpp (hunk 3 above)
Comment (ethouris) [reply srtcore/core.cpp:3919]: Ok, fair enough.

File: srtcore/core.cpp [hunk 6]
```diff
@@ -10944,47 +10949,17 @@ int srt::CUDT::processConnectRequest(const sockaddr_any& addr, CPacket& packet)
...
+        // The connection already exists (no new connection has been created, no response sent).
+        // Send the conclusion response manually here in case the peer has missed the first one.
+        // The value  `result` here should be 0.
         if (acpu)
         {
             // This is an existing connection, so the handshake is only needed
             // because of the rule that every handshake request must be covered
             // by the handshake response. It wouldn't be good to call interpretSrtHandshake
-            // here because the data from the handshake have been already interpreted
+            // here because the data from the handshake has been already interpreted
```
Comment (ethouris) [inline srtcore/core.cpp:10970]: Nothing to fix here. https://www.britannica.com/dictionary/eb/qa/Is-Data-Singular-or-Plural-

File: srtcore/core.cpp [hunk 7]
```diff
@@ -11029,16 +11004,31 @@ int srt::CUDT::processConnectRequest(const sockaddr_any& addr, CPacket& packet)
...
+            // a new connection has been created, enable epoll for write
+            // Note: not using SRT_EPOLL_CONNECT symbol because this is a procedure
+            // executed for the accepted socket.
+            uglobal().m_EPoll.update_events(m_SocketID, m_sPollID, SRT_EPOLL_OUT, true);
+        }
+        else if (result == -1)
+        {
+            // The new connection failed
+            // or the connection already existed, but manually sending the HS response above has failed.
+            // HSv4: Send the SHUTDOWN message to the peer (see PR #2010) in order to disallow then to connect.
```
Comment (ethouris) [inline srtcore/core.cpp:11033]: them?

File: srtcore/core.cpp (hunk 4 above)
Comment (maxsharabayko) [reply srtcore/core.cpp:11015]: Processing expected positive result first. It is also shorter, mainly only updating the epoll. Otherwise, handle the error.
