### PR TITLE
Eliminated ref_t. Some more convention fixes

### LINKED ISSUE #943: Replace the use of Ref with dedicated variables with prefix
There are concerns about extraordinary complications in the code provided by the `ref_t` reference wrapper. The use of it should be replaced by a regular reference, and variables used to retrieve the values from it should have `r_` prefix and should be dedicated to value retrieval only.

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #943, #945

The new convention for passing parameters by writable reference applied. The use of `ref_t` and `Ref` has been eliminated, as well as the definitions thereof.

The new convention is:

1. Reference parameters must have `w_` prefix and pointer parameters - `pw_` prefix.
2. Passing **any expression** that resolves to a reference to a writable object requires `(extra_parentheses)` around the whole expression. This applies to:
   - passing single variable to a function
   - passing a field of a structure
   - passing a pointer to a writable object, both as pointer or as reference
   - assigning a pointer to a pointer-type field of another structure to be later passed to a function for writing
   - regardless if this reference variable is a local variable, or a parameter pass-through

The above rules don't embrace passing a non-writable object, usually preferred as const, but also when it's required to be passed by writable pointer or reference, but the function doesn't modify it.

Also the order of parameters is changed to the convention - writable reference parameters should be placed after value parameters.

### CODE REVIEW

**Comment by ethouris** [comment]
Fixes #943, #945

**Comment by maxsharabayko** [comment]
Looks like it also depends on PR #1028. At least I see some function from that not yet merged PR in this one.

**Comment by ethouris** [comment]
Purged of any premature merges. Now the PR is completely independent.

File: apps/srt-file-transmit.cpp [hunk 1]
```diff
@@ -222,11 +223,8 @@ int parse_args(FileTransmitConfig &cfg, int argc, char** argv)
 
 
 
-void ExtractPath(string path, ref_t<string> dir, ref_t<string> fname)
+tuple<string, string> ExtractPath(string path)
 {
```
Comment (maxsharabayko) [inline apps/srt-file-transmit.cpp]: This looks like something from another PR.

**Comment by ethouris** [comment]
I understand, but the trouble is that splitting makes sense if they can be independent - whereas as this involves deletion of `ref_t` and `Ref`, this change applies to both, or at least one would be dependent on the other and require a blocking merge cycle.

**Comment by maxsharabayko** [comment]
Well, it is simple to solve. The first commit should remove ref_t from apps, the second - from the core.

**Comment by maxsharabayko** [comment]
So like this then
```
git reset @~3
git add ./apps/*
git add ./testing/*
git commit -m "[apps] Eliminated ref_t from apps"
git add ./srtcore/*
git commit -m "[core] Eliminated ref_t from the core"
git push --force
```
