### PR TITLE
[core] Fixed suspicious (HCRYPT_CTX_F_ENCRYPT & ctx->flags ? ..).

### LINKED ISSUE #2377: Suspicious calculation. Please use parentheses to clarify the code. The code ''a&b?c:d'' should be written as either ''(a&b)?c:d'' or ''a&(b?c:d)''.
https://github.com/Haivision/srt/blob/e8b713e954345291e8d6e2314d1e5094a6a14179/haicrypt/hcrypt_sa.c#L40
https://github.com/Haivision/srt/blob/e8b713e954345291e8d6e2314d1e5094a6a14179/haicrypt/hcrypt_sa.c#L90

### PR DESCRIPTION
**Pull request by maxsharabayko**
Using parentheses to clarify the code.

Fixes #2377.

### CODE REVIEW

File: haicrypt/hcrypt_sa.c [hunk 1]
```diff
@@ -37,7 +37,7 @@ int hcryptCtx_SetSecret(hcrypt_Session *crypto, hcrypt_Ctx *ctx, const HaiCrypt_
 		ctx->cfg.pwd_len = 0;
 		/* KEK: Key Encrypting Key */
 		if (0 > (iret = crypto->cryspr->km_setkey(crypto->cryspr_cb,
-							  (HCRYPT_CTX_F_ENCRYPT & ctx->flags ? true : false),
+							  ((HCRYPT_CTX_F_ENCRYPT & ctx->flags) ? true : false),
```
Comment (jeandube) [inline haicrypt/hcrypt_sa.c:40]: Hopefully this will shut-up the code analyser. There is 0-ambiguity with the "C" pririty of operators in the case.

File: haicrypt/hcrypt_sa.c [hunk 2]
```diff
@@ -87,7 +87,7 @@ int hcryptCtx_GenSecret(hcrypt_Session *crypto, hcrypt_Ctx *ctx)
 	HCRYPT_PRINTKEY(kek, kek_len, "kek");
 	
 	/* KEK: Key Encrypting Key */
-	if (0 > (iret = crypto->cryspr->km_setkey(crypto->cryspr_cb, (HCRYPT_CTX_F_ENCRYPT & ctx->flags ? true : false), kek, kek_len))) {
+	if (0 > (iret = crypto->cryspr->km_setkey(crypto->cryspr_cb, ((HCRYPT_CTX_F_ENCRYPT & ctx->flags) ? true : false), kek, kek_len))) {
```
Comment (jeandube) [inline haicrypt/hcrypt_sa.c:90]: ditto

**Review by jeandube — APPROVED** [review]
