### PR TITLE
[BUG] Fixed async event reporting and mutex lock ordering for groups

### LINKED ISSUE #1631: [BUG] Recursive lock on an attempt to close a group
Closing a group iterates over member sockets (`CUDTGroup::close()`), calls `close()` on the first member socket ` CUDTUnited::close(CUDTSocket* s)`). The `m_ControlLock` mutex is locked, then eventually `CUDTSocket::removeFromGroup()` is called, which again tries to acquire the same lock.
Results in:
- exception thrown on Windows;
- hang up on close on Ubuntu.

Reproducible by `Bonding.SRTConnectGroup` unit test from PR #1446.

Tested with SRT commit ID: 7848fcdaf10214e3795d463bc02e849a2d61b8fc October 27.

```c++
CUDTUnited::close(CUDTSocket* s)
{
    ScopedLock socket_cg(s->m_ControlLock);
    if (s->m_Status != SRTS_LISTENING)
    {
        // makeShutdown() will attempt to lock s->m_ControlLock in CUDTSocket::removeFromGroup
        s->makeShutdown();
    }
}


void CUDTSocket::makeShutdown()
{
#if ENABLE_EXPERIMENTAL_BONDING
    if (m_IncludedGroup)
    {
        removeFromGroup(true);
    }
#endif

    HLOGC(smlog.Debug, log << "@" << m_SocketID << " CLOSING AS SOCKET");
    m_pUDT->closeInternal();
}

void CUDTSocket::removeFromGroup(bool broken)
{
    CUDTGroup* pg = 0;
    {
        ScopedLock grd (m_ControlLock);
        pg = m_IncludedGroup;
        m_IncludedIter = CUDTGroup::gli_NULL();
        m_IncludedGroup = NULL;
    }
    // ...
}

```

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #1631, #1625, #1605, #1603, #1612, #1599, #1585

This PR introduces a common function that is run in case of a broken connection. It takes care of correct error reporting to the application using asynchronous connection methods and sets properly epoll readiness flags for the group.

### CODE REVIEW

File: srtcore/core.cpp [hunk 1]
```diff
@@ -8652,13 +8652,9 @@ void CUDT::processCtrl(const CPacket &ctrlpkt)
...
-        // Signal the sender and recver if they are waiting for data.
-        releaseSynch();
-        // Unblock any call so they learn the connection_broken error
-        s_UDTUnited.m_EPoll.update_events(m_SocketID, m_sPollID, SRT_EPOLL_ERR, true);
-
-        CGlobEvent::triggerEvent();
-
+        // This does the same as it would happen on connection timeout,
+        // just we know about this state prematurely thanks to this message.
+        updateBrokenConnection(SRT_ECONNLOST);
```
Comment (maxsharabayko) [inline srtcore/core.cpp:8657]: Connection hook will now be also called at shutdown `UMSG_SHUTDOWN`? Is this correct?

File: srtcore/queue.cpp [hunk 2]
```diff
@@ -960,34 +960,24 @@ void CRendezvousQueue::updateConnStatus(EReadStatus rst, EConnectStatus cst, con
...
+            int ccerror = SRT_ECONNREJ;
+            if (i->m_pUDT->m_RejectReason == SRT_REJ_UNKNOWN)
             {
-                // Timer expired, set TIMEOUT forcefully
-                i->m_pUDT->m_RejectReason = SRT_REJ_TIMEOUT;
+                if (!is_zero(i->m_tsTTL))
+                {
+                    // Timer expired, set TIMEOUT forcefully
+                    i->m_pUDT->m_RejectReason = SRT_REJ_TIMEOUT;
+                    ccerror = SRT_ENOSERVER;
```
Comment (maxsharabayko) [inline srtcore/queue.cpp:970]: This is a useful fix. Previously it was possible that a connection had already been rejected with some rejection code, but the rejection reason was overwritten with `SRT_REJ_TIMEOUT` if this timer hits in parallel.

File: srtcore/core.cpp (hunk 1 above)
Comment (ethouris) [reply srtcore/core.cpp:8657]: Correct. The SHUTDOWN situation differs to TIMEOUT only by the fact that SHUTDOWN succeeded to be received by the agent party and it should be handled the same way.

File: srtcore/queue.cpp (hunk 2 above)
Comment (ethouris) [reply srtcore/queue.cpp:970]: Yes, and that's exactly the fix. Jean reported that in several situations, tho it wasn't recorded as an issue.

File: srtcore/core.cpp (hunk 1 above)
Comment (maxsharabayko) [reply srtcore/core.cpp:8657]: From [API-functions.md](https://github.com/Haivision/srt/blob/master/docs/API-functions.md#srt_connect_callback) about `srt_connect_callback`:
> This call installs a callback hook, which will be executed on a given clr socket just after the pending connection situation in the background has been resolved (that is, when the connection succeeded or failed). 

SHUTDOWN may arrive:
- right after HS response, when callback makes sense,
- in the end of transmission if the peer closes connection, then callback does not look reasonable.

File: srtcore/core.cpp [hunk 3]
```diff
@@ -10909,6 +10889,68 @@ void CUDT::checkTimers()
...
+    }
+#endif
+
+    // app can call any UDT API to learn the connection_broken error
+    s_UDTUnited.m_EPoll.update_events(m_SocketID, m_sPollID, SRT_EPOLL_IN | SRT_EPOLL_OUT | SRT_EPOLL_ERR, true);
+    CGlobEvent::triggerEvent();
+    if (m_cbConnectHook)
+    {
+        CALLBACK_CALL(m_cbConnectHook, m_SocketID, errorcode, m_PeerAddr.get(), token);
+    }
```
Comment (maxsharabayko) [inline srtcore/core.cpp:10927]: Maybe?

```suggestion
    if (m_cbConnectHook && m_bConnecting)
    {
        CALLBACK_CALL(m_cbConnectHook, m_SocketID, errorcode, m_PeerAddr.get(), token);
    }
```

Comment (ethouris) [reply srtcore/core.cpp:11157]: Actually the most important intention of the callback is to be called at the moment when the connection is broken. So this would be wrong.

Comment (maxsharabayko) [reply srtcore/core.cpp:11157]: The docs on [srt_connect_callback](https://github.com/Haivision/srt/blob/master/docs/API-functions.md#srt_connect_callback) disagree:
> This call installs a callback hook, which will be executed on a given clr socket just after the pending connection situation in the background has been resolved (that is, when the connection succeeded or failed).

See also [my comment above](https://github.com/Haivision/srt/pull/1639#discussion_r518659096).

File: srtcore/core.cpp [hunk 4]
```diff
@@ -4234,7 +4273,10 @@ bool CUDT::processAsyncConnectRequest(EReadStatus         rst,
     {
         // m_RejectReason already set at worker_ProcessAddressedPacket.
         LOGC(cnlog.Warn,
-             log << "processAsyncConnectRequest: REJECT reported from HS processing, not processing further.");
+             log << "processAsyncConnectRequest: REJECT reported from HS processing:"
+             << srt_rejectreason_str(m_RejectReason)
+             << "- not processing further; REQ-TIME LOW");
+        m_tsLastReqTime = steady_clock::time_point();
```
Comment (ethouris) [inline srtcore/core.cpp:4279]: Resetting the last req time here causes that in case of password-related rejection the socket would be closed immediately and not processed further, which also means that the immediate state found on the socket by the application upon reception of epoll error would be now SRTS_BROKEN, instead of, like previously SRTS_CONNECTING.

This likely should be the fix for the first thing here, maybe instead it should be removed from here, but the process of rejection reviewed.

File: srtcore/core.cpp (hunk 3 above)
Comment (ethouris) [reply srtcore/core.cpp:11157]: Ok, I was kinda unclear.

The intention of the callback is to be called at the moment when the connection is SUCCESSFUL OR BROKEN. That's exactly what is written in the documentation you cited.

Whereas your proposal limits the cases of calling it to successful resolution only.

**Review by maxsharabayko — COMMENTED** [review]
- [x] `TEST(Bonding, DISABLED_NonBlockingGroupConnect)` is still disabled, please enable it as well.

File: srtcore/core.cpp (hunk 3 above)
Comment (maxsharabayko) [reply srtcore/core.cpp:11157]: The problem I am raising is the following.
Connection hook will now be **also** called at shutdown `UMSG_SHUTDOWN`. 

`SHUTDOWN` may arrive:

1. right after HS response, when **callback makes sense**,
2. at the end of transmission if the peer closes the connection, then **callback does not look reasonable**.

What do you think about situation no. 2?

On my proposal, after connection is established, `m_bConnecting` becomes false. The question is if the callback is called befare of after this?

File: testing/testmedia.cpp [hunk 5]
```diff
@@ -890,6 +891,188 @@ void SrtCommon::PrepareClient()
...
 
 #if ENABLE_EXPERIMENTAL_BONDING
+#if 0
+void SrtConn_ConnectCB(void *opaq, SRTSOCKET ns, int errorcode, const struct sockaddr *psaPeer, int token)
+{
+    char szEndPoint[SRTC_ENDPOINTLEN];
+    SrtConn *srtc = (SrtConn *)opaq;
+    int iLID = token-1;
+    int iRejectReason = SRT_REJ_UNKNOWN;
+    srtcLog(srtc, LOG_DEBUG, "connectCB(%p,%x,%d,%s,%d)\n",
```
Comment (maxsharabayko) [inline testing/testmedia.cpp:901]: dead code

**Review by maxsharabayko — COMMENTED** [review]
Changes to `srt-test-live` should go in a separate PR. This one is already big enough and each review iteration consumes time on looking through changes to apps.
For now I will concentrate on changes to the library.

File: srtcore/group.cpp [hunk 6]
```diff
@@ -1732,11 +1837,11 @@ void CUDTGroup::fillGroupData(SRT_MSGCTRL&       w_out, // MSGCTRL to be written
     w_out.grpdata = grpdata;
 }
 
-struct FLookupSocketWithEvent
+struct FLookupSocketWithEvent_LOCKED
 {
     CUDTUnited* glob;
     int         evtype;
-    FLookupSocketWithEvent(CUDTUnited* g, int event_type)
+    FLookupSocketWithEvent_LOCKED(CUDTUnited* g, int event_type)
```
Comment (maxsharabayko) [inline srtcore/group.cpp:1844]: 1. Please follow some naming convention
2. What is expected to be locked?

File: srtcore/core.cpp (hunk 1 above)
Comment (ethouris) [reply srtcore/core.cpp:8858]: Ok, I understand what you mean. The real intention for the connect callback is to catch the moment when the socket got broken and is about to be removed in order to collect the information before the socket disappears and the information about the broken connection is lost. This is important regardless as to whether it didn't ever connect due to rejection, or got broken after being functional for some time.

In the light of this, it's actually the description not exactly correct.

File: testing/testmedia.cpp (hunk 5 above)
Comment (ethouris) [reply testing/testmedia.cpp:901]: Right. That's not even a dead code, rather a copy of the original code that was causing crashes in the library, which serves as a pattern to that one. I'll ship this off.

File: srtcore/api.cpp [hunk 7]
```diff
@@ -126,6 +126,7 @@ SRT_SOCKSTATUS CUDTSocket::getStatus()
     return m_Status;
 }
 
+// [[using locked(m_GlobControlLock)]]
 void CUDTSocket::makeShutdown()
 {
 #if ENABLE_EXPERIMENTAL_BONDING
```
[the remark this answers is not in the document]
Comment (ethouris) [reply srtcore/api.cpp:132]: Could be, but I'd personally prefer this to be used only in a special thread-tracking mode, in which the lock state would be recorded in a special variable, not just in the debug mode.

File: srtcore/api.cpp [hunk 8]
```diff
@@ -649,101 +672,111 @@ int CUDTUnited::newConnection(const SRTSOCKET listen, const sockaddr_any& peer,
...
-      int write_modes = SRT_EPOLL_OUT | SRT_EPOLL_ERR;
-      srt_epoll_add_usock(g->m_RcvEID, ns->m_SocketID, &read_modes);
-      srt_epoll_add_usock(g->m_SndEID, ns->m_SocketID, &write_modes);
+           // Add also per-direction subscription for the about-to-be-accepted socket.
+           // Both first accepted socket that makes the group-accept and every next
+           // socket that adds a new link.
+           int read_modes = SRT_EPOLL_IN | SRT_EPOLL_ERR;
+           int write_modes = SRT_EPOLL_OUT | SRT_EPOLL_ERR;
+           epoll_add_usock_INTERNAL(g->m_RcvEID, ns, &read_modes);
+           epoll_add_usock_INTERNAL(g->m_SndEID, ns, &write_modes);
```
[the remark this answers is not in the document]
Comment (ethouris) [reply srtcore/api.cpp:764]: Well, I needed some special marker that should attract attention because of dangerous treats of these functions. Similar thing about `_LOCKED` suffix. This function isn't according to the naming convention either because it looks more like an API function. Probably something like `epollAddSrtSocket` would be better, or even something reaching deeper into the internals, driven out of `CUDT::s_UDTUnited.m_EPoll.add...`

File: srtcore/api.cpp [hunk 9]
```diff
@@ -1133,21 +1166,31 @@ SRTSOCKET CUDTUnited::accept(const SRTSOCKET listen, sockaddr* pw_addr, int* pw_
    if (s == NULL)
       throw CUDTException(MJ_SETUP, MN_CLOSED, 0);
 
+   // Set properly the SRTO_GROUPCONNECT flag
+   s->core().m_OPT_GroupConnect = 0;
+
```
[the remark this answers is not in the document]
Comment (ethouris) [reply srtcore/api.cpp:1171]: It's taken care of that it is properly set, that is:
 - it's always 0 on the accepted socket, if the connection is not for a group member
 - then it's checked if this is a group member, if so, it's set to 1

This flag is meaningful in two cases:

1. On the listener socket - the user sets it explicitly to allow groupwise connections to be accepted.
2. Set internally on the accepted socket - this exactly here - so that a user can check this flag in the listener callback.

[the remark this answers is not in the document]
Comment (ethouris) [reply srtcore/api.cpp:1171]: Note of course that this is an old code and this aspect wasn't changed here. Only the locking rules for the group.

File: srtcore/core.cpp [hunk 10]
```diff
@@ -6017,7 +6118,7 @@ void CUDT::considerLegacySrtHandshake(const steady_clock::time_point &timebase)
 
     if (m_iSndHsRetryCnt <= 0)
     {
-        HLOGC(cnlog.Debug, log << "Legacy HSREQ: not needed, expire counter=" << m_iSndHsRetryCnt);
+        //HLOGC(cnlog.Debug, log << "Legacy HSREQ: not needed, expire counter=" << m_iSndHsRetryCnt);
```
[the remark this answers is not in the document]
Comment (ethouris) [reply srtcore/core.cpp:6121]: Ah, I commented it out because it was flooding this message in one of the test. Shouldn't be the case anymore.

File: srtcore/core.cpp (hunk 3 above)
Comment (ethouris) [reply srtcore/core.cpp:11157]: The situation 2 was the exact reason for introducing the connect callbacks. It was in order to allow a non-blocking-style function to notify this information so that the application knows that it must revive the link.

File: srtcore/group.cpp (hunk 6 above)
Comment (ethouris) [reply srtcore/group.cpp:1844]: Actually both `CUDTUnited::m_GlobControlLock` and `CUDTGroup::m_GroupLock` should be locked. The special `_LOCKED` marker is added here because this is a functional so this is the only way how it can be eye-catching at the usage point.

File: srtcore/api.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (maxsharabayko) [reply srtcore/api.cpp:764]: There are two naming styles used so far:
- camel case;
- lower case with underscores

I get the point of "eye catching". I am just concerned about adding a third naming style, making the code look like a garland.

File: srtcore/group.cpp (hunk 6 above)
Comment (maxsharabayko) [reply srtcore/group.cpp:1844]: Where is the special comment?
```c++
// [[using locked(m_GlobControlLock)]]
```

Comment (ethouris) [reply srtcore/group.cpp:1819]: Appropriate markers added.

**Comment by maxsharabayko** [comment]
### TODO

- [ ] Improve connect callback unit test

Take `TEST(Bonding, NonBlockingGroupConnect)` and modify the `ConnectCallback` as presented further, and the test will hang up with the current version 3fa5b49 and previous versions as well.

```c++
void ConnectCallback(void* /*opaq*/, SRTSOCKET sock, int error, const sockaddr* /*peer*/, int token)
{
    std::cout << "Connect callback. Socket: " << sock
        << ", error: " << error
        << ", token: " << token << '\n';

    srt_close(sock);
}
```

**Comment by maxsharabayko** [comment]
(For future reference)

Data race acessing `m_iTsbPdDelay_ms`

```shell
Thread A:
  Write of size 4 at 0x7ba80000c134 by thread T6 (mutexes: write M365):
    #0 CUDT::fillSrtHandshake_HSREQ(unsigned int*, unsigned long, int) core.cpp:1633 (test-srt:x86_64+0x10025e4f2)
	   [NO LOCKS, writes to m_iTsbPdDelay_ms]
    #1 CUDT::fillSrtHandshake(unsigned int*, unsigned long, int, int) core.cpp:1610 (test-srt:x86_64+0x10025e141)
	   [NO LOCKS]
    #2 CUDT::createSrtHandshake(int, int, unsigned int const*, unsigned long, CPacket&, CHandShake&) core.cpp:2231 (test-srt:x86_64+0x10026386c)
	   [NO LOCK, but scope-locks m_parent->m_ControlLock and s_UDTUnited.m_GlobControlLock a bit later to fill HS group extension.
    #3 CUDT::processAsyncConnectRequest(EReadStatus, EConnectStatus, CPacket const&, sockaddr_any const&) core.cpp:4287 (test-srt:x86_64+0x1002872bd)
	   [NO LOCK]
    #4 CRendezvousQueue::updateConnStatus(EReadStatus, EConnectStatus, CPacket const&) queue.cpp:1049 (test-srt:x86_64+0x1003ae9e5)
	   [UNDER m_RIDVectorLock LOCK, can also change m_pUDT->m_bConnecting = false
    #5 CRcvQueue::worker(void*) queue.cpp:1295 (test-srt:x86_64+0x1003b2447)
	   [NO LOCK]

Thread B:
  Previous read of size 4 at 0x7ba80000c134 by main thread (mutexes: write M317):
    #0 CUDTGroup::syncWithSocket(CUDT const&, HandshakeSide) group.cpp:936 (test-srt:x86_64+0x1003f6e6d)
    #1 CUDTUnited::groupConnect(CUDTGroup*, SRT_GroupMemberConfig_*, int) api.cpp:1584 (test-srt:x86_64+0x1001d0e40)
    #2 CUDTUnited::singleMemberConnect(CUDTGroup*, SRT_GroupMemberConfig_*) api.cpp:1284 (test-srt:x86_64+0x1001ccc44)
    #3 CUDTUnited::connect(int, sockaddr const*, int, int) api.cpp:1270 (test-srt:x86_64+0x1001cd5ad)
    #4 CUDT::connect(int, sockaddr const*, int, int) api.cpp:3486 (test-srt:x86_64+0x1001e2cc5)
    #5 srt_connect srt_c_api.cpp:83 (test-srt:x86_64+0x1003dc2e5)
```

File: srtcore/api.cpp [hunk 11]
```diff
@@ -1460,17 +1454,53 @@ int CUDTUnited::groupConnect(CUDTGroup* pg, SRT_SOCKGROUPCONFIG* targets, int ar
...
+            if (g.m_bClosing)
+            {
+                HLOGC(aclog.Debug, log << "srt_connect_group: not processing @" << sid << " due to CLOSED GROUP $" << g.m_GroupID);
+                proceed = false;
+            }
+
+            if (proceed)
+            {
+                CUDTGroup::gli_t f = g.add(data);
```
Comment (maxsharabayko) [inline srtcore/api.cpp:1486]: The group may still change in between cause there is no lock of `m_GroupLock` here. Just the chances are lower now, as those two operations stand close together:
- `if (g.m_bClosing)`
- `g.add(data)`

File: srtcore/api.cpp [hunk 12]
```diff
@@ -683,6 +683,12 @@ int CUDTUnited::newConnection(const SRTSOCKET listen, const sockaddr_any& peer,
            // For redundancy group, at least, update the status in the group
            CUDTGroup* g = ns->m_IncludedGroup;
            ScopedLock glock (g->m_GroupLock);
+           if (g->m_bClosing)
+           {
+               error = 1; // "INTERNAL REJECTION"
+               goto ERR_ROLLBACK;
```
Comment (maxsharabayko) [inline srtcore/api.cpp:689]: I know this goto label already exists, but somehow all these gotos are better to be rewritten to something more readable.

File: srtcore/api.cpp [hunk 13]
```diff
@@ -1579,6 +1611,21 @@ int CUDTUnited::groupConnect(CUDTGroup* pg, SRT_SOCKGROUPCONFIG* targets, int ar
...
+            if (g.m_bClosing)
+            {
+                LOGC(aclog.Error, log << "groupConnect: group deleted while connecting; breaking the process");
+
+                // Set the status as pending so that the socket is taken care of later.
+                // Note that all earlier sockets that were processed in this loop were either
+                // set BROKEN or PENDING.
+                f->sndstate = SRT_GST_PENDING;
+                f->rcvstate = SRT_GST_PENDING;
+                retval = -1;
```
Comment (maxsharabayko) [inline srtcore/api.cpp:1625]: The socket already references the group, doesn't it?
`ns->m_IncludedIter = f;` 127 lines above.

File: srtcore/group.cpp [hunk 14]
```diff
@@ -942,6 +942,7 @@ void CUDTGroup::close()
     vector<SRTSOCKET> ids;
 
     {
+        ScopedLock glob(CUDT::s_UDTUnited.m_GlobControlLock);
         ScopedLock g(m_GroupLock);
```
Comment (maxsharabayko) [inline srtcore/group.cpp:946]: Are you sure `CUDTGroup::close()` is not called with `s_UDTUnited.m_GlobControlLock` already acquired?

**Comment by maxsharabayko** [comment]
### TODO:

- [ ] Update documentation of the connection callback: now only called on failure.

File: srtcore/api.cpp (hunk 11 above)
Comment (ethouris) [reply srtcore/api.cpp:1486]: The `m_bClosing` flag is set exclusively in `CUDTGroup::close` function, and it's under `CUDTUnited::m_GlobControlLock`, just like this section. So, the `CUDTGroup::close` if is attempted to be executed at the moment when this section is executed, it will have to wait until this socket is added to the group and the section left. It might then happen that THIS socket will be added to the group, but the NEXT ONE will find out that this group is being closed, but then the whole loop will be interrupted.

File: srtcore/api.cpp (hunk 12 above)
Comment (ethouris) [reply srtcore/api.cpp:689]: Will be. Not of course that goto in C++ still honors all required destructors, so it's not that dangerous if you use scoped tools.

File: srtcore/api.cpp (hunk 13 above)
Comment (ethouris) [reply srtcore/api.cpp:1626]: Yes, but there were mutexes unlocked in the meantime and this could have changed. Prolonged use of `f` here has caused a crash in one test.

File: srtcore/group.cpp (hunk 14 above)
Comment (ethouris) [reply srtcore/group.cpp:946]: No. This part is executed directly from the API functions and no locks are applied yet:
```
    if (u & SRTGROUP_MASK)
    {
        GroupKeeper k (*this, u, ERH_THROW);
        k.group->close();
        deleteGroup(k.group);
        return 0;
    }
```
And this `k.group->close()` is then called with no locks. Note that `GroupKeeper` only applies locks to access the group to mark the busy flag, but during "its section" all locks are released.

**Comment by ethouris** [comment]
As per: Data race acessing `m_iTsbPdDelay_ms`

I think this shouldn't be a problem because `makeMePeerOf` is a function executed exclusively on the listener side, while `groupConnect` happens on the caller side. Groups also cannot involve both connecting and accepted sockets. This procedure of setting the latency is also executed exclusively on sockets that are newly being connected and borrow the value from a socket that is already connected.

File: srtcore/core.cpp (hunk 1 above)
Comment (maxsharabayko) [reply srtcore/core.cpp]: Still topical.
Connection callback is now called in SHUTDOWN and not called anymore on a successfull connection.
Fix API-Functions.md

File: srtcore/api.cpp (hunk 12 above)
Comment (maxsharabayko) [reply srtcore/api.cpp:689]: > For a number of years I have been familiar with the observation that the quality of programmers is a decreasing function of the density of go to statements in the programs they produce. More recently I discovered why the use of the go to statement has such disastrous effects, and I became convinced that the go to statement should be abolished from all "higher level" programming languages (i.e. everything except, perhaps, plain machine Code). 

Edsger W. Dijkstra. [Letters to the editor: go to statement considered harmful](https://dl.acm.org/doi/10.1145/362929.362947)

Comment (ethouris) [reply srtcore/api.cpp:689]: I know. Just note that I wasn't actually the first to introduce this label and gotos in this function. OTOH note that goto in C++ is also under heavy restrictions and there are only extremely distinct cases when the use of it might make sense. And I believe this is the case here.
