### PR TITLE
Fixed fallback for memory allocation errors

### LINKED ISSUE #1458: [BUG] Memory leak if exception is thrown
As noted in [the comment](https://github.com/Haivision/srt/commit/c88ff8882442190d94b60aab39a9266f1c88debf#r41362141), PR #1393 did not handle the allocated resources properly if exception is thrown.

Consider function `CUDTUnited::updateMux(..)`
```c++
    m.m_pTimer = new CTimer;
    m.m_pSndQueue = new CSndQueue;
    // ..
}
catch (..)
{
    // TODO: delete m.m_pSndQueue, etc.
}
```

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #1458 

Changes:
1. All `new` expressions dragged into under `try` clause.
2. Pointers initialized to NULL to enable null-check
3. All objects that succeeded to allocate, in case when fallen into a `catch` clause, are destroyed.

### CODE REVIEW

**Comment by ethouris** [comment]
CodeFactor: ignore complex code.

File: srtcore/api.cpp [hunk 1]
```diff
@@ -2617,21 +2617,38 @@ void CUDTUnited::updateMux(
...
+{
+    // Reverse order of the assigned 
+    if (m.m_pRcvQueue)
+        delete m.m_pRcvQueue;
+
+    if (m.m_pSndQueue)
+        delete m.m_pSndQueue;
+
+    if (m.m_pTimer)
+        delete m.m_pTimer;
```
Comment (maxsharabayko) [inline srtcore/api.cpp:2643]:
```suggestion
    delete m.m_pRcvQueue;
    delete m.m_pSndQueue;
    delete m.m_pTimer;
```

Comment (ethouris) [reply srtcore/api.cpp:2643]: Actually, right.

File: srtcore/api.cpp [hunk 2]
```diff
@@ -2617,21 +2617,33 @@ void CUDTUnited::updateMux(
...
+    delete m.m_pRcvQueue;
+    delete m.m_pSndQueue;
+    delete m.m_pTimer;
+
+    if (m.m_pChannel)
+    {
+        m.m_pChannel->close();
+        delete m.m_pChannel;
+    }
+}
```
Comment (maxsharabayko) [inline srtcore/api.cpp:2645]: Why not moving this function to the destructor of `CMultiplexer`?

Comment (ethouris) [reply srtcore/api.cpp:2645]: Because destructor will be called in every place where the object is deleted, including intermediate things happening during copying the object, at least formally. You'd need also to provide a copy constructor, with possibly some kind of poor C++03 move semantics (those from the `std::auto_ptr`).

Or, in short, not worth a shot.

Comment (maxsharabayko) [reply srtcore/api.cpp:2645]: Still, this function looks more like a member of `CMultiplexer`, that a member of `CUDTUnited`.
Maybe move to `CMultiplexer::destroy()` or some similar name.

Another thought, `CMultiplexer::release()` to just set pointers to NULL without delete, and `~CMultiplexer()` destructor.

Comment (ethouris) [reply srtcore/api.cpp:2645]: I'd still leave the destructor behind, as it wouldn't be a good idea to let it run at the destruction time - but the idea to make this function a special method of `CMultiplexer` is very good.
