### PR TITLE
[core] Fixed updating new RCV buffer on ISN change.

### LINKED ISSUE #2306: [BUG] getAvailRcvBufferSizeNoLock() reports a negative value causing srt-live-transmit to shut down an otherwise healthy connection
**Describe the bug**
I'm working on writing a TS transmitter using SRT library. I only have one function that actually calls `srt_send()` and I use this function regardless of whether the connection was established in listener mode, caller mode or rendezvous. Caller & listener mode works well, however, when the connection has been established using rendezvous mode, I get this output on the `srt-live-transmit` application that attempts to receive the TS:

```
./srt-live-transmit srt://10.0.28.232:8888?mode=rendezvous udp://10.0.28.232:9999
Media path: 'srt://10.0.28.232:8888?mode=rendezvous' --> 'udp://10.0.28.232:9999'
12:59:58.115288/SRT:RcvQ:w1*E:SRT.cn: cookieContest: agent=-705126473 peer=101587914
12:59:58.119616/SRT:RcvQ:w1*E:SRT.qr: @1013203658:SEQUENCE DISCREPANCY. BREAKING CONNECTION. seq=1518897272 buffer=(1518897272:1518897271+1518905462), 1027654368 past max. Reception no longer possible. REQUESTING TO CLOSE.
```

**Some clues from our friend gdb**
Preliminary debugging
It appears that it is possible for the receive buffer to report that it's available size is negative.
This may prove to be a good starting point to investigate this bug.

**What goes over the wire?**
Wireshark
Sometimes there are more than one packet sent before the receiving application (`srt-live-transmit`) shuts down the connection, but usually far less than 10, and always >=1. _Note that this capture is not from the same execution as the output pasted above._

**To Reproduce**
This may prove very difficult as I'd have to give you my code for the transmitter.
However, I have followed the examples in the documentation to setup a rendezvous connection and simply
used srt_send() to transmit over that connection once established. 

**Expected behavior**
Expected behavior would be `srt-live-transmit` not shutting down the connection due to a "sequence discrepancy" and continuing reception of data as normal.

**Workaround**
I have found a simple work-around for this issue, which is to disable the use of the so-called "new" receiver buffer and compiling
SRT with the "old" implementation of the receiver buffer. I did this by adding the following line to `CMakeLists.txt`:
 `set (ENABLE_NEW_RCVBUFFER OFF)`

**Transmitting machine details**
 ```[root@btech ~]# neofetch
        #####           root@btech 
       #######          ---------- 
       ##O#O##          OS: x86_64 
       #######          Host: VirtualBox 1.2 
     ###########        Kernel: 3.10.0-1160.el7.x86_64 
    #############       Uptime: 10 days, 5 hours, 28 mins 
   ###############      Packages: 523 (rpm) 
   ################     Shell: bash 4.2.46 
  #################     Terminal: /dev/pts/1 
#####################   CPU: Intel i7-7820X (8) @ 3.599GHz 
#####################   GPU: VirtualBox Graphics Adapter 
  #################     Memory: 8409MiB / 15884MiB
  ```
SRT Version 1.4.4

**Receiving machine details**
```                 ..
               .PLTJ.
              <><><><>
     KKSSV' 4KKK LJ KKKL.'VSSKK        terjegun@localhost.localdomain 
     KKV' 4KKKKK LJ KKKKAL 'VKK        ------------------------------ 
     V' ' 'VKKKK LJ KKKKV' ' 'V        OS: CentOS Linux 7 (Core) x86_64 
     .4MA.' 'VKK LJ KKV' '.4Mb.        Host: VirtualBox 1.2 
   . KKKKKA.' 'V LJ V' '.4KKKKK .      Kernel: 3.10.0-1160.59.1.el7.x86_64 
 .4D KKKKKKKA.'' LJ ''.4KKKKKKK FA.    Uptime: 5 hours, 39 mins 
<QDD ++++++++++++  ++++++++++++ GFD>   Packages: 2138 (rpm), 1 (pkg) 
 'VD KKKKKKKK'.. LJ ..'KKKKKKKK FV     Shell: bash 4.2.46 
   ' VKKKKK'. .4 LJ K. .'KKKKKV '      Terminal: /dev/pts/0 
      'VK'. .4KK LJ KKA. .'KV'         CPU: Intel i7-7820X (8) @ 3.599GHz 
     A. . .4KKKK LJ KKKKA. . .4        GPU: 00:02.0 VMware SVGA II Adapter 
     KKA. 'KKKKK LJ KKKKK' .4KK        Memory: 3761MiB / 23379MiB 
     KKSSA. VKKK LJ KKKV .4SSKK
              <><><><>                                         
               'MKKM'                                          
                 ''
```
SRT Version 1.4.4

Both receiving and transmitting machines are virtual machines hosted on the same hardware.

### PR DESCRIPTION
**Pull request by maxsharabayko**
The new receiver buffer keeps track of the packet sequence number in the starting position to be independent from SRT receiver ACK position.
As the receiver buffer is created **before** the connection is actually being established (see #2268), the starting sequence number has to be updated afterward.
- In particular, in the rendezvous connection mode both parties come with its own ISN. The negotiated ISN is the one from the party that has become INITIATOR after the cookie contest. The ISN has to be updated. Fixes #2306.
- Another source of the update is group connections, each having its own receiver buffer, that has to be synchronized at the start (and already after an individual connection has been established).

This PR adds an update of the RCV buffer's starting seqno.

### CODE REVIEW

File: srtcore/buffer_rcv.cpp [hunk 1]
```diff
@@ -200,6 +200,27 @@ int CRcvBufferNew::dropUpTo(int32_t seqno)
     return iDropCnt;
 }
 
+int CRcvBufferNew::dropAll()
```
Comment (gou4shi1) [inline srtcore/buffer_rcv.cpp:203]: Why not just call `dropUpTo(m_iStartSeqNo+m_iMaxPosInc)`? So that something likes `m_numOutOfOrderPackets`, `m_iFirstReadableOutOfOrder` would also be updated.

Comment (gou4shi1) [reply srtcore/buffer_rcv.cpp:203]: OK, updated now.

Comment (maxsharabayko) [reply srtcore/buffer_rcv.cpp:203]: Then we need to know up to what seqno to drop. We can't drop up to the new ISN, because it can be anywhere relative to the current RCV buffer starting position.

Comment (gou4shi1) [reply srtcore/buffer_rcv.cpp:203]: You are right.

Comment (maxsharabayko) [reply srtcore/buffer_rcv.cpp:203]: Although it might make sense to define the end position within the `dropAll()` function, and then call `dropUpTo(m_iStartSeqNo+m_iMaxPosInc)`, like you suggested. 🤔

**Comment by maxsharabayko** [comment]
✔️  Tested with main/backup and broadcast groups. No issues.
✔️  Tested with rendezvous connection. No issues.

File: srtcore/buffer_rcv.h [hunk 2]
```diff
@@ -73,6 +73,10 @@ class CRcvBufferNew
     ///
     int dropUpTo(int32_t seqno);
 
+    /// @brief Drop all the packets in the receiver buffer. The starting position.
```
Comment (gou4shi1) [inline srtcore/buffer_rcv.h:76]:
```suggestion
    /// @brief Drop all the packets in the receiver buffer.
```

File: srtcore/buffer_rcv.cpp [hunk 3]
```diff
@@ -200,6 +200,15 @@ int CRcvBufferNew::dropUpTo(int32_t seqno)
...
+{
+    if (empty())
+        return 0;
+
+    const int end_pos = incPos(m_iStartPos, m_iMaxPosInc);
+    return dropUpTo(end_pos);
```
[the remark this answers is not in the document]
Comment (maxsharabayko) [reply srtcore/buffer_rcv.cpp]: Argh! Thank you for noticing!

**Review by gou4shi1 — APPROVED** [review]
