### PR TITLE
[core] Fix some warnings when compiling with mingw

### LINKED ISSUE #2862: Build warnings on minGW
SRT latest master, v1.5.3 (with some differences)
MinGW build in Travis produces warnings worth fixing.

E.g. https://app.travis-ci.com/github/Haivision/srt/jobs/616548006
```shell
[ 21%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/channel.cpp.obj
In file included from /home/travis/build/Haivision/srt/srtcore/udt.h:70:0,
                 from /home/travis/build/Haivision/srt/srtcore/channel.h:63,
                 from /home/travis/build/Haivision/srt/srtcore/channel.cpp:60:
/home/travis/build/Haivision/srt/srtcore/srt.h:52:0: warning: "SRT_API" redefined
          #define SRT_API __declspec(dllexport)
 ^
In file included from /home/travis/build/Haivision/srt/srtcore/channel.cpp:57:0:
/home/travis/build/Haivision/srt/srtcore/srt_compat.h:36:0: note: this is the location of the previous definition
       #define SRT_API
 ^
/home/travis/build/Haivision/srt/srtcore/channel.cpp: In member function 'void srt::CChannel::createSocket(int)':
/home/travis/build/Haivision/srt/srtcore/channel.cpp:179:10: warning: variable 'cloexec_flag' set but not used [-Wunused-but-set-variable]
     bool cloexec_flag = false;
          ^
/home/travis/build/Haivision/srt/srtcore/channel.cpp: In member function 'int srt::CChannel::sendto(const srt::sockaddr_any&, srt::CPacket&, const srt::sockaddr_any&) const':
/home/travis/build/Haivision/srt/srtcore/channel.cpp:799:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (res == WAIT_FAILED)
                     ^
[ 23%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/common.cpp.obj
[ 25%] Building CXX object CMakeFiles/srtsupport_virtual.dir/apps/uriparser.cpp.obj
[ 26%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/core.cpp.obj
[ 28%] Building CXX object CMakeFiles/srtsupport_virtual.dir/apps/verbose.cpp.obj
[ 28%] Built target srtsupport_virtual
[ 30%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/crypto.cpp.obj
[ 32%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/epoll.cpp.obj
/home/travis/build/Haivision/srt/srtcore/epoll.cpp:284:2: warning: #warning "Unsupported system for epoll. The epoll_add_ssock() API call won't work on this platform." [-Wcpp]
 #warning "Unsupported system for epoll. The epoll_add_ssock() API call won't work on this platform."
  ^
[ 33%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/fec.cpp.obj
```

### PR DESCRIPTION
**Pull request by yomnes0**
fixes #2862
Removed duplicate declaration of SRT_API
Moved around variables to avoid set but not used warnings

### CODE REVIEW

File: srtcore/channel.cpp [hunk 1]
```diff
@@ -795,8 +797,9 @@ int srt::CChannel::sendto(const sockaddr_any& addr, CPacket& packet, const socka
     {
         if (NET_ERROR == WSA_IO_PENDING)
         {
-            res = WSAWaitForMultipleEvents(1, &m_SendOverlapped.hEvent, TRUE, 100 /*ms*/, FALSE);
-            if (res == WAIT_FAILED)
+            DWORD res_wait = 0;
+            res_wait = WSAWaitForMultipleEvents(1, &m_SendOverlapped.hEvent, TRUE, 100 /*ms*/, FALSE);
```
Comment (maxsharabayko) [inline srtcore/channel.cpp:801]:
```suggestion
            DWORD res_wait = WSAWaitForMultipleEvents(1, &m_SendOverlapped.hEvent, TRUE, 100 /*ms*/, FALSE);
```

File: srtcore/srt.h [hunk 2]
```diff
@@ -33,7 +33,7 @@ written by
 //if compiling with MinGW, it only works on XP or above
 //use -D_WIN32_WINNT=0x0501
 
-
+#ifndef SRT_API
```
Comment (ethouris) [inline srtcore/srt.h:36]: I think this whole part should be removed from this file and put into `platform_sys.h` file where it belongs.

The definition of `SRT_API` should still stay in this file, but then this symbol shall not be used anywhere else in the SRT code than this exactly file.

File: srtcore/srt_compat.c [hunk 3]
```diff
@@ -17,7 +17,7 @@ written by
 // Prevents from misconfiguration through preprocessor.
 
 #include "platform_sys.h"
-
+#include <srt.h>
```
Comment (maxsharabayko) [inline srtcore/srt_compat.c:20]: Why is `srt.h` needed in this file?

File: srtcore/srt_compat.h [hunk 4]
```diff
@@ -20,49 +20,6 @@ written by
...
-   // http://www.gnu.org/software/libc/manual/html_node/Integer-Conversions.html
-   // printf() Format for ssize_t
-   #if !defined(PRIzd)
-      #define PRIzd "zd"
-   #endif
-   // printf() Format for size_t
-   #if !defined(PRIzu)
-      #define PRIzu "zu"
-   #endif
-#endif
```
Comment (maxsharabayko) [inline srtcore/srt_compat.h:63]: These are removed. Not sure if `PRIzd` and `PRIzu` are needed anywhere though.
@jlsantiago0 you added them in PR #336 almost six years ago. Do you happen to know/remember why?

Comment (ethouris) [reply srtcore/srt_compat.h:63]: About 3 years ago I took the effort of a complete removal of any printf-formatting things from SRT. This PRI* stuff was one of the reasons.

They should not be needed anywhere, and if they are, they should be removed. There's also an appriate annotation at the LOGF/HLOGF macros that they are deprecated.

Comment (ethouris) [reply srtcore/srt_compat.h:63]: The printf versions weren't exactly abandoned due to performance, rather due to that printf formatting was causing problems, incompatibilities, unexpected warnings and portability issues. One of the most annoying things - and the reason why this PRI* stuff exists - was that the formatting tags in printf are tied to the builtin types only, while SRT makes wide use of types like `size_t` and `int64_t`, which's definition is platform-dependent. Only `size_t` got finally the `z` printf tag to support it, but that's also not implemented correctly in every compiler.

So everntually getting rid of the printf tag use was the most sensible choice. Performace is another matter - if you remember our last discussion about the {fmt} library, it turns out that iostreams with formatting are pretty slow (another thing is that we use specific formatting parameters rarely). Of course it would be nice to provide some better performant formatting library, but not such that would reuse the printf formatting and all its problems, and the best would be something that could be used as a drop-in replacement without changing the existing log instructions.

File: srtcore/srt_compat.c (hunk 3 above)
Comment (yomnes0) [reply srtcore/srt_compat.c:20]: SRT_API seems to be needed in srt_compat.h. I don't know why I added it in the c file instead, should I move it ?

Comment (ethouris) [reply srtcore/srt_compat.c:20]: Right, but then I doubt that `SysStrError` really requires this attribute. This is an internally used function, not a part of the SRT API. I believe it should be able to go without it, but I'd check this on all Windows builds to be sure first.

Comment (yomnes0) [reply srtcore/srt_compat.c]: All AppVeyor build for windows went fine

File: srtcore/channel.cpp [hunk 5]
```diff
@@ -51,7 +51,7 @@ modified by
 *****************************************************************************/
 
 #include "platform_sys.h"
-
+#include <srt.h>
```
Comment (maxsharabayko) [inline srtcore/channel.cpp:54]: I'm sorry I didn't see this the previous review round, but this include is likely not required as well.

Comment (yomnes0) [reply srtcore/channel.cpp]: I think I added it because of srt_compat as well, I just removed it

**Comment by yomnes0** [comment]
This include should not be there, it will be fixed soon
