### PR TITLE
Fix CRcvBuffer::countbytes()

### LINKED ISSUE #776: countBytes bad call in CRcvBuffer::getRcvReadyMsg
Hi

I am reading the SRT codes to have a better understanding. (By the way, should not there be a better/more complete documentation?)
I encountered this, which seems to be a bug:
In CRcvBuffer::getRcvReadyMsg in buffer.cpp, the number of removed pakcets/bytes are being counted inside a loop on the queue locations. Then at the end, after the loop, the statistics are being  updated according to these counters. 
But the function might be returned inside the loop. For example when after some bad packets we at last find a good packet with all the needed specs and return that packet spec. In such a case the countBytes would not be called and the statistics would drift away from what really is there in.

### PR DESCRIPTION
**Pull request by maxlovic**
Fixes #776.
In `CRcvBuffer::getRcvReadyMsg`, the number of removed packets/bytes is counted inside the loop. After the loop, the countBytes() is called. But the function might return inside the loo, thus not calling `countBytes()`.

Fixes partially #836 issue 1
`countBytes()` is called for the part of the packet actually read, not the real size. Furthermore, if there is no more space in the buffer, the reading will continue, but a call to countBytes() will be skipped.

and TSBPD log messages from TODO list.

### CODE REVIEW

File: srtcore/buffer.cpp [hunk 1]
```diff
@@ -1590,12 +1588,15 @@ int CRcvBuffer::readMsg(char* data, int len, ref_t<SRT_MSGCTRL> r_msgctl)
...
-        if ((rs >= 0) && (unitsize > rs))
-            unitsize = rs;
+        const int pktlen = (int)m_pUnit[p]->m_Packet.getLength();
+        if (pktlen > 0)
+            countBytes(-1, -pktlen, true);
+
+        const int unitsize = ((rs >= 0) && (unitsize > rs)) ? rs : pktlen;
 
         if (unitsize > 0)
         {
```
Comment (ethouris) [inline srtcore/buffer.cpp]: What will then happen in the line below, if the memory assigned to `data` are of less size than `pktlen` and the value passed as `len` to `readData` is -1? And if we don't predict it be -1, why is then `rs >= 0` checked?

I know that it wasn't subject of this PR, but it looks weird. The condition should prevent `memcpy` to be called with a size that exceeds the allocated memory.
