### PR TITLE
Fixed bug in fixing seq on activation in rel mode

### LINKED ISSUE #1345: [BUG] Group sequence discrepancy fixed wrong way
The bug is not reproducible and the only trace is contained in the following log:

```
15:54:00.228953/srt-test-live D:SRT.c: generateSocketID: : @84249295
15:54:00.355759/srt-test-live*E:SRT.d: grp/sendBackup: IPE: another running link seq discrepancy: %1396666984 vs. previous %1396780200 - fixing
15:54:00.356814/srt-test-live*E:SRT.d: grp/sendBackup: IPE: another running link seq discrepancy: %1396780200 vs. previous %1396780201 - fixing
15:54:00.356870/srt-test-live*E:SRT.c: IPE: Overridding seq %1396780201 DISCREPANCY against current next sched %1396780201
15:54:00.357921/srt-test-live*E:SRT.d: grp/sendBackup: IPE: another running link seq discrepancy: %1396780201 vs. previous %1396780202 - fixing
15:54:00.357949/srt-test-live*E:SRT.c: IPE: Overridding seq %1396780202 DISCREPANCY against current next sched %1396780202
15:54:00.359368/srt-test-live*E:SRT.d: grp/sendBackup: IPE: another running link seq discrepancy: %1396780202 vs. previous %1396780203 - fixing
15:54:00.359442/srt-test-live*E:SRT.c: IPE: Overridding seq %1396780203 DISCREPANCY against current next sched %1396780203
15:54:00.359972/srt-test-live*E:SRT.d: grp/sendBackup: IPE: another running link seq discrepancy: %1396780203 vs. previous %1396780204 - fixing
```

Then it continues according to the model from the 4th line.

The problem is caught in this line and it is believed that the problem once detected is tried to be fixed, but the fix is likely wrong:

```
        if (w_curseq == SRT_SEQNO_NONE)
        {
            w_curseq = pktseq;
        }
        else if (w_curseq != lastseq)
        {
            // We believe that all running links use the same seq.
            // But we can do some sanity check.
            LOGC(dlog.Error, log << "grp/sendBackup: IPE: another running link seq discrepancy: %" << lastseq
                    << " vs. previous %" << w_curseq << " - fixing");
            w_u.overrideSndSeqNo(w_curseq);
        }
```

where `lastseq` is the sequence that was supposed to be next to be stamped on the sent packet, but known at the time BEFORE the sending happened, while this location is executed after the sending happened, so `lastseq` is expected to be equal to `w_curseq`. `pktseq` is the sequence that WAS set on the packet that was sent in the last sending function. `w_curseq` refers to a variable that is lazily initialized from the first socket used for sending, so if it's not -1, then likely the previous loop iteration has set the value here. So this was executed in at least second iteration of the loop, that is, second socket in the group.

The log doesn't provide information as to which socket was struck by the problem and on which it got fixed. Unknown is both why the first IPE problem has happened, as well as why the call to `overrideSndSeqNo` has caused that the sequence didn't pass the check and the fix was rejected.

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #1345

The problem: in the procedure where the sequence should be updated before dispatching collected packets from the receiver buffer, the call to `overrideSndSeqNo` was under `ENABLE_HEAVY_LOGGING` conditional.

### CODE REVIEW

File: srtcore/core.cpp [hunk 1]
```diff
@@ -14701,12 +14723,15 @@ int CUDTGroup::sendBackupRexmit(CUDT& core, SRT_MSGCTRL& w_mc)
...
             // Stop sending if one sending ended up with error
+            LOGC(dlog.Warn, log << "sendBackupRexmit: sending from buffer stopped at %"
+                    << core.schedSeqNo() << " and FAILED");
             return -1;
         }
     }
 
     // Copy the contents of the last item being updated.
     w_mc = m_SenderBuffer.back().mc;
+    LOGC(dlog.Warn, log << "sendBackupRexmit: pre-sent collected %" << curseq << " - %" << w_mc.pktseq);
```
Comment (maxsharabayko) [inline srtcore/core.cpp:14734]: Should it be a warning? Look like some heavy log.
