### PR TITLE
[core][MAINT] Removed unused and swelling m_pAcceptSockets field + refax

### LINKED ISSUE #1734: [BUG] The `CUDTSocket::m_pAcceptSockets` grows indefinitely
**Describe the bug**
The `CUDTSocket::m_pAcceptSockets` grows when accepting sockets, but the added sockets will not be deleted in most case.

**To Reproduce**
1. Run an srt server.
2. Connect it multiple times using `srt-live-transmit` and close.
3. Check the size of the `CUDTSocket::m_pAcceptSockets`.

**Expected behavior**
The `CUDTSocket::m_pAcceptSockets` should be shrinked accordingly.

**Screenshots**

**Desktop (please provide the following information):**
 - OS: Linux
 - SRT Version / commit ID: 6fa2545dd729544f2f61308b5dadf13316b65625

**Additional context**
The sockets in `CUDTSocket::m_pAcceptSockets` seems never be accessed, so can we just remove it?

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #1734 

The `m_pAcceptSocket` field seems to not be used for anything. Sockets were added to it and removed from it under some circumstances, but that's about all.

Refax: Also the `m_pQueuedSockets` field has been turned into `m_QueuedSockets` and turned into a solid object instead of pointer. There has never been any reason to make this object dynamically allocated and deallocated and it has only increased entropy.

### CODE REVIEW

File: srtcore/api.cpp [hunk 1]
```diff
@@ -1138,9 +1114,8 @@ SRTSOCKET CUDTUnited::accept(const SRTSOCKET listen, sockaddr* pw_addr, int* pw_
            //
            // Consider using std::list or std::vector here.
 
-           u = *(ls->m_pQueuedSockets->begin());
-           ls->m_pAcceptSockets->insert(ls->m_pAcceptSockets->end(), u);
-           ls->m_pQueuedSockets->erase(ls->m_pQueuedSockets->begin());
+           u = *(ls->m_QueuedSockets.begin());
+           ls->m_QueuedSockets.erase(ls->m_QueuedSockets.begin());
```
Comment (maxsharabayko) [inline srtcore/api.cpp:1118]: According to the suggrstion in comments above:
```c++
set<SRTSOCKET>::iterator b = ls->m_QueuedSockets.begin();
u = *b;
ls->m_QueuedSockets.erase(b);
```

**Review by maxsharabayko — COMMENTED** [review]
I am also voting for making `m_QueuedSockets` a `vector` instead of a set.
Only erase operation makes use of a set, but I assume the number of queued sockets is limited by a backlog value, so it is not something where such optimization is beneficial.

**Review by maxsharabayko — APPROVED** [review]
