### PR TITLE
Added fixes for failing tests

### LINKED ISSUE #1321: [BUG] Fix SyncEvent.WaitFor unit test
Fix SyncEvent.WaitFor unit test. Take into account spurious wake-ups.
C++11 test run sometimes fails because of that:
- SyncEvent.WaitFor
- SyncEvent.WaitForTwoNotifyOne

#### SyncEvent.WaitFor
Example GitHub Action output:
```shell
1: [ RUN      ] SyncEvent.WaitFor
1: SyncEvent::wait_for(50us) took 15152us
1: SyncEvent::wait_for(100us) took 15550us
1: SyncEvent::wait_for(500us) took 15458us
1: SyncEvent::wait_for(1 ms) took 15.637 ms
1: SyncEvent::wait_for(101 ms) took 109.269 ms
1: D:\a\srt\srt\test\test_sync.cpp(276): error: Value of: cond.wait_for(lock, timeout)
1:   Actual: true
1: Expected: false
1: SyncEvent::wait_for(1001 ms) took 1001.31 ms
1: [  FAILED  ] SyncEvent.WaitFor (1173 ms)
```
#### SyncEvent.WaitForTwoNotifyOne

```shell
1: [ RUN      ] SyncEvent.WaitForTwoNotifyOne
1: D:\a\srt\srt\test\test_sync.cpp(368): error: Value of: isready1 ? wait_async2_res.get() : wait_async1_res.get()
1:   Actual: true
1: Expected: false
1: [  FAILED  ] SyncEvent.WaitForTwoNotifyOne (3000 ms)
```

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #1321 

1. Decreased the number of simultaneously created connection to be quickly failed to 100. Not every platform withstood 200 and this was also the reason of test failures in CI.

2. The WaitForTwoNotifyOne test has been redesigned. The general idea is that:

* We start two threads, that is "clients".
* We expect them both to timeout in a short time, as we didn't signal them.
* Then, we apply `notify_one` on the CV on which they are both waiting.
* The thread that got the notification first, does a simulated "resource requisition", that is, it adds a value to the vector with its id. Then sets the resource availability flag to false in order to avoid a spuriously woken up thread to get advantage of it.
* The thread that reports the "ready" status is expected to also have added its id to the vector and return 42. We also require that the value returned for this thread's future is always valid.
* For the not-ready thread we are tolerant; we record -1 value for a case when the value isn't valid, and both valid 0 and invalid -1 are acceptable values.
* The not-ready thread is expected to report timeout and not return 42.

Note that the "resource requisition" is done under the mutex lock, which means that the really getting notified one should behave correctly. The other client is expected to either not get any notification at all and therefore exit on timeout, or getting a spurious notification, in which case it will see the resource already acquired.

### CODE REVIEW

File: test/test_sync.cpp [hunk 1]
```diff
@@ -275,14 +275,21 @@ TEST(SyncEvent, WaitFor)
...
         const bool on_timeout = !cond.wait_for(lock, timeout);
         const steady_clock::time_point stop = steady_clock::now();
+        const steady_clock::duration waittime = stop - start;
 #if defined(ENABLE_STDCXX_SYNC) || !defined(_WIN32)
         // This check somehow fails on AppVeyor Windows VM with VS 2015 and pthreads.
         // - SyncEvent::wait_for( 50us) took 6us
         // - SyncEvent::wait_for(100us) took 4us
         if (on_timeout) {
-            EXPECT_GE(count_microseconds(stop - start), tout_us);
+            EXPECT_GE(waittime, timeout);
```
Comment (maxsharabayko) [inline test/test_sync.cpp:284]: I suppose `tout_us` was used here instead of `duration` because GTest was not formatting the duration properly.
An error message can be added then.
```suggestion
            EXPECT_GE(waittime, timeout); << Expected << tout_us << waited << count_microseconds(waittime);
```

Comment (maxsharabayko) [reply test/test_sync.cpp:284]: The problem with this condition is that even this condition sometimes fails.

Comment (ethouris) [reply test/test_sync.cpp:284]: I haven't seen any fail here outside the conditionals. Is that too little tolerance, or there's no guarantee at all?

File: test/test_sync.cpp [hunk 2]
```diff
@@ -348,35 +356,105 @@ TEST(SyncEvent, WaitForTwoNotifyOne)
...
+    volatile bool resource_ready = true;
+
+    auto wait_async = [&notified_clients, &resource_ready](Condition* cond, Mutex* mutex, const steady_clock::duration& timeout, int id) {
         UniqueLock lock(*mutex);
-        return cond->wait_for(lock, timeout);
+        if (cond->wait_for(lock, timeout) && resource_ready)
+        {
+            notified_clients.push_back(id);
+            resource_ready = false;
+            return 42;
```
Comment (maxsharabayko) [inline test/test_sync.cpp:371]: Return `true` or `1`.

```suggestion
            return true;
```

File: test/test_sync.cpp [hunk 3]
```diff
@@ -348,35 +356,105 @@ TEST(SyncEvent, WaitForTwoNotifyOne)
...
+        }
+        return 0;
```
Comment (maxsharabayko) [inline test/test_sync.cpp:373]:
```suggestion
        return false;
```

File: test/test_sync.cpp [hunk 4]
```diff
@@ -348,35 +356,105 @@ TEST(SyncEvent, WaitForTwoNotifyOne)
...
+    for (auto& nof: notified_clients)
+        cerr << " " << nof;
+    cerr << endl;
+
+    // Now exactly one waiting thread should become ready
+    // Error if: 0 (none ready) or 2 (both ready, while notify_one was used)
+    ASSERT_EQ(notified_clients.size(), 1);
+
+    int ready = notified_clients[0];
+    int not_ready = (ready + 1) % 2;
```
Comment (maxsharabayko) [inline test/test_sync.cpp:411]:
```suggestion
    const int ready = notified_clients[0];
    const int not_ready = (ready + 1) % 2;
```

File: test/test_sync.cpp [hunk 5]
```diff
@@ -348,35 +356,105 @@ TEST(SyncEvent, WaitForTwoNotifyOne)
...
+    // The one that got the signal, should exit ready.
+    // The one that didn't get the signal, should exit timeout.
+    EXPECT_EQ(wait_state[ready], future_status::ready);
+    EXPECT_EQ(wait_state[not_ready], future_status::timeout);
+
+    // Same, expect these future to return the value
+    // TURNED OFF for Windows, as there happens to be a
+    // "spurious" signal causing this condition to fail,
+    // even though it is declared valid and timed out.
+    EXPECT_EQ(future_val[ready], 42);
```
Comment (maxsharabayko) [inline test/test_sync.cpp:455]: true or 1

```suggestion
    EXPECT_EQ(future_val[ready], true);
```

**Review by maxsharabayko — APPROVED** [review]
