### PR TITLE
Fixing a member (m_nHeader) being referenced before initialized

### LINKED ISSUE #2400: [BUG] Static Sanitizer Error
Testing with Master, reported by Static Sanitizer GCC-12.1.0.

In `‘srt::CPacket::CPacket()’`: constructor. value in `m_nHeader[SRT_PH_SEQNO]` is referenced before it is set.

```
/mnt/share/open/toolchain/gcc12/tesu/ub16-32/srt/srtcore/packet.cpp: In constructor ‘srt::CPacket::CPacket()’:
/mnt/share/open/toolchain/gcc12/tesu/ub16-32/srt/srtcore/packet.cpp:180:25: warning: member ‘srt::CPacket::m_nHeader’ is used uninitialized [-Wuninitialized]
  180 |     m_iSeqNo((int32_t&)(m_nHeader[SRT_PH_SEQNO])),
```

### PR DESCRIPTION
**Pull request by maxsharabayko**
Fixed a member (`m_nHeader`) being referenced before initialized. Fixes #2400.

### Status

Seems to help when compiled with `-Werror` and GCC 12 ([see this comment](https://github.com/Haivision/srt/pull/2433#issuecomment-1335447580)).
`(int32_t&) m_nHeader[SRT_PH_SEQNO]` is still a problem. Even though `m_nHeader[SRT_PH_SEQNO]` is a valid address, dereferencing it worries the sanitizer because the value itself is not initialized.

It is not an error in this case but would be nice to have it resolved.

### CODE REVIEW

File: srtcore/packet.h [hunk 1]
```diff
@@ -115,32 +115,28 @@ class IOVector
...
         iov_len = length;
 #endif
     }
 };
 
-
 /// To define packets in order in the buffer. This is public due to being used in buffer.
 enum PacketBoundary
 {
     PB_SUBSEQUENT = 0, // 00
```
Comment (ethouris) [inline srtcore/packet.h:128]: By this cleanup you could also add some comment here. For example: packet between the first and last packet of a message.

**Comment by jlsantiago0** [comment]
Hi @maxsharabayko Per your request, I tested SRT master branch and this branch IRT Issue #2400  . The Sanitizer error is the same in both cases:

```
[ 29%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/packet.cpp.o
/mnt/share/open/srt/srt/srtcore/packet.cpp: In constructor ?srt::CPacket::CPacket()?:
/mnt/share/open/srt/srt/srtcore/packet.cpp:180:25: warning: member ?srt::CPacket::m_nHeader? is used uninitialized [-Wuninitialized]
  180 |     m_iSeqNo((int32_t&)(m_nHeader[SRT_PH_SEQNO])),
      |                         ^~~~~~~~~
```

**Comment by jlsantiago0** [comment]
NOTE: This reads from a memory address that has not been set. It is not too much of a problem, unless this memory location happens to reside on certain in a virtual page frame that has not been mapped to a physical page frame, then it can segfault. This can happen when for instance a new page frame is created, but has never been written too. Reading from a memory address there can segfault. Either way it is undefined behavior.

Perhaps m_iSeqNo could be set to NULL here and then m_nHeader could be initialized in the constructor body and then the m_iSeqNo could be set afterwards?

**Comment by ethouris** [comment]
This is because the `m_nHeader[SRT_PH_SEQNO]` is indeed not initialized. But I don't understand why the sanitizer sees a problem there, while it's not the value, but the reference (through the pointer) being initialized here, so the initialization status of `m_nHeader[SRT_PH_SEQNO]` shouldn't matter. It should matter when someone is trying to read the `m_iSeqNo` field.

OTOH I frankly never liked these reference fields. I have once tried to refax them to turn these names into methods returning ad-hoc references to these fields (or, this time, by using the PROPERTIES through `SRTU_PROPERTY_RW` macro).

**Comment by ethouris** [comment]
> Perhaps m_iSeqNo could be set to NULL here and then m_nHeader could be initialized in the constructor body and then the m_iSeqNo could be set afterwards?

No because it's a reference. References can't be set to NULL, and tricks to do it are even more dangerous.

**Comment by jlsantiago0** [comment]
> > Perhaps m_iSeqNo could be set to NULL here and then m_nHeader could be initialized in the constructor body and then the m_iSeqNo could be set afterwards?
> 
> No because it's a reference. References can't be set to NULL, and tricks to do it are even more dangerous.

I think you can use the default constructor of m_iSeqNo and then assign it in the body. You can reassign references. This should be fine as long as you dont try to use the reference until you have assigned it to a valid object.

**Comment by maxsharabayko** [comment]
Hmm, this PR actually helps to resolve the issue on GCC 12.0.1.

#### Configure

```shell
cmake .. -DENABLE_CODE_COVERAGE=ON -DENABLE_BONDING=ON -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_BUILD_TYPE=Debug
```

#### Build (Before the Fix)

```shell
[ 27%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/packet.cpp.o
/mnt/d/Projects/srt/srt-max/srtcore/packet.cpp: In constructor ‘srt::CPacket::CPacket()’:
/mnt/d/Projects/srt/srt-max/srtcore/packet.cpp:181:27: error: member ‘srt::CPacket::m_nHeader’ is used uninitialized [-Werror=uninitialized]
  181 |     , m_iSeqNo((int32_t&)(m_nHeader[SRT_PH_SEQNO]))
      |                           ^~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/srt_virtual.dir/build.make:300: CMakeFiles/srt_virtual.dir/srtcore/packet.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/srt_virtual.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### After the Fix

All built successfully.

**Comment by ethouris** [comment]
This is only a formal compiler shut-up. The thing taken from these uninitialized fields is their reference, which remains the same after initialization. Moreover, this type doesn't feature an explicit constructor that would initialize the internal array field, which means that it is "default initialized" (not default-constructed), i. e. left with garbage. This is cleared in the call of `clear()` method, which is called later in this constructor, but it happens already after the reference was taken. Only becaue this type contains methods, it can't be treated as POD, which means that it is not treated as initialized if there was no constructor call. This is actually a bit strange because such a type already has a constructor (the default one) and as the field is defined earlier than the reference fields, the compiler should have called this constructor automatically, as this field provides a (generated, but still) default constructor.

At least this initialization entry deserves some comment that explains this in short.
