### PR TITLE
[BUG] Data race when TLPKTDROP while checking loss for ACK candidate

### LINKED ISSUE #1662: [BUG] srt-live-transmit sender stuck, repeatedly
**Describe the bug**
We are running srt-live-transmit in PULL mode and have a customer connecting to a password protected stream. The past 2 weeks we have been plagued by disconnects and the inability of our customer to reconnect (or at least receive data).

This is then only resolved by us restarting the srt-live-transmit application

The following logmessage at the start of the loss period suggests this is triggered by a ack pkt with a sequence number of -1
` 17:36:41.963749/SRT:RcvQ:w1*E:SRT.gg: @352733066:ATTACK/IPE: incoming ack seq -1 exceeds current 1863400545 by 284083101!`
The code for that logmessage can be found from line 8145 in srtcore/core.cpp.

**To Reproduce**
-setup a password protected srt-live-transmit in listening mode that sends an mpegts stream
-connect to it (customer srt: "haivision srt 1.4")
-mix in invalid seq's in the ackstream (assuming this is the cause)
-see the srt connection breakdown

**Expected behavior**
Invalid sequence data should not destroy a srt session in such a way that a restart of the sending application is required.

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #1662 

The problem is that the check for empty Receiver Loss List was done without locking, so potentially the loss list could be purged between the check and getting the contents. This way the getFirstLoss function might potentially return SRT_SEQNO_NONE (-1) and then take this value further down the processing path without checking.

### CODE REVIEW

File: srtcore/core.cpp [hunk 1]
```diff
@@ -8059,21 +8059,27 @@ int CUDT::sendCtrlAck(CPacket& ctrlpkt, int size)
...
-#endif
-    }
-    else
     {
+        // If there is no loss, the ACK is the current largest sequence number plus 1;
+        // Otherwise it is the smallest sequence number in the receiver loss list.
         ScopedLock lock(m_RcvLossLock);
         ack = m_pRcvLossList->getFirstLostSeq();
+
+        // We don't need to check the length prematurely,
```
Comment (maxsharabayko) [inline srtcore/core.cpp:8068]: Consider reducing the scope of lock to the target function `getFirstLostSeq()` only, thus also removing extra nested code block, although gaining one more operation line.

```suggestion
        // If there is no loss, the ACK is the current largest sequence number plus 1;
        // Otherwise it is the smallest sequence number in the receiver loss list.
        enterCS(m_RcvLossLock);
        ack = m_pRcvLossList->getFirstLostSeq();
        leaveCS(m_RcvLossLock);

        // We don't need to check the length prematurely,
```

File: srtcore/core.cpp [hunk 2]
```diff
@@ -8056,25 +8056,23 @@ int CUDT::sendCtrlAck(CPacket& ctrlpkt, int size)
 
     local_prevack = m_iDebugPrevLastAck;
 
-    string reason; // just for "a reason" of giving particular % for ACK
+    string reason = "first lost"; // just for "a reason" of giving particular % for ACK
```
Comment (maxsharabayko) [inline srtcore/core.cpp:8059]:
```suggestion
    IF_HEAVY_LOGGING(string reason = "first lost"); // just for "a reason" of giving particular % for ACK
```

**Review by maxsharabayko — APPROVED** [review]
