### PR TITLE
Fixed error reporting on connect/accept.

### LINKED ISSUE #1242: [BUG] Clean up rules of error reports in srt_accept
The documentation states about the errors reported by `srt_accept`:

  * `SRT_EINVSOCK`: `lsn` designates no valid socket ID. Can also mean Internal
Error when an error occurred while creating an accepted socket (**BUG?**)
  * `SRT_ENOLISTEN`: `lsn` is not set up as a listener (`srt_listen` not called,
or the listener socket has already been closed)
  * `SRT_ERDVNOSERV`: Internal error (if no `SRT_ENOLISTEN` reported, it means
that the socket could not be set up as rendezvous because `srt_listen` does
not allow it)

The following things need fixing here:

1. The behavior designated as (**BUG?**) should be cleaned up. So far there are no known errors to be reported from `srt_accept` that could result from the internal behavior with all settings correct (that is, existing listener socket, configured as listener, and correct rest of arguments).

2. The description for `SRT_ENOLISTEN` states that the socket could have been closed. This is either a lie or something wrong in the implementation, as the nonexistent socket should result in `SRT_EINVSOCK`.

3. The `SRT_ERDVNOSERV` error should not happen, although it depends from which part it might be reported. Nonetheless, if this is internal error, it should be notified by the IPE error log, but the user should get a clearly designated error. In particular, if `srt_listen` has allowed this socket, it means that this error shouldn't have occurred. So, if it happens, it should be reported by IPE error log, but the error code returned should still be `SRT_ENOLISTEN`.

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #1242

### CODE REVIEW

File: srtcore/srt.h [hunk 1]
```diff
@@ -439,12 +439,14 @@ enum CodeMinor
...
     MN_NORES           =  3,
     MN_SECURITY        =  4,
+    MN_CLOSED          =  5,
     // MJ_CONNECTION
     MN_CONNLOST        =  1,
     MN_NOCONN          =  2,
     // MJ_SYSTEMRES
     MN_THREAD          =  1,
     MN_MEMORY          =  2,
+    MN_OBJECT          =  3,
```
[the remark this answers is not in the document]
Comment (ethouris) [reply srtcore/srt.h:449]: There's another PR that is going to fix problems around the unreported errors from the Mutex/CV creation functions. There are these errors reported. Passing it here might spare too much noise in that PR.

File: docs/API-functions.md [hunk 2]
```diff
@@ -1614,6 +1618,284 @@ is not availble - it then sets the value to `SRT_REJC_PREDEFINED + 404`.
...
+`srt_getlasterror` function. The values for the error are collected in an
+`SRT_ERRNO` enum:
+
+#### `SRT_EUNKNOWN`
+
+Internal error when setting the right error code.
+
+#### `SRT_SUCCESS`
+
+The value set in case when the last error was cleared and no error occurred lately.
```
Comment (stevomatthews) [inline docs/API-functions.md:1636]:
```suggestion
The value set when the last error was cleared and no error has occurred since then.
```

File: docs/API-functions.md [hunk 3]
```diff
@@ -1614,6 +1618,284 @@ is not availble - it then sets the value to `SRT_REJC_PREDEFINED + 404`.
...
+
+#### `SRT_ECONNSETUP`
+
+General setup error resulting from internal system state.
+
+#### `SRT_ENOSERVER`
+
+Connection timed out, while attempting to connect to the remote address. Note
+that when it happens, the `srt_getrejectreason` also reports the timeout reason.
```
Comment (stevomatthews) [inline docs/API-functions.md:1645]:
```suggestion
Connection timed out while attempting to connect to the remote address. Note
that when this happens, `srt_getrejectreason` also reports the timeout reason.
```

File: docs/API-functions.md [hunk 4]
```diff
@@ -1614,6 +1618,284 @@ is not availble - it then sets the value to `SRT_REJC_PREDEFINED + 404`.
...
+#### `SRT_ESCLOSED`
+
+A socket that was vital for the operation called in the blocking mode
+has been closed during the operation. Please note that this situation is
+handled differently than the system calls for `connect` and `accept`
+functions for TCP, which in case, when the key socket was closed during
+the operation, simply block indefinitely or until the standard
+timeout. When this error is reported, it usually means that the socket
+passed as the first parameter to `srt_connect*` or `srt_accept` is no
+longer usable.
```
Comment (stevomatthews) [inline docs/API-functions.md:1672]:
```suggestion
A socket that was vital for an operation called in blocking mode
has been closed during the operation. Please note that this situation is
handled differently than the system calls for `connect` and `accept`
functions for TCP, which simply block indefinitely (or until the standard
timeout) when the key socket was closed during an operation. When this 
error is reported, it usually means that the socket passed as the first 
parameter to `srt_connect*` or `srt_accept` is no longer usable.
```

File: docs/API-functions.md [hunk 5]
```diff
@@ -1614,6 +1618,284 @@ is not availble - it then sets the value to `SRT_REJC_PREDEFINED + 404`.
...
+#### `SRT_ECONNLOST`
+
+The socket was properly connected, but the connection has been broken.
+This specialzation is reported from the transmission functions.
+
+#### `SRT_ENOCONN`
+
+The socket is not connected. This can be reported also when when the
+connection was broken for a function that checks some characteristic
+socket data.
```
Comment (stevomatthews) [inline docs/API-functions.md:1688]:
```suggestion
The socket is not connected. This can be reported also when the
connection was broken for a function that checks some characteristic
socket data.
```

File: docs/API-functions.md [hunk 6]
```diff
@@ -1614,6 +1618,284 @@ is not availble - it then sets the value to `SRT_REJC_PREDEFINED + 404`.
...
+#### `SRT_EWRPERM`
+
+Write permission was denied when trying to write to a file.
+
+#### `SRT_EINVOP`
+
+Invalid operation performed in the current state of the socket. Mainly
+it's about performing any of `srt_bind*` operations on the socket that
+is already bound. The socket that has once been bound, cannot be bound
+again.
```
Comment (stevomatthews) [inline docs/API-functions.md:1734]:
```suggestion
Invalid operation performed for the current state of a socket. This mainly
concerns performing `srt_bind*` operations on a socket that
is already bound.  Once a socket has been been bound, it cannot be bound
again.
```

File: docs/API-functions.md [hunk 7]
```diff
@@ -1614,6 +1618,284 @@ is not availble - it then sets the value to `SRT_REJC_PREDEFINED + 404`.
...
+that is currently connected is also considered bound.
+
+#### `SRT_ECONNSOCK`
+
+The socket is currently connected and therefore preforming the required
+operation is not possible. Usually it's about setting an option that must
+be set before connecting, alghouth it is allowed to be altered after
+binding. Also when trying to start connecting operation (`srt_connect*`),
+while the socket isn't in the state that allows it (only `SRTS_INIT` or
+`SRTS_OPENED` are allowed).
```
Comment (stevomatthews) [inline docs/API-functions.md:1750]:
```suggestion
The socket is currently connected and therefore performing the required
operation is not possible. Usually concerns setting an option that must
be set before connecting (although it is allowed to be altered after
binding), or when trying to start a connecting operation (`srt_connect*`)
while the socket isn't in a state that allows it (only `SRTS_INIT` or
`SRTS_OPENED` are allowed).
```

File: docs/API-functions.md [hunk 8]
```diff
@@ -1614,6 +1618,284 @@ is not availble - it then sets the value to `SRT_REJC_PREDEFINED + 404`.
...
+The API function required an ID of an entity (socket or group) and
+it was invalid. Note that some API functions work only with socket or
+only with group, so they would also return this error if inappropriate
+type of entity was passed, even if it was valid.
+
+#### `SRT_EUNBOUNDSOCK`
+
+The operation to be performed on the socket requires that it be first
+bound (using `srt_bind*` functions), explicitly. Currently it's about
+calling `srt_listen`, which cannot work with implicitly bound socket.
```
Comment (stevomatthews) [inline docs/API-functions.md:1771]:
```suggestion
The operation to be performed on a socket requires that it first be
explicitly bound (using `srt_bind*` functions). Currently it applies when
calling `srt_listen`, which cannot work with an implicitly bound socket.
```

File: docs/API-functions.md [hunk 9]
```diff
@@ -1614,6 +1618,284 @@ is not availble - it then sets the value to `SRT_REJC_PREDEFINED + 404`.
...
+#### `SRT_ENOLISTEN`
+
+The socket passed for the operation is required to be in the listen
+state (`srt_listen` must be called first).
+
+#### `SRT_ERDVNOSERV`
+
+The required operation cannot be performed when the socket is set
+rendezvous mode (`SRTO_RENDEZVOUS` set to true). Usually it's about
+trying to call `srt_listen` on such socket.
```
Comment (stevomatthews) [inline docs/API-functions.md:1782]:
```suggestion
The required operation cannot be performed when the socket is set to
rendezvous mode (`SRTO_RENDEZVOUS` set to true). Usually applies when
trying to call `srt_listen` on such a socket.
```

File: docs/API-functions.md [hunk 10]
```diff
@@ -1614,6 +1618,284 @@ is not availble - it then sets the value to `SRT_REJC_PREDEFINED + 404`.
...
+#### `SRT_ERDVUNBOUND`
+
+The socket has been set rendezvous mode (`SRTO_RENDEZVOUS` set to
+true), and was tried to be connected without being bound first. The
+rendezvous connection requires setting up two addresses and ports
+on both sides of the connection, then set local one with `srt_bind`
+and use the remote one with `srt_connect` (or you can simplify it
+using `srt_rendezvous`). Calling `srt_connect*` on an unbound socket
+(in `SRTS_INIT` state), that is, to be bound implicitly, is only allowed
+for regular caller socket (not rendezvous).
```
Comment (stevomatthews) [inline docs/API-functions.md:1793]:
```suggestion
An attempt was made to connect to a socket set to rendezvous mode 
(`SRTO_RENDEZVOUS` set to true) that was not first bound. A
rendezvous connection requires setting up two addresses and ports
on both sides of the connection, then setting the local one with `srt_bind`
and using the remote one with `srt_connect` (or you can simply
use `srt_rendezvous`). Calling `srt_connect*` on an unbound socket
(in `SRTS_INIT` state) that is to be bound implicitly is only allowed
for regular caller sockets (not rendezvous).
```

File: docs/API-functions.md [hunk 11]
```diff
@@ -1614,6 +1618,284 @@ is not availble - it then sets the value to `SRT_REJC_PREDEFINED + 404`.
...
+
+The epoll container has currently no subscribed sockets. This is reported by an
+epoll waiting function that would in this case block forever. This problem
+might be reported both in a situation that you have created a new epoll
+container and didn't subscribe any socket to it, or you did, but all these
+sockets have been closed (including when closed in a separate thread while the
+waiting function was blocking). Note that this situation can be prevented from
+by setting the `SRT_EPOLL_ENABLE_EMPTY` flag, which may be useful in case when
+you use multiple threads and start waiting without subscribed sockets, so that
+you can subscribe them later from another thread.
```
Comment (stevomatthews) [inline docs/API-functions.md:1850]:
```suggestion
The epoll container currently has no subscribed sockets. This is reported by an
epoll waiting function that would in this case block forever. This problem
might be reported both in a situation where you have created a new epoll
container and didn't subscribe any sockets to it, or you did, but these
sockets have been closed (including when closed in a separate thread while the
waiting function was blocking). Note that this situation can be prevented
by setting the `SRT_EPOLL_ENABLE_EMPTY` flag, which may be useful when
you use multiple threads and start waiting without subscribed sockets, so that
you can subscribe them later from another thread.
```

File: docs/API-functions.md [hunk 12]
```diff
@@ -1614,6 +1618,284 @@ is not availble - it then sets the value to `SRT_REJC_PREDEFINED + 404`.
...
+ready for sending, but `SRTO_SNDSYN` was set to false (when true,
+the function would block the call otherwise).
+
+#### `SRT_EASYNCRCV`
+
+Receiving operation is not ready to perform. This error is reported
+when trying to perform a receiving operation or accept a new socket from the
+listner socket, when the socket is not ready for that operation, but
+`SRTO_RCVSYN` was set to false (when true, the function would block
+the call otherwise).
```
Comment (stevomatthews) [inline docs/API-functions.md:1870]:
```suggestion
Receiving operation is not ready to perform. This error is reported
when trying to perform a receiving operation or accept a new socket from the
listener socket, when the socket is not ready for that operation, but
`SRTO_RCVSYN` was set to false (when true, the function would block
the call otherwise).
```

File: docs/API-functions.md [hunk 13]
```diff
@@ -1614,6 +1618,284 @@ is not availble - it then sets the value to `SRT_REJC_PREDEFINED + 404`.
...
+The operation timed out. This can happen if you have a timeout
+set by an option (`SRTO_RCVTIMEO` or `SRTO_SNDTIMEO`), or passed
+as an extra argument (`srt_epoll_wait` or `srt_accept_bond`) and
+the function call was blocking, but the required timeout time has passed.
+
+#### `SRT_ECONGEST`
+
+This error is used only in an experimental version that requires
+setting the `SRT_ENABLE_ECN` macro at compile time. Otherwise the
+described below situation results in just usual successful report.
```
Comment (stevomatthews) [inline docs/API-functions.md:1883]:
```suggestion
NOTE: This error is used only in an experimental version that requires
setting the `SRT_ENABLE_ECN` macro at compile time. Otherwise the
situation described below results in the usual successful report.
```

File: docs/API-functions.md [hunk 14]
```diff
@@ -1614,6 +1618,284 @@ is not availble - it then sets the value to `SRT_REJC_PREDEFINED + 404`.
...
+
+This error should be reported by the sending function in case when
+with `SRTO_TLPKTDROP` set to true there were packets had to be removed
+from the sender buffer and forgotten because the network is unable
+to live up to the sending rate.
```
Comment (stevomatthews) [inline docs/API-functions.md:1888]:
```suggestion
This error should be reported by the sending function when, with
`SRTO_TLPKTDROP` set to true, packets to be removed from the 
sender buffer are forgotten because the network is unable
to support to the sending rate. 
```

File: srtcore/api.cpp [hunk 15]
```diff
@@ -1010,7 +1010,13 @@ SRTSOCKET CUDTUnited::accept(const SRTSOCKET listen, sockaddr* pw_addr, int* pw_
 
    // no "accept" in rendezvous connection setup
    if (ls->m_pUDT->m_bRendezvous)
-      throw CUDTException(MJ_NOTSUP, MN_ISRENDEZVOUS, 0);
+   {
+       LOGC(mglog.Fatal, log << "CUDTUnited::accept: RENDEZVOUS flag passed through check in srt_listen when it set listen state");
+       // This problem should never happen because `srt_listen` function should have
+       // checked this situation before and not set listen state in result. To the user
+       // inform about the invalid state universal way.
```
Comment (stevomatthews) [inline srtcore/api.cpp:1017]:
```suggestion
       // checked this situation before and not set listen state in result.
       // Inform the user about the invalid state in the universal way.
```

File: docs/API-functions.md (hunk 14 above)
Comment (ethouris) [reply docs/API-functions.md:1888]: Ok, I'll try to describe the situation. When this error is encountered:
 - SRTO_TLPKTDROP flag was set
 - the TLPKTDROP on the sender site was triggered (there were found packets in the sender buffer, which's predicted delivery time is already in the past, and they are still not acknowledged - in that case the sender simply drops these packets from the sender buffer and they are no longer eligible for retransmission)

And also the `SRT_ENABLE_ECN` was turned on at compile time.

In this case the data sending function will return this error, however the data that it has scheduled for sending have been accepted.

Maybe this way:

This error should be reported by the sending function when, with `SRTO_TSBPDMODE` and `SRTO_TLPKTDROP` set to true`, some packets were dropped at the sender side (see description for `SRTO_TLPKTDROP` for details). This doesn't concern the data that were passed for sending by this call (these data are placed at the back side of the sender buffer, while the dropped packets are at the front side of the sender buffer). In other words, the operation done by the sending function is actually successful, just the application might want to slowdown the sending rate to avoid the congestion.

Comment (stevomatthews) [reply docs/API-functions.md:1887]: Your last suggestion is much better. Some minor tweaks:

This error should be reported by the sending function when, with `SRTO_TSBPDMODE` and `SRTO_TLPKTDROP` set to true, some packets were dropped at the sender side (see the description of `SRTO_TLPKTDROP` for details). This doesn't concern the data that were passed for sending by the sending function (these data are placed at the back of the sender buffer, while the dropped packets are at the front). In other words, the operation done by the sending function is successful, but the application might want to slow down the sending rate to avoid congestion.
