### PR TITLE
[apps] Fixed srt-file-transit (issue #645)

### LINKED ISSUE #645: srt-file-transmit loses 99% of data in transfer
Issue seems to coincide with commit 9e48f03 about 6 days ago, that `srt-file-transmit` no longer works correctly.

Running both Source and Target sides with "-v" reveals data loss -- Source sending 1316 bytes per chunk sent, and the Target receiving 1 byte per chunk sent.

**Source-side:** sends a file size 134,232 bytes input3.txt
```
srt-file-transmit.exe -v ./input3.txt srt://:5555
SOURCE type=file, TARGET type=srt
Extract path './input3.txt': directory=C:\Users\dbalma\Projects\srt\bin\Release/. filename=input3.txt
Opening SRT target listener on :5555
Binding a server on :5555 ...
 listen...
Event with status 3

 accept...
 connected.
Target connected (listener)
Upload: 1316 --> 1316
Event with status 5

Upload: 1316 --> 1316
Event with status 5

Upload: 1316 --> 1316
Event with status 5

[...]

Upload: 1316 --> 1316
Event with status 5

File sent
Buffers flushed
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%980186327 ls%-1)...
SrtCommon: ... done.
```

**Target-side:** receives file size 100 bytes output3.txt
```
srt-file-transmit.exe -v srt://127.0.0.1:5555 ./output3.txt
SOURCE type=srt, TARGET type=file
Extract path './output3.txt': directory=C:\Users\dbalma\Projects\srt\bin\Release/. filename=output3.txt
Opening SRT source caller on 127.0.0.1:5555
Connecting to 127.0.0.1:5555
Event with status 5

Source connected (caller), id []
Writing output to [C:\Users\dbalma\Projects\srt\bin\Release/./output3.txt]
Download: --> 1
Event with status 5

Download: --> 1
Event with status 5

Download: --> 1
Event with status 5

[...]

Download: --> 1
Event with status 6

Source disconnected
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%120426075 ls%-1)...
SrtCommon: ... done.
```

@Howlowck also observed this behavior -- we've reproduced on both Linux and Windows builds this week.

### PR DESCRIPTION
**Pull request by maxlovic**
Fixed `srt-file-transmit` issue, introduced by #598.
`Source::Read(…)` now returns int and does not throw exceptions.

Fixes #645

### CODE REVIEW

File: apps/srt-file-transmit.cpp [hunk 1]
```diff
@@ -180,7 +180,7 @@ int parse_args(FileTransmitConfig &cfg, int argc, char** argv)
         return 2;
     }
 
-    cfg.chunk_size    = stoul(Option<OutString>(params, "1316", o_chunk));
+    cfg.chunk_size    = stoul(Option<OutString>(params, "1456", o_chunk));
```
Comment (ethouris) [inline apps/srt-file-transmit.cpp]: Actually I doubt this option makes any sense anymore.

Comment (maxlovic) [reply apps/srt-file-transmit.cpp]: I agree it is very unlikely to be used, but still is was in the previous file transmit version, so I'd better keep it, at least to minimize the work on these apps.
