### PR TITLE
[Test][MAINT] Splitting ListenCallback test into 3 separate tests, fixed proper setup/teardown

### LINKED ISSUE #1306: [tests] Split listener callback test into three test cases
Improve the listener callback test.
**File:** test/test_listen_callback.cpp

`TEST(Core, ListenCallback)` actually contains three tests that should be split into three actual tests using the test fixture.

Example fixture: test/test_socket_options.cpp

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #1306

### CODE REVIEW

File: test/test_listen_callback.cpp [hunk 1]
```diff
@@ -22,26 +195,12 @@ srt_listen_callback_fn SrtTestListenCallback;
...
 
-    using namespace std;
-
-    ASSERT_EQ(srt_startup(), 0);
-
-    // Create server on 127.0.0.1:5555
-
-    const SRTSOCKET server_sock = srt_create_socket();
-    ASSERT_GT(server_sock, 0);    // socket_id should be > 0
+TEST(Core, DISABLED_ListenCallback)
```
Comment (maxsharabayko) [inline test/test_listen_callback.cpp:199]: To remove? As I read it, the test is replaced by those three tests based on the fixture.

Comment (ethouris) [reply test/test_listen_callback.cpp:199]: Ops. Forgot to remove it, didn't want to do this until I'm certain that everything is working. Just a moment ;)
