### PR TITLE
[apps] FIX srt-live-transmit stops listening after SRT disconnect #2997...

### LINKED ISSUE #2997: [BUG] srt-live-transmit stops listening after SRT disconnect during no active input
**Describe the bug**
srt-live-transmit stops listening on the configured port if the SRT connection was closed at a moment when there was no input

**To Reproduce**

1. Start srt-live-transmit and stop sending input. Or to simulate, just pipe nothing into it: `cat | srt-live-transmit -v file://con srt://127.0.0.1:5000?mode=listener`
2. Start a receiver: `srt-live-transmit -v srt://127.0.0.1:5000?mode=caller udp://127.0.0.1:5001`
3. Stop the receiver

If you now try to reconnect or check with for example `netstat -anu | grep 5000` you'll see the bind has disappeared.

**Expected behavior**
The listener never stops listening on the configured port.

**Desktop (please provide the following information):**
 - OS: Linux (Debian 12, Ubuntu 24.04)
 - SRT Version / commit ID: 1.5.3

### PR DESCRIPTION
**Pull request by cl-ment**
... during no active input (FIX #2997)

There are two primary reasons for this issue:

1. The main loop assumes that each time srt_epoll_wait returns, there is data available to read from the source. However, this assumption is incorrect when an SRT socket is in listener mode and on the "target" side. In this mode, srt_epoll_wait can return simply to provide an opportunity to accept a new connection, even if no data is ready to be read. As a result, the process becomes stuck while waiting to read from the source.
2. The ConsoleSource operates in blocking mode by default. Even worse, its Read() method blocks execution until a full packet (1456 bytes) is received.

### CODE REVIEW

File: apps/srt-live-transmit.cpp [hunk 1]
```diff
@@ -537,14 +539,19 @@ int main(int argc, char** argv)
                     }
                     break;
                 case UriParser::FILE:
-                    if (srt_epoll_add_ssock(pollid,
-                        src->GetSysSocket(), &events))
                     {
-                        cerr << "Failed to add FILE source to poll, "
-                            << src->GetSysSocket() << endl;
-                        return 1;
+                        int con = src->GetSysSocket();
```
Comment (maxsharabayko) [inline apps/srt-live-transmit.cpp:543]:
```suggestion
                        const int con = src->GetSysSocket();
```

File: apps/srt-live-transmit.cpp [hunk 2]
```diff
@@ -537,14 +539,19 @@ int main(int argc, char** argv)
...
+                        // try to make the standard input non blocking
+                        srcMayBlock = fcntl(con, F_SETFL, fcntl(con, F_GETFL) | O_NONBLOCK) < 0;
```
Comment (maxsharabayko) [inline apps/srt-live-transmit.cpp:545]: This functionality is better to be moved inside the file source class to maintain the abstraction layer from the system-level function calls.

File: apps/srt-live-transmit.cpp [hunk 3]
```diff
@@ -771,12 +779,46 @@ int main(int argc, char** argv)
...
+                    {
+                        SRTSOCKET sock = src->GetSRTSocket();
+                        if (sock != SRT_INVALID_SOCK)
+                        {
+                            for (int n = 0; n < srtrfdslen; n ++)
+                                if (sock == srtrwfds[n])
+                                {
+                                    srcReady = true;
+                                    break;
+                                }
```
Comment (maxsharabayko) [inline apps/srt-live-transmit.cpp:797]: More readable and error-prone.
```suggestion
                            for (int n = 0; n < srtrfdslen; n ++)
                            {
                                if (sock == srtrwfds[n])
                                {
                                    srcReady = true;
                                    break;
                                }
                            }
```

File: apps/srt-live-transmit.cpp [hunk 4]
```diff
@@ -771,12 +779,46 @@ int main(int argc, char** argv)
...
+                        int sock = src->GetSysSocket();
+                        if (sock != -1)
+                        {
+                            for (int n = 0; n < sysrfdslen; n++)
+                                if (sock == sysrfds[n])
+                                {
+                                    srcReady = true;
+                                    break;
+                                }
+
```
Comment (maxsharabayko) [inline apps/srt-live-transmit.cpp:812]:
```suggestion
                            for (int n = 0; n < sysrfdslen; n++)
                                if (sock == sysrfds[n])
                                {
                                    srcReady = true;
                                    break;
                                }
                            }
```

File: apps/transmitmedia.cpp [hunk 5]
```diff
@@ -712,6 +713,9 @@ class ConsoleSource: public Source
         // The default stdin mode on windows is text.
         // We have to set it to the binary mode
         _setmode(_fileno(stdin), _O_BINARY);
+#else
+        const int fd = fileno(stdin);
+        may_block = fcntl(fd, F_SETFL, fcntl(fd, F_GETFL) | O_NONBLOCK) < 0;
```
Comment (ethouris) [inline apps/transmitmedia.cpp:718]: That doesn't make any sense. If this fails (best from the constructor), it should make the application exit. Error from this call is unlikely.

File: apps/srt-live-transmit.cpp [hunk 6]
```diff
@@ -800,9 +843,10 @@ int main(int argc, char** argv)
 
                         dataqueue.push_back(pkt);
                         receivedBytes += pkt->payload.size();
+                        if (src->MayBlock())
+                            break;
```
Comment (ethouris) [inline apps/srt-live-transmit.cpp:847]: I think that actually reading should be done this way: either you have the device read-ready, so you read, and then after you read, you don't know, and have to recheck.

Or, you can resolve to reading multiple times, counting on that when particular time reading isn't ready, then the Read call should report an error. Might be, I think, a good idea, to keep the "blocked" state in the fields, which will be written to, in case when particular Read implementation finds out that the call failed due to not being ready. This way it won't need to see if this is SRT and this way we use that function to get the error and maybe check for an SRT-specific readiness failure.

File: apps/transmitmedia.cpp (hunk 5 above)
Comment (cl-ment) [reply apps/transmitmedia.cpp:718]: Typically, when implementing an event loop for reading, the pattern is to use non-blocking file descriptors and continue reading until `errno == EAGAIN` is encountered.
If it’s not possible to make the file descriptors non-blocking, an alternative approach is to make a single `read()` call for each “_read_” event. While this approach is not optimal due to the increased number of system calls, it still ensures the process functions as expected from the user’s perspective. I prefer this pragmatic approach over halting the process just because it cannot run in an optimal manner.

File: apps/srt-live-transmit.cpp (hunk 6 above)
Comment (cl-ment) [reply apps/srt-live-transmit.cpp:847]: From what I understand, the current implementation already follows this approach. For file descriptors in blocking mode (case 1), it checks if the device is ready before attempting to read, performs the read operation, and rechecks the state afterward since readiness isn’t guaranteed. For file descriptors in non-blocking mode (case 2), it handles multiple read attempts and relies on the error returned by the Read call to detect if the device isn’t ready.
Could you clarify if there’s something specific you’d like me to adjust or add to the current implementation? Perhaps there’s a particular scenario or behavior you’d like to address that isn’t currently handled?

Comment (cl-ment) [reply apps/srt-live-transmit.cpp:847]: I understand the benefits of enforcing non-blocking mode for consistency and simplifying the architecture. However, I think it might be preferable to maintain support for both blocking and non-blocking modes. This flexibility ensures compatibility with a broader range of sources and use cases, particularly for systems where blocking mode is either required or more practical.

The current implementation can differentiate the handling of each mode:
	•	For blocking mode: Always check read-readiness before calling Read().
	•	For non-blocking mode: Check read-readiness once before the loop and perform multiple Read() calls until it’s no longer possible.

Would you be open to maintaining support for both modes, or do you see specific challenges in doing so?

Comment (maxsharabayko) [reply apps/srt-live-transmit.cpp:847]: The initial specific about `srt-live-transmit` is that it is intended as a sample application, showing how to work with SRT using epoll and non-blocking mode. I don't think supporting the blocking mode was the case.
Now the problem is that a user can actually set the blocking mode via URI `srt://ip:port?blocking=true`, and then the application must either work, or report an error that the blocking mode is not supported.

File: apps/srt-live-transmit.cpp [hunk 7]
```diff
@@ -771,12 +777,49 @@ int main(int argc, char** argv)
...
+                        if (sock != SRT_INVALID_SOCK)
+                        {
+                            for (int n = 0; n < srtrfdslen; n ++)
+                            {
+                                if (sock == srtrwfds[n])
+                                {
+                                    srcReady = true;
+                                    break;
+                                }
+                            }
```
Comment (maxsharabayko) [inline apps/srt-live-transmit.cpp:797]: Consider packing this into a helper function than can be used both for `srtrwfds` and `sysrfds`, thus making the code more compact and easier to read the intent.

File: apps/srt-live-transmit.cpp (hunk 6 above)
Comment (ethouris) [reply apps/srt-live-transmit.cpp:847]: Exactly. This is built in into the architecture of this application to only support the nonblocking mode and it should not even take the blocking mode into account - unlike the `srt-test-live` application, which supports both, and it is prepared to work in either mode.

File: apps/transmitmedia.cpp [hunk 8]
```diff
@@ -704,6 +704,7 @@ Iface* CreateSrt(const string& host, int port, const map<string,string>& par) {
 
 class ConsoleSource: public Source
 {
+    bool may_block = true;
```
[the remark this answers is not in the document]
Comment (ethouris) [reply apps/transmitmedia.cpp:707]: I would eliminate it altogether and just report an error and exit in case when nonblocking mode can't be enforced.

File: apps/transmitmedia.cpp [hunk 9]
```diff
@@ -731,14 +734,15 @@ class ConsoleSource: public Source
...
         if (chunk < pkt.payload.size())
-            pkt.payload.resize(chunk);
+            pkt.payload.resize(ret);
 
-        return (int) chunk;
+        return ret;
     }
 
-    bool IsOpen() override { return cin.good(); }
+    bool IsOpen() override { return !cin.eof(); }
```
[the remark this answers is not in the document]
Comment (ethouris) [reply apps/transmitmedia.cpp:742]: Actually the only use case when `cin.eof()` could be true is when a user presses Ctrl-D and when the pipeline is broken (you also need to ignore SIGPIPE).

[the remark this answers is not in the document]
Comment (cl-ment) [reply apps/transmitmedia.cpp:742]: good() returns false when unexpected data is received from std::cin—for example, if letters are entered instead of the expected numbers. However, cin remains open in this case.

That’s why I initially thought !cin.eof() would be a more appropriate check.

File: apps/transmitmedia.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (cl-ment) [reply apps/transmitmedia.cpp]: Added all the "const" suggestions (commit: 6fb40eb22cae5427b92f2400899d2dd2abf19132)

File: apps/transmitmedia.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (maxsharabayko) [reply apps/transmitmedia.cpp:744]: `cin.eof()` can be used via `End()` function instead of `IsOpen()` in the application loop.
If that makes sense for all the mediums.
My complaint here is that implementing `IsOpen()` via `cin::eof()` kinda deceives сукефшт expectations.

[the remark this answers is not in the document]
Comment (cl-ment) [reply apps/transmitmedia.cpp]: Reverted ConsoleSource.IsOpen(). I've got nothing better to propose and it's not really related to this PR.

File: apps/srt-live-transmit.cpp [hunk 10]
```diff
@@ -771,12 +777,34 @@ int main(int argc, char** argv)
                     break;
                 }
 
+
+                bool srcReady = false;
+
+                if (src.get() && src->IsOpen())
```
Comment (maxsharabayko) [inline apps/srt-live-transmit.cpp:783]: Maybe this way then if you still want to use `cin.eof()`?
```suggestion
                if (src.get() && src->IsOpen() && !src->EOF())
```

**Comment by maxsharabayko** [comment]
The review has dragged on. If there are no critical comments, I suggest merging once CI checks pass.
`MayBlock` is still the remaining point, as I understand. Not crucial though.
`cin.eof()` usage still can be done, see my suggestion, but not sure if it would work properly for other mediums. Not critical, I assume?

**Comment by maxsharabayko** [comment]
Not related to these changes, but noting down the QEMU CI failure on test
```
[ RUN      ] ReuseAddr.DiffAddr
[T/S] serverSocket: creating binder socket
[T/S] Bind @275074266 to: 127.0.0.1:5000 (IPv4)
[T/S] ... result 0 (expected to succeed)
[T/S] serverSocket: creating listener socket
[T/S] Bind @275074265 to: 172.17.0.2:5000 (IPv4)
[T/S] ... result 0 (expected to succeed)
[T/S] Listener/binder sock @275074265 added to server_pollid
[T/C] Setting up client socket
[T/S] Wait 10s on E81 for acceptance on @275074265 ...
[T/C] Connecting to: 172.17.0.2:5000 (IPv4)
[T/S] Accepted from: 172.17.0.2:42683
[T/S] Wait for data reception...
[T/C] Waiting for connection readiness...
[T/C] Client exit
[T/S] closing client socket
[T/S] closing sockets: ACP:@275074263...
/github/workspace/test/test_main.cpp:207: Failure
Expected: (close_error) != (SRT_EINVSOCK), actual: 5004 vs 5004
[T/S]accept CREATED: /github/workspace/test/test_reuseaddr.cpp:347
[T/S] joining client async 
[T/S] waiting for cleanup of @275074266 up to 10s
[T/S] @275074266 dissolved after 1.002s
[T/S] waiting for cleanup of @275074265 up to 10s
[T/S] @275074265 dissolved after 1.001s
[  FAILED  ] ReuseAddr.DiffAddr (2133 ms)
```

**Comment by Frenzie** [comment]
Thanks! I can confirm it now successfully fully destroys the connection and rebinds after the receiver stops.

```
Media path: 'file://con' --> 'srt://127.0.0.1:5000?mode=listener'
SRT parameters specified:

        mode = 'listener'
Opening SRT target listener on 127.0.0.1:5000
Binding a server on 127.0.0.1:5000 ...
 listen...
 accept... 
 connected.
Accepted SRT target connection
SRT target disconnected
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%646118174 ls%-1)...
SrtCommon: ... done.
SRT parameters specified:

        mode = 'listener'
Opening SRT target listener on 127.0.0.1:5000
Binding a server on 127.0.0.1:5000 ...
 listen...
 accept... 
 connected.
11:07:09.860234/srt-live-transm*E:SRT.ea: remove_usock: @646118173 not found as either socket or group. Removing only from epoll system.
Accepted SRT target connection
11:07:10.860323/SRT:GC*E:SRT.ei: epoll/update: IPE: update struck E1 which is NOT SUBSCRIBED to @646118173
11:07:10.860392/SRT:GC*E:SRT.ei: epoll/update: IPE: update struck E1 which is NOT SUBSCRIBED to @646118173
```
