### PR TITLE
Fix redefinition of inet_pton with mingw-w64

### LINKED ISSUE #474: (MSYS2/MinGW, GCC) inet_pton() was declared 'extern' and later 'static'
Compiling libsrt fails in transmitmedia.cpp:

```
FAILED: CMakeFiles/srtsupport_virtual.dir/apps/transmitmedia.cpp.o 
H:\development\media-autobuild_suite-master\msys64\mingw32\bin\c++.exe  -DHAICRYPT_USE_OPENSSL_AES -DHAICRYPT_USE_OPENSSL_EVP=1 -DHAI_ENABLE_SRT=1 -DHAI_PATCH=1 -DPTW32_STATIC_LIB=1 -DSRT_VERSION=\"1.3.1\" -DWIN32=1 -D_GNU_SOURCE -I../common -I../srtcore -I../haicrypt -I. -mthreads -mtune=generic -O2 -pipe   -DENABLE_LOGGING=1 -Wall -Wextra -O3 -DNDEBUG   -std=c++11 -MD -MT CMakeFiles/srtsupport_virtual.dir/apps/transmitmedia.cpp.o -MF CMakeFiles\srtsupport_virtual.dir\apps\transmitmedia.cpp.o.d -o CMakeFiles/srtsupport_virtual.dir/apps/transmitmedia.cpp.o -c ../apps/transmitmedia.cpp
In file included from ../apps/transmitmedia.cpp:26:0:
../apps/apputil.hpp: In function 'int inet_pton(int, const char*, void*)':
../apps/apputil.hpp:80:19: error: 'int inet_pton(int, const char*, void*)' was declared 'extern' and later 'static' [-fpermissive]
 static inline int inet_pton(int af, const char * src, void * dst)
                   ^~~~~~~~~
In file included from ../srtcore/platform_sys.h:15:0,
                 from ../srtcore/srt.h:21,
                 from ../apps/transmitmedia.cpp:20:
H:/development/media-autobuild_suite-master/msys64/mingw32/i686-w64-mingw32/include/ws2tcpip.h:454:32: note: previous declaration of 'INT inet_pton(INT, LPCSTR, PVOID)'
 WINSOCK_API_LINKAGE INT WSAAPI InetPtonA(INT Family, LPCSTR pStringBuf, PVOID pAddr);
```

Log files archive created by [MABS](https://github.com/jb-alvarado/media-autobuild_suite/) = [logs.zip](https://0x0.st/sYeB.zip) where you may want to check e.g. **srt-git/build-32bit/ab-suite.build.log** for further details.

### PR DESCRIPTION
**Pull request by wiiaboo**
It may be missing in mingw32, but not in mingw-w64.

Fixes #474 .

### CODE REVIEW

**Comment by wiiaboo** [comment]
Maybe not a mingw-w64 from 2013, since that's when it was added...

File: apps/apputil.hpp [hunk 1]
```diff
@@ -76,7 +76,7 @@ inline void SysCleanupNetwork() {}
 // See:
 //    https://msdn.microsoft.com/en-us/library/windows/desktop/ms742214(v=vs.85).aspx
 //    http://www.winsocketdotnetworkprogramming.com/winsock2programming/winsock2advancedInternet3b.html
-#ifdef __MINGW32__
+#ifndef HAVE_INET_PTON
 static inline int inet_pton(int af, const char * src, void * dst)
```
Comment (rndi) [inline apps/apputil.hpp]: This particular inet_pton() implementation is Windows-only. Shouldn't there be `#ifdef _WIN32` around it too, maybe just below `#ifndef HAVE_INET_PTON`?

Comment (wiiaboo) [reply apps/apputil.hpp]: Sure.

File: CMakeLists.txt [hunk 2]
```diff
@@ -145,6 +147,22 @@ endif()
 # When you use crosscompiling, you have to take care that PKG_CONFIG_PATH
 # and CMAKE_PREFIX_PATH are set properly.
 
+# symbol exists in win32, but function does not.
+if(WIN32)
+	if(ENABLE_INET_PTON)
+		set(CMAKE_REQUIRED_LIBRARIES ws2_32)
+		check_function_exists(inet_pton HAVE_INET_PTON)
+		add_definitions(-D_WIN32_WINNT=0x0600)
```
Comment (rndi) [inline CMakeLists.txt]: Another question: why do we need to define _WIN32_WINNT (other than testing)?

**Comment by wiiaboo** [comment]
Rebased and modified as asked in https://github.com/Haivision/srt/pull/476#discussion_r224841822
