### PR TITLE
Fixed wrong usage of seqcmp

### LINKED ISSUE #579: Check CSeqNo::seqcmp wrong usage
There's needed a check if the `CSeqNo::seqcmp` function wasn't misused. This function works similar way as `CSeqNo::seqoff`, however it's not predicted that its return type is used for anything else than relationship, or in other words, the result of this function should not be used any other way than comparison against 0. The actual value that should show the true distance between two sequences shall be exclusively measured using `CSeqNo::seqoff` function.

It might be also a good idea to implement a new type that would only hold the 3-way result and can be tested for a condition state, as well as simply implementing the `< >` operators for `CSeqNo` so that the comparison can be used more natural way.

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #579

### CODE REVIEW

File: srtcore/common.h [hunk 1]
```diff
@@ -685,7 +685,7 @@ class StatsLossRecords
 
     void add(int32_t lo, int32_t hi)
     {
-        int32_t end = lo + CSeqNo::seqcmp(hi, lo);
+        int32_t end = CSeqNo::incseq(hi);
```
Comment (maxlovic) [inline srtcore/common.h]: Was `lo + (hi - lo)` for the general case (`(abs(seq1 - seq2) < m_iSeqNoTH`).
Now: `hi + 1`

Function `void add(int32_t lo, int32_t hi)` is never used? As well as class `StatsLossRecords`.
Changes in `common.h` do not effect the work of SRT.

File: srtcore/core.cpp [hunk 2]
```diff
@@ -6257,10 +6257,10 @@ static void DebugAck(string hdr, int prev, int ack)
     }
 
     prev = CSeqNo::incseq(prev);
-    int diff = CSeqNo::seqcmp(ack, prev);
+    int diff = CSeqNo::seqoff(prev, ack);
```
Comment (maxlovic) [inline srtcore/core.cpp]: `DebugAck()` is used for heavy logging. The change does not affect SRT functionality.

File: srtcore/core.cpp [hunk 3]
```diff
@@ -6648,12 +6648,12 @@ void CUDT::processCtrl(CPacket& ctrlpkt)
       CGuard::enterCS(m_AckLock);
 
       // check the validation of the ack
-      int seqdiff = CSeqNo::seqcmp(ack, CSeqNo::incseq(m_iSndCurrSeqNo));
-      if (seqdiff> 0)
+      if (CSeqNo::seqcmp(ack, CSeqNo::incseq(m_iSndCurrSeqNo)) > 0)
```
Comment (maxlovic) [inline srtcore/core.cpp]: Small refactoring, logic is not changed.

File: srtcore/core.cpp [hunk 4]
```diff
@@ -7936,7 +7938,7 @@ void CUDT::unlose(const CPacket& packet)
         {
             HLOGF(mglog.Debug, "received out-of-band packet seq %d", sequence);
 
-            int seqdiff = abs(CSeqNo::seqcmp(m_iRcvCurrSeqNo, packet.m_iSeqNo));
+            int seqdiff = abs(CSeqNo::seqoff(packet.m_iSeqNo, m_iRcvCurrSeqNo));
```
Comment (maxlovic) [inline srtcore/core.cpp]: A notable change. What is happening here?

Comment (maxlovic) [reply srtcore/core.cpp]: Previously it was effectively just `abs(m_iRcvCurrSeqNo, packet.m_iSeqNo)`.

Now it is `m_iRcvCurrSeqNo - packet.m_iSeqNo,` if the difference is within the threshold `m_iSeqNoTH`.

Otherwise
```
if (packet.m_iSeqNo < m_iRcvCurrSeqNo)
	return m_iRcvCurrSeqNo - packet.m_iSeqNo - m_iMaxSeqNo - 1;

return m_iRcvCurrSeqNo - packet.m_iSeqNo + m_iMaxSeqNo + 1;
```

File: srtcore/common.h (hunk 1 above)
Comment (ethouris) [reply srtcore/common.h]: This is still an existing code. Not sure what to do with it, but even if it had to be used for testing purposes only, it should work correctly. I don't even know anymore what the API requirements for the `add` function were, I simply guessed it requires to get the range of sequences, with both ends included. Therefore the `end` sequence should be the first value for which the loop condition shouldn't be executed and it should stop there, so I defined it simply according to this statement.

File: srtcore/core.cpp (hunk 2 above)
Comment (ethouris) [reply srtcore/core.cpp]: Hit by the general search-replace query, I only skipped replacement when it was clear that the result is only compared against 0. This is for debug purposes, but it better work correctly or should be disabled.

File: srtcore/core.cpp (hunk 3 above)
Comment (ethouris) [reply srtcore/core.cpp]: It's simply the value `seqdiff` ruled out. However, this variable was previously used in some further debug log expressions - these were also ruled out. Removal of this variable makes the use of seqcmp as comparison-only clear.

File: srtcore/core.cpp (hunk 4 above)
Comment (ethouris) [reply srtcore/core.cpp]: As you remember our research session about these functions, `seqoff` and `seqcmp` differ firstly in that the "primary result" is in reverse: `seqcmp(s1, s2)` is like `(s1 - s2)`, `seqoff(s1, s2)` is like `(s2 - s1)`. The other difference is that `seqoff` returns the real distance, while `seqcmp` only a value that has only a correct relationship to 0, but the value itself may be misleading.
