### PR TITLE
[BUG] Fixed the use of the right error constant

### LINKED ISSUE #2505: precise comparison -1 by SRT_ERROR/SRT_INVALID_SOCK
there are many implicite comparisons srt error code/srt socket in folders srt/test/* 
can you fix it ?

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #2505 

This changes the use of the error constants SRT_ERROR and SRT_INVALID_SOCK. Besides, there are some others (maybe some better fix could be introduced sometimes, but note that some parts apply to the C API):

1. Introduced a new type, `SRTSTATUS`. This is obviously an alias for `int`, but the use of it suggests that there are only two possible values expected in return: `SRT_ERROR` or `SRT_STATUS_OK` (newly introduced in this PR - could be `SRT_SUCCESS`, but this symbol is already used for a 0 error code, so it's from a kinda different domain).
2. Introduced additionally `SRTRUNSTATUS`, which contains values for usual OK and ERROR, but also ALREADY, which means that no actual action was undertaken as it was started already. This is currently in use for `srt_startup()`, as it was hard to find any better solution (an integer value could be used, but this value is still symbolic, not anyhow numeric with trap), but made universal enough if any need for similar type of status appears.
3. Might be that the returned value has some "meaningful" value when it is non-negative, and other value is only -1, for which `SRT_ERROR` should be used. This is used explicitly now, although the return type is `int`, not `SRTSTATUS`.
4. Sometimes the returned value is a socket, but it still might return an error, with the same value -1. For this case the error value is used as `SRT_INVALID_SOCK` as per the `SRTSOCKET` return type. As this is also an alias to `int` (`int32_t` more preciesly), then there's nothing wrong with comparing it to `SRT_ERROR`, but the internal code is consequently using `SRT_INVALID_SOCK` wherever `SRTSOCKET` type is used.
5. Important: all functions that do "connect", including `srt_connect`, return `SRTSOCKET` even though the usual use of `srt_connect` is connecting a single socket and the returned value should be treated as a status. Therefore the pair of `SRT_ERROR` and `SRT_STATUS_OK` should be treated as equivalent to `SRT_INVALID_SOCK` and `SRT_SOCKID_CONNREQ` respectively. The latter is a value of the socket that is used only internally, it's not a valid value of a socket, but also not erroneous (as erroneous is only `SRT_INVALID_SOCK`).

Might be then that it deserves a description, which should mention something like this:

1. The `SRTSTATUS` type contains only two possible values: `SRT_ERROR` and `SRT_STATUS_OK`. When this is the return type in an API function, all values except these are illegal.
2. Usually - but not always - the returned `int` type is an extended version of SRTSTATUS with added positive meaningful values. In this case you are allowed to use `SRT_ERROR` and non-negative values in comparison, others are illegal.
3. The `SRTSOCKET` is also an extended version of `SRTSTATUS`, in which `SRT_INVALID_SOCK` and `SRT_SOCKID_CONNREQ` map to `SRT_ERROR` and `SRT_STATUS_OK` respectively. This way, `SRT_SOCKID_CONNREQ` should be treated as a possible return for a function, which in particular runtime circumstances is not expected to return a valid socket ID. This is the case of `srt_connect`, when it is called for a single socket.

TODO:
* [x] Update the documentation, with regards to `srt_accept` and `srt_connect` and similar.

### CODE REVIEW

File: common/devel_util.h [hunk 1]
```diff
@@ -0,0 +1,90 @@
+
+#include <ostream>
```
Comment (maxsharabayko) [inline common/devel_util.h:2]: Copyright header is missing.

File: common/devel_util.h
Comment (maxsharabayko) [inline common/devel_util.h:1]: What's the difference with `utilities.h`?

File: srtcore/srt.h [hunk 2]
```diff
@@ -148,6 +164,12 @@ typedef int32_t SRTSOCKET;
 // socket or a socket group.
 static const int32_t SRTGROUP_MASK = (1 << 30);
 
+#ifdef __cplusplus
+namespace srt {
+inline bool isgroup(SRTSOCKET sid) { return (int32_t(sid) & SRTGROUP_MASK) != 0; }
+}
+#endif
```
Comment (maxsharabayko) [inline srtcore/srt.h:171]: C++ API (inline function) mixed with C API.

File: srtcore/srt.h
Comment (maxsharabayko) [inline srtcore/srt.h:1]: I would prefer not to change the `srt.h` in the 1.5.4 patch release.

**Review by maxsharabayko — COMMENTED** [review]
This is more for 1.6.0 due to changes to the API.

File: srtcore/srt.h (hunk 2 above)
Comment (ethouris) [reply srtcore/srt.h:171]: I think it can be moved. I wanted to make it available for the users. We can just as well add this to the internals and later move it to the API.

File: common/devel_util.h
Comment (ethouris) [reply common/devel_util.h:1]: This file contains things that are in any temporary use for development. This is only provided for convenience for the use during development, but the normal code goes with this file ousted, with provided just plain definitions for the specific types as alias to integer.

Directly this file is provided so that by a temporary change in srt.h you can run the compile command and then by the errors you get you can find out where the rules for the right usage of the status types has been violated.
