### PR TITLE
[apps] Fixed verbose linkage difference.

### LINKED ISSUE #2145: [BUG] 1.4.4: compile time warnings
**Describe the bug**
On compile time are emitted several warnings.

**To Reproduce**
Just compile latest srt using latest gcc using LTO.
Part of the warnings are related to use openssl 3.0.0 (those for now are less important)
Here is example script which should produce all warnings:
```shell
CFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none'
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -flto=auto -flto-partition=none -fuse-linker-plugin'
CC=/usr/bin/gcc
AR=/usr/bin/gcc-ar
NM=/usr/bin/gcc-nm
RANLIB=/usr/bin/gcc-ranlib
export CFLAGS CXXFLAGS FFLAGS FCFLAGS LDFLAGS CC CXX FC AR NM RANLIB
/usr/bin/cmake -D ENABLE_GETNAMEINFO=ON -D ENABLE_STATIC=OFF -D ENABLE_UNITTESTS=ON -D USE_GNUSTL=OFF -D USE_OLD_ADD_METHOD=OFF
```

**Expected behaviour**
No compile time warnings especially those related to use LTO.

**Screenshots**
Summary stats:
```console
[tkloczko@barrel SPECS]$ rpmbuild -ba --with check --with failing_tests srt.spec --quiet 2>&1 | grep -- -W | sed 's/.*\[//; s/\]//' | sort | uniq -c | sort -nr
      5 -Wdeprecated-declarations
      1 -Wodr
      1 -Wlto-type-mismatch
```
Warnings extracted from stderr:
```console
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c: In function 'crysprOpenSSL_AES_SetKey':
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c:43:9: warning: 'AES_set_encrypt_key' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   43 |         if (AES_set_encrypt_key(kstr, kstr_len * 8, aes_key)) {
      |         ^~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.h:24,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-config.h:9,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr.h:39,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/hcrypt.h:52,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c:20:
/usr/include/openssl/aes.h:51:5: note: declared here
   51 | int AES_set_encrypt_key(const unsigned char *userKey, const int bits,
      |     ^~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c:48:9: warning: 'AES_set_decrypt_key' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   48 |         if (AES_set_decrypt_key(kstr, kstr_len * 8, aes_key)) {
      |         ^~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.h:24,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-config.h:9,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr.h:39,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/hcrypt.h:52,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c:20:
/usr/include/openssl/aes.h:54:5: note: declared here
   54 | int AES_set_decrypt_key(const unsigned char *userKey, const int bits,
      |     ^~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c: In function 'crysprOpenSSL_AES_CtrCipher':
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c:119:27: warning: 'AES_encrypt' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  119 |                           inlen, aes_key, iv, ctr, &blk_ofs, (block128_f) AES_encrypt);
      |                           ^~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.h:24,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-config.h:9,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr.h:39,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/hcrypt.h:52,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c:20:
/usr/include/openssl/aes.h:57:6: note: declared here
   57 | void AES_encrypt(const unsigned char *in, unsigned char *out,
      |      ^~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c: In function 'crysprOpenSSL_KmWrap':
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c:154:5: warning: 'AES_wrap_key' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  154 |     return(((seklen + HAICRYPT_WRAPKEY_SIGN_SZ) == (unsigned int)AES_wrap_key(kek, NULL, wrap, sek, seklen)) ? 0 : -1);
      |     ^~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.h:24,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-config.h:9,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr.h:39,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/hcrypt.h:52,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c:20:
/usr/include/openssl/aes.h:97:5: note: declared here
   97 | int AES_wrap_key(AES_KEY *key, const unsigned char *iv,
      |     ^~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c: In function 'crysprOpenSSL_KmUnwrap':
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c:166:5: warning: 'AES_unwrap_key' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  166 |     return(((wraplen - HAICRYPT_WRAPKEY_SIGN_SZ) == (unsigned int)AES_unwrap_key(kek, NULL, sek, wrap, wraplen)) ? 0 : -1);
      |     ^~~~~~
In file included from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.h:24,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-config.h:9,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr.h:39,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/hcrypt.h:52,
                 from /home/tkloczko/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr-openssl.c:20:
/usr/include/openssl/aes.h:101:5: note: declared here
  101 | int AES_unwrap_key(AES_KEY *key, const unsigned char *iv,
      |     ^~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/apps/verbose.hpp:30:7: warning: type 'struct Log' violates the C++ One Definition Rule [-Wodr]
   30 | class Log
      |       ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/apps/verbose.hpp:30:7: note: a different type is defined in another translation unit
   30 | class Log
      |       ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/apps/verbose.hpp:34:10: note: the first difference of corresponding definitions is field 'lockline'
   34 |     bool lockline = false;
      |          ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/apps/verbose.hpp:30:7: note: a type with different number of fields is defined in another translation unit
   30 | class Log
      |       ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/apps/verbose.hpp:56:5: warning: type of '__dt_comp ' does not match original declaration [-Wlto-type-mismatch]
   56 |     ~Log();
      |     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/apps/verbose.cpp:39:5: note: '__dt_comp ' was previously declared here
   39 |     Log::~Log()
      |     ^
/home/tkloczko/rpmbuild/BUILD/srt-1.4.4/apps/verbose.cpp:39:5: note: code may be misoptimized unless '-fno-strict-aliasing' is used
```
Openssl 3.0.0 deprecation warnings can be for now skipped.
**Desktop (please provide the following information):**
 - OS: Linux/x86_64
 - SRT Version / commit ID: 1.4.4

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by maxsharabayko**
- Verbose log now has a single version with a mutex lock.
- Removed `SRT_ENABLE_VERBOSE_LOCK` build definition.

Fixes #2145.

## Notes

I am not quite sure if the implementation of the Verbose::Log with a mutex is thread safe given the `template <class V> Log& operator<<(const V& arg)` is not protected by a mutex lock. What's protected is putting the end of line symbol on log destruction.

```c++
Verb() << VerbLock << "Starting TargetMedium: " << this;
```

### CODE REVIEW

**Comment by ethouris** [comment]
I don't exactly understand this change.

The problem was, as I understand, that some object files were created using the non-lockable Verb and others lockable Verb.

The idea for this locking was that VerbLock is only used on demand. Locking isn't necessary there at all, everything there is forwarded to cout or cerr (depending on settings) and this one is thread-safe by definition. The only problem can be that when two different threads are executing verbose at the same time then the output could intermix printed items, which this locking aims to avoid. In most of the application this locking is unnecessary because they are single-threaded (except for the threads of SRT itself, but this doesn't use Verb and logs should rather use different channel).

Not sure, but if you think it's not harmful to feature locking in Verb unconditionally, so be it. But then adding this enabler in the build is not necessary, if you removed it in the sources.

**Comment by ethouris** [comment]
Ok, let me explain.

The locking was normally not necessary, and the only merit for logging is to prevent printing from different threads to be interleaved. Verb is simply redirecting to the stream (cout or cerr, depending on settings) and it's by definition thread-safe. This locking is only necessary to keep one line not interrupted by printing of the other and prevent messup in the verbose messages.

Therefore it's only required in apps that uses threads and may have a situtation of printing Verb from multiple threads simultaneously. Apps like srt-test-live don't use multiple threads and so they don't use this locking.

File: apps/verbose.cpp [hunk 1]
```diff
@@ -28,27 +27,24 @@ namespace Verbose
...
-#if SRT_ENABLE_VERBOSE_LOCK
             if (lockline)
             {
                 // Lock explicitly, as requested, and wait for the opportunity.
                 vlock.lock();
             }
             else if (vlock.try_lock())
             {
-                // Successfully locked, so unlock immediately, locking wasn't requeted.
+                // Successfully locked, so unlock immediately, locking wasn't required.
```
Comment (maxsharabayko) [inline apps/verbose.cpp:47]:
```suggestion
                // Successfully locked, so unlock immediately, locking wasn't requested.
```

Comment (ethouris) [reply apps/verbose.cpp]: yes.
