### PR TITLE
[core] Fixed group rcv buffering of ignored packet

### LINKED ISSUE #1799: [BUG] Main/backup: The group gives 1 packet out of order when the main link goes down
## Describe the bug

When retesting #1768 with the latest master, I've reproduced the following problem: right after the main link shutdown, the group drops 1 packet, gives 1 packet out of order with the reorder distance around 300 packets.

Screenshot 2021-02-08 at 18 06 48

## To Reproduce

Test procedure with the detailed description of the test setup, test cases, and `srt-xtransmit` commands for reproduction can be found [here](https://stash.haivision.com/projects/SAS/repos/srt-devbook/browse/srt-protocol/connection-bonding/test-reports/release-v1.5.0/dynamic-link-stability-timeout-4th-iteration/test-procedure.md). Briefly:

Test Setup is the combination of small Flip&Flop (CentOS 7) and big LanForge with the following links connected:

```
FLIP                 ---- LanForge  ----                 FLOP

enp7s0 (192.168.4.1) ---- eth2-eth3 ---- (192.168.4.2) enp7s0    (Main link)
enp8s0 (192.168.3.1) ---- eth4-eth5 ---- (192.168.3.2) enp8s0    (Backup link)
```

**SRT version:**
- Latest master: [2d14df227205bd327da6854430901d63aab5f4cd](https://github.com/maxsharabayko/srt/tree/2d14df227205bd327da6854430901d63aab5f4cd)
   
- `srt-xtransmit` with Connection Bonding support (`develop/bonding` branch):
   commit f66de1f2554eae704945ee0d940953a2ae8a1161 (HEAD -> develop/bonding, origin/develop/bonding)
   Author: Maxim Sharabayko <maxlovic@gmail.com>
   Date:   Mon Feb 8 17:48:48 2021 +0100

**srt-xtransmit commands:**
```
# Sender
_build_bonding_main_backup/bin/srt-xtransmit generate "srt://192.168.4.2:4200?latency=4000&grouptype=backup&weight=75" srt://192.168.3.2:4201?weight=25 --sendrate 1Mbps --duration 120s --enable-metrics --statsfile group-snd-stats.csv --statsfreq 1s -v
```

```
# Receiver
_build_bonding_main_backup/bin/srt-xtransmit receive srt://:4200?latency=4000 srt://:4201 --enable-metrics --metricsfile group-rcv-metrics.csv --metricsfreq 1s --statsfile group-rcv-stats.csv --statsfreq 1s -v
```

**Failed test case:**

Test Case 3. Main link shutdown for 40 seconds (higher than `SRTO_PEERIDLETIMEOUT` = 5 s)

Scenario | Main Link (enp7s0)                              | Backup Link (enp8s0)                       | Bitrate, Mbps  | SRT Options    | 
| --------| ------------------------------------ | ----------------------------------- | -------------- | ---------------| 
| -            | RTT1 = 1000 ms (1 s)                          | RTT2 = 1000 ms (1 s)                        | 1                       | latency=4000  |    

To emulate link shutdown use the following command:
```
sleep 40 && echo ifdown $(date +"%F %T,%3N") && sudo ifdown enp7s0 && sleep 40 && echo ifup $(date +"%F %T,%3N") && sudo ifup enp7s0
```

**Statistics and screenshots are attached:**
[srt #1799.zip](https://github.com/Haivision/srt/files/5945498/srt.1799.zip)

### PR DESCRIPTION
**Pull request by maxsharabayko**
One of the member links can provide a packet ahead of the current position after another link has provided a valid packet.
This AHEAD packet is saved in group's buffer. However, the payload of the packet was incorrect, as it was read to a buffer different from the one being saved.

Fixes #1799

### Ignoring Packet
Already have the one to deliver.

```c++
if (output_size)
{
    // We have already the data, so this must fall on the floor
    char lostbuf[SRT_LIVE_MAX_PLSIZE];
    stat = ps->core().receiveMessage((lostbuf), SRT_LIVE_MAX_PLSIZE, (mctrl), CUDTUnited::ERH_RETURN);
```

### Buffering Packet

Here `buf` is different from `lostbuf` where the packet was read to.

```c++
if (seqdiff > 1)
{
    HLOGC(grlog.Debug,
            log << "@" << id << " %" << mctrl.pktseq << " #" << mctrl.msgno << " AHEAD base=%"
                << m_RcvBaseSeqNo);
    p->packet.assign(buf, buf + stat);
    p->mctrl = mctrl;
    break; // Don't read from that socket anymore.
}
```

### TODO

- [x] Fix `recvDiscard` stats (see TODO comment in the code)

### CODE REVIEW

**Comment by ethouris** [comment]
Not sure what this thing changes. Ignoring the packet is based on a premise - might be that not correctly stated - that the packet with given sequence number is already received. Note that this reception function relies on packets retrieved from single links at their play time, meaning, whatever is not delivered by these links, has been dropped according to overall rules of TLPKTDROP. Here if the `output_size` has been set, it means that the data for the next packet to deliver have been already read, the user's buffer filled with the payload, and whatever is being done here is to make the link shifted to read the "next position", that is, it should read everything up to the sequence number of the currently delivered packet.

Reading packets that came AHEAD of the current latest read sequence is done in another place, and these are being read to a spare buffer - if I remember correctly.

**Comment by maxsharabayko** [comment]
The issue is the following.

1. Group reads the next packet. output_size = non-zero
2. Iterating to the next read-ready member link, now reading to `lostbuf` and `mctl`.

```c++
if (output_size)
{
    // We have already the data, so this must fall on the floor
    char lostbuf[SRT_LIVE_MAX_PLSIZE];
    stat = ps->core().receiveMessage((lostbuf), SRT_LIVE_MAX_PLSIZE, (mctrl), CUDTUnited::ERH_RETURN);
```

4. Checking the sequence number of the packet. It it happens to be the AHEAD packet, saving `buf` instead of `lostbuf`.

```c++
if (seqdiff > 1)
{
    p->packet.assign(buf, buf + stat);
    p->mctrl = mctrl;
    break; // Don't read from that socket anymore.
}
```

**Result:** group buffered a packet with AHEAD `seqno`, but a different payload.

File: srtcore/group.cpp [hunk 1]
```diff
@@ -2372,21 +2372,20 @@ int CUDTGroup::recv(char* buf, int len, SRT_MSGCTRL& w_mc)
                 // by "more correct data" if found more appropriate later. But we have to
                 // copy these data anyway anywhere, even if they need to fall on the floor later.
                 int stat;
+                char lostbuf[SRT_LIVE_MAX_PLSIZE];
+                char* msgbuf = NULL;
                 if (output_size)
                 {
                     // We have already the data, so this must fall on the floor
-                    char lostbuf[SRT_LIVE_MAX_PLSIZE];
+                    msgbuf = lostbuf;
```
Comment (ethouris) [inline srtcore/group.cpp:2380]: I think you better fix the explanation here as it's no longer true. The `lostbuf` isn't also the best name now, as this is now a "maybe lost buf". Maybe `sparebuf` would be more appropriate, and the comment above should not speak about "falling on the floor", but rather sound like "most likely this is an already received packet, but you never know what packet it is until you read it. In case when it turns out to be an ahead packet received by having the expected current packet being TLPKTDROP-ed from this link, this packet will have to be saved as ahead packet instead."

File: srtcore/group.cpp [hunk 2]
```diff
@@ -2372,21 +2372,20 @@ int CUDTGroup::recv(char* buf, int len, SRT_MSGCTRL& w_mc)
...
                     stat = ps->core().receiveMessage((lostbuf), SRT_LIVE_MAX_PLSIZE, (mctrl), CUDTUnited::ERH_RETURN);
                     HLOGC(grlog.Debug,
-                          log << "group/recv: @" << id << " IGNORED data with %" << mctrl.pktseq << " #" << mctrl.msgno
-                              << ": " << (stat <= 0 ? "(NOTHING)" : BufferStamp(lostbuf, stat)));
-                    if (stat > 0)
-                    {
-                        m_stats.recvDiscard.Update(stat);
-                    }
+                          log << "group/recv: @" << id << " EXTRACTED EXTRA data with %" << mctrl.pktseq
```
Comment (ethouris) [inline srtcore/group.cpp:2383]: I think this LOG now deserves to display also the information about which pktseq it has extracted - and whether this packet should be IGNORED or stored as AHEAD.

**Review by ethouris — COMMENTED** [review]
Minor things to consider.

File: srtcore/group.cpp (hunk 1 above)
Comment (maxsharabayko) [reply srtcore/group.cpp]: Renamed to `extrabuf`.

File: srtcore/group.cpp (hunk 2 above)
Comment (maxsharabayko) [reply srtcore/group.cpp:2384]: Added "TO STORE" / "TO IGNORE" to the log message.

**Review by ethouris — APPROVED** [review]
