### PR TITLE
Fixed buggy update_usock

### LINKED ISSUE #916: srt_epoll_update_usock seem to be broken in v1.4.0
if srt_epoll_update_usock is used to disable SRT_EPOLL_OUT for SRT sender srt_epoll_wait continues returning output event. I guess the issue is related to #893 and #906 as sender is not able to disable getting OUT event when there is no data to send.

[test_srt.cpp.gz](https://github.com/Haivision/srt/files/3757718/test_srt.cpp.gz)

Please find attached example UT for reproducing the issue, the test passes on v1.3.4 but fails on v1.4.0 expecting timeout error from srt_epoll_wait call switching to waiting only for SRT_EPOLL_ERR:

/home/bullet/workshop/srt-1.4.0.git/test/test_srt.cpp:83: Failure
Expected equality of these values:
  SRT_ERROR
    Which is: -1
  srt_epoll_wait(client_pollid, read, &rlen, write, &wlen, 1000, 0, 0, 0, 0)
    Which is: 1

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #916

### CODE REVIEW

File: test/test_epoll.cpp [hunk 1]
```diff
@@ -555,3 +556,205 @@ TEST(CEPoll, ThreadedUpdate)
...
+
+int g_server_pollid = SRT_ERROR;
+
+void serverSocket()
+{
+    int yes = 1;
+    int no = 0;
+
+	SRTSOCKET m_bindsock = srt_socket(AF_INET, SOCK_DGRAM, 0);
+	ASSERT_NE(m_bindsock, SRT_ERROR);
```
Comment (maxlovic) [inline test/test_epoll.cpp]: Replace tabs here and in other places.

File: test/test_epoll.cpp [hunk 2]
```diff
@@ -555,3 +556,205 @@ TEST(CEPoll, ThreadedUpdate)
     EXPECT_EQ(srt_cleanup(), 0);
 }
 
+
+int g_client_pollid = SRT_ERROR;
+SRTSOCKET g_client_sock = SRT_ERROR;
+
+void clientSocket()
```
Comment (maxlovic) [inline test/test_epoll.cpp]: Please use a test fixture instead of global variables and global functions.

File: srtcore/epoll.cpp [hunk 3]
```diff
@@ -230,22 +230,44 @@ int CEPoll::update_usock(const int eid, const SRTSOCKET& u, const int* events)
...
         CEPollDesc::Wait& wait = iter_new.first->second;
-        int newstate = wait.watch & wait.state;
-        if (newstate)
+        if (!iter_new.second)
         {
-            p->second.addEventNotice(wait, u, newstate);
+            // The object exists. We only are certain about the `u`
+            // parameter, but others are probably unchanged. Change them
+            // forcefully and take out notices that are no longer valid.
+            int removable = wait.watch & ~evts;
```
Comment (maxlovic) [inline srtcore/epoll.cpp]: add `const`

File: srtcore/epoll.cpp [hunk 4]
```diff
@@ -230,22 +230,44 @@ int CEPoll::update_usock(const int eid, const SRTSOCKET& u, const int* events)
...
+            wait.watch = evts;
+            if (edgeTriggered)
+                wait.edge = evts;
+
+            // Now it should look exactly like newly added
+            // and the state is also updated
         }
-        else if (!iter_new.second) // if it was freshly added, no notice object exists
+
+        int newstate = wait.watch & wait.state;
```
Comment (maxlovic) [inline srtcore/epoll.cpp]: Add `const`.
