### PR TITLE
[core] Fixed packet drop when reading from members

### LINKED ISSUE #1755: [BUG] Main/backup: The group drops packets at the very beginning of the transmission
## Describe the bug

During testing Connection Bonding (main/backup algorithm) I've encountered the following problem: 

The group drops packets at the very beginning of the transmission.
The connection over backup link happens first as it's the faster link and transmission starts over backup link.
Then main link is connected in a while and the transmission continues over main link.
There are no dropped packets on both main and backup link, however there are **2 dropped packets** at the group level.
This happens in the moment of switch.

Another problem is that there is no log from the library in `srt-xtransmit` (receiver side) when the drop happens at the group level. There is only a message from individual sockets (main link when it becomes up after 2 s shutdown).

## To Reproduce

Test procedure with the detailed description of the test setup, test cases, and `srt-xtransmit` commands for reproduction can be found [here](https://stash.haivision.com/projects/SAS/repos/srt-devbook/browse/srt-protocol/connection-bonding/test-reports/release-v1.5.0/dynamic-link-stability-timeout-4th-iteration/test-procedure.md). Briefly:

Test Setup is the combination of small Flip&Flop (CentOS 7) and big LanForge with the following links connected:

```
FLIP                 ---- LanForge  ----                 FLOP

enp7s0 (192.168.4.1) ---- eth2-eth3 ---- (192.168.4.2) enp7s0    (Main link)
enp8s0 (192.168.3.1) ---- eth4-eth5 ---- (192.168.3.2) enp8s0    (Backup link)
```

**SRT version:**
- [PR 13](https://github.com/maxsharabayko/srt/pull/13), `develop/main-backup` branch:
   commit 6cd05372ae8f1b35d2fe48435db90c8bd3dfaf31 (HEAD -> develop/main-backup, origin/develop/main-backup)
   Author: Maxim Sharabayko
   Date:   Thu Jan 21 15:02:38 2021 +0100
   [core] Added socket ID to RCV-DROP log message
   
- `srt-xtransmit` with Connection Bonding support (`develop/bonding` branch):
   commit 5055a22b6a2ff4f5f59591f73d7a0a1c1ea2ef62 (HEAD -> develop/bonding, origin/develop/bonding)
   Author: Maxim Sharabayko
   Date:   Thu Jan 21 18:07:19 2021 +0100
   Printing SRC and DST URIs

**srt-xtransmit commands:**
```
# Sender
_build_bonding_main_backup/bin/srt-xtransmit generate "srt://192.168.4.2:4200?latency=800&grouptype=backup&weight=75" srt://192.168.3.2:4201?weight=25 --sendrate 1Mbps --duration 120s --enable-metrics --statsfile group-snd-stats.csv --statsfreq 1s -v
```

```
# Receiver
_build_bonding_main_backup/bin/srt-xtransmit receive srt://:4200?latency=800 srt://:4201 --enable-metrics --metricsfile group-rcv-metrics.csv --metricsfreq 1s --statsfile group-rcv-stats.csv --statsfreq 1s -v
```

**Failed test case:**

Test Case 1. Main link shutdown for 2 seconds (less than `SRTO_PEERIDLETIMEOUT` = 5 s)

| Main Link (enp7s0)                              | Backup Link (enp8s0)                       | Bitrate, Mbps  | SRT Options  | 
| ------------------------------------ | ----------------------------------- | -------------- | ------------- | 
| RTT1 = 200 ms (slow link)                  | RTT2 = 100 ms                                   | 1                       | latency=800  | 

1 out of 5 test runs - failed

To emulate link shutdown use the following command:
```
sleep 60 && echo ifdown $(date +"%F %T,%3N") && sudo ifdown enp7s0 && sleep 2 && echo ifup $(date +"%F %T,%3N") && sudo ifup enp7s0
```

Statistics and screenshots are attached.
[srt #1755.zip](https://github.com/Haivision/srt/files/5850026/srt.1755.zip)

### PR DESCRIPTION
**Pull request by maxsharabayko**
TSBPD thread of a group member might not yet trigger epoll read-ready event, while it is potentially ready.
If another member signals read-readiness ahead of the current position it will result in a packet drop by a group.

This PR changes the logic of a group waiting for read-readiness.
When a notification is received, not only notified sockets are added to the reading list, but also those not notified, but with receiver buffer ready to read.

Fixes #1755 
Fixes: #1757 (likely the same reason, tests show no losses when switching back)

### CODE REVIEW

File: srtcore/group.cpp [hunk 1]
```diff
@@ -2078,21 +2078,36 @@ vector<CUDTSocket*> CUDTGroup::recv_WaitForReadReady(const vector<CUDTSocket*>&
...
 
-        // Check if this socket is in aheads
-        // If so, don't read from it, wait until the ahead is flushed.
-        SRTSOCKET   id = i->first;
-        CUDTSocket* ps = m_pGlobal->locateSocket_LOCKED(id);
-        if (ps)
-            readReady.push_back(ps);
+            int32_t skiptoseqno = SRT_SEQNO_NONE;
+            bool    passack     = true; // Get next packet to wait for even if not acked
+            const bool rxready = sock->core().m_pRcvBuffer->getRcvFirstMsg((tsbpdtime), (passack), (skiptoseqno), (current_pkt_seq));
```
Comment (ethouris) [inline srtcore/group.cpp:2104]: Please look into the core.cpp file, there must be a shorted function that designates the same thing.

Comment (maxsharabayko) [reply srtcore/group.cpp:2104]: I don't see any. 👀

Comment (ethouris) [reply srtcore/group.cpp:2104]: Well, ok, but there's `CRcvBuffer::isRcvDataReady` that is shorter and easier to use.

Comment (maxsharabayko) [reply srtcore/group.cpp:2104]: Good point.
It is not implemented, but my concern here is the following. What if the next packet is there, but it is not ready to be read? This can happen only if it is not yet acknowledged and thus can't be read from the buffer.
The idle link is synchronized with the latest acknowledged position of the active link - so not the case for #1757 (the next packet is acknowledged).
But it may happen in run time. Not sure what's the proper way to handle this. Force ACK?

Comment (ethouris) [reply srtcore/group.cpp:2104]: The whole "app-based solution" works on a premise that TSBPD is signing off the same packet coming over different links at perfectly same time. This "signing off" is an action to do, and that was the problem here, but the rules aren't changed: you have a time to play, so you play, if the time hasn't come yet, it remains in the buffer and is not allowed to be extracted. ACK means nothing here because it should have happen way before the TSBPD play time has come. Of course, if you have a situation on the edge, that is, you have a case of asymmetric loss, so both links must do TLPKTDROP, but just different packets, the reading should still happen in the order of play time.

What you are fixing here is the problem that the epoll-based read-ready state isn't synchronized with rule-based read-ready state, which is simply defined by the fact that the head-of-the-queue packet's play time is in the past, just TSBPD was not given a chance to do this synchronization. Example:
```
Link1   Link2
  |       |
  5       5
  |       |
  *       6  <---NOW
  |       |       |
  7       *       V
  |       |
  8       8
```

If we have a hypothetical situation that NOW is the moment when packet 6 is ready to play, it is being read. Next time if the reading function "wakes up" (as the call times are application-controlled), let's say its NOW time is after the play time of packet 8. You attempt to read from all ready links, but TSBPD for Link1 did not restore the read-ready state after it was cleared due to lacking packet number 6 and it's not set as well at this moment. If you call this `CRcvBuffer::isRcvDataReady` function, it will find out that at the head of the queue there's a packet number 7, which simply **cannot be not ready to play when it was already found out that packet number 8 is**, as it is guaranteed that its time to play will be less than that of packet 8.

**Comment by maxsharabayko** [comment]
Changed `m_pRcvBuffer->getRcvFirstMsg(..)` to `m_pRcvBuffer->isRcvDataReady()`. Testing...

**Comment by maxsharabayko** [comment]
30 test runs, not losses 👍 

Receiver-caller

```shell
srt-xtransmit receive "srt://192.168.1.91:4200?grouptype=backup&weight=75&latency=800"
    "srt://192.168.1.91:4201?weight=25" --statsfile backup-stats-rcv.csv --statsfreq 1s --enable-metrics
```

Sender-listener

```shell
srt-xtransmit generate srt://:4200 srt://:4201 --sendrate 500kbps --duration 5s --enable-metrics --reconnect -v
```

| Main Link (port 4200)                         | Backup Link (port 4201)                 | Bitrate, Mbps  | SRT Latency | 
| ------------------------------------ | ----------------------------------- | -------------- | ------------- | 
| RTT1 = 200 ms, <br />weight 75 (slow link)   | RTT2 = 100 ms, <br />weight 25               | 0.5                     | 800 ms |

**Review by ethouris — APPROVED** [review]
